export const DASHBOARD_TABS = [
  { id: "overview", label: "Overview", icon: "ğŸ " },
  { id: "projects", label: "Projects", icon: "ğŸâ€”ï¸" },
  { id: "communities", label: "Communities", icon: "ğŸ˜ï¸" },
  { id: "market", label: "Market", icon: "ğŸâ€œŠ" },
  { id: "yields", label: "Yields", icon: "ğŸâ€™°" },
  { id: "compare", label: "Compare", icon: "âšâ€“ï¸" },
  { id: "eibor", label: "EIBOR", icon: "ğŸâ€œˆ" },
  { id: "developers", label: "Developers", icon: "ğŸ¢" },
  { id: "risks", label: "Risks", icon: "âš ï¸" },
  { id: "calculator", label: "Calculator", icon: "ğŸ§®" },
  { id: "intel", label: "Intel", icon: "ğŸâ€" },
  { id: "mega", label: "Mega Projects", icon: "ğŸŒ†" },
  { id: "financials", label: "Financials", icon: "ğŸâ€œ‹" },
  { id: "segments", label: "Segments", icon: "ğŸ¯" },
  { id: "radar", label: "Radar", icon: "ğŸâ€œ¡" },
  { id: "phases", label: "Phases", icon: "ğŸâ€„" },
  { id: "history", label: "History", icon: "ğŸâ€¢" },
  { id: "roi", label: "ROI", icon: "ğŸâ€™¹" },
  { id: "news", label: "News", icon: "ğŸâ€œ°" },
  { id: "reports", label: "Reports", icon: "ğŸâ€œ„" },
  { id: "alerts", label: "Alerts", icon: "ğŸâ€â€" },
  { id: "account", label: "Account", icon: "ğŸâ€˜¤" },
  { id: "upgrade", label: "Upgrade", icon: "â­" },
];

export const ADMIN_TABS = [
  { id: "overview", label: "Overview", icon: "ğŸ " },
  { id: "projects", label: "Projects", icon: "ğŸâ€”ï¸" },
  { id: "communities", label: "Communities", icon: "ğŸ˜ï¸" },
  { id: "users", label: "Users", icon: "ğŸâ€˜¥" },
  { id: "subscriptions", label: "Subscriptions", icon: "ğŸâ€™³" },
  { id: "yields", label: "Yields", icon: "ğŸâ€™°" },
  { id: "eibor", label: "EIBOR", icon: "ğŸâ€œˆ" },
  { id: "leads", label: "Leads", icon: "ğŸ¯" },
  { id: "kyc", label: "KYC", icon: "ğŸªª" },
  { id: "support", label: "Support", icon: "ğŸ§" },
  { id: "cancellations", label: "Cancellations", icon: "âŒ" },
  { id: "audit", label: "Audit Log", icon: "ğŸâ€œ‹" },
  { id: "analytics", label: "Analytics", icon: "ğŸâ€œŠ" },
  { id: "revenue", label: "Revenue", icon: "ğŸâ€™µ" },
  { id: "notifications", label: "Notifications", icon: "ğŸâ€â€" },
  { id: "settings", label: "Settings", icon: "âšâ„¢ï¸" },
  { id: "seed", label: "Seed Data", icon: "ğŸŒ±" },
  { id: "backups", label: "Backups", icon: "ğŸâ€™¾" },
  { id: "roles", label: "Roles", icon: "ğŸâ€" },
];
