export const DASHBOARD_TABS = [
  { id: "overview", label: "Overview", icon: "🏠" },
  { id: "projects", label: "Projects", icon: "🏗️" },
  { id: "communities", label: "Communities", icon: "🏘️" },
  { id: "market", label: "Market", icon: "📊" },
  { id: "yields", label: "Yields", icon: "💰" },
  { id: "compare", label: "Compare", icon: "⚖️" },
  { id: "eibor", label: "EIBOR", icon: "📈" },
  { id: "developers", label: "Developers", icon: "🏢" },
  { id: "risks", label: "Risks", icon: "⚠️" },
  { id: "calculator", label: "Calculator", icon: "🧮" },
  { id: "intel", label: "Intel", icon: "🔍" },
  { id: "mega", label: "Mega Projects", icon: "🌆" },
  { id: "financials", label: "Financials", icon: "📋" },
  { id: "segments", label: "Segments", icon: "🎯" },
  { id: "radar", label: "Radar", icon: "📡" },
  { id: "phases", label: "Phases", icon: "🔄" },
  { id: "history", label: "History", icon: "🕐" },
  { id: "roi", label: "ROI", icon: "💹" },
  { id: "news", label: "News", icon: "📰" },
  { id: "reports", label: "Reports", icon: "📄" },
  { id: "alerts", label: "Alerts", icon: "🔔" },
  { id: "account", label: "Account", icon: "👤" },
  { id: "upgrade", label: "Upgrade", icon: "⭐" },
];

export const ADMIN_TABS = [
  { id: "overview", label: "Overview", icon: "🏠" },
  { id: "projects", label: "Projects", icon: "🏗️" },
  { id: "communities", label: "Communities", icon: "🏘️" },
  { id: "users", label: "Users", icon: "👥" },
  { id: "subscriptions", label: "Subscriptions", icon: "💳" },
  { id: "yields", label: "Yields", icon: "💰" },
  { id: "eibor", label: "EIBOR", icon: "📈" },
  { id: "leads", label: "Leads", icon: "🎯" },
  { id: "kyc", label: "KYC", icon: "🪪" },
  { id: "support", label: "Support", icon: "🎧" },
  { id: "cancellations", label: "Cancellations", icon: "❌" },
  { id: "audit", label: "Audit Log", icon: "📋" },
  { id: "analytics", label: "Analytics", icon: "📊" },
  { id: "revenue", label: "Revenue", icon: "💵" },
  { id: "notifications", label: "Notifications", icon: "🔔" },
  { id: "settings", label: "Settings", icon: "⚙️" },
  { id: "seed", label: "Seed Data", icon: "🌱" },
  { id: "backups", label: "Backups", icon: "💾" },
  { id: "roles", label: "Roles", icon: "🔐" },
];
