export const danubeIdentity = {
  id: "danube", name: "Danube Properties", legalName: "Danube Properties LLC",
  founded: 2014, website: "https://danubeproperties.com", color: "#E74C3C",
  dld: { transactions: 1129, avgPrice: 3705440, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

// Danube Properties — Verified from official site + DLD Q1 2026
// Source: https://danubeproperties.com
// Generated: 2026-04-01 | 29 projects
export const danubeProjects = [
  { id:"dan-1", developerId:"danube", name:"Shahrukhz by Danube", officialUrl:"https://danubeproperties.com/portfolio/shahrukhz/",
    community:"Al Sufouh", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q2 2029", price:1700000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-2", developerId:"danube", name:"Breez by Danube", officialUrl:"https://danubeproperties.com/portfolio/breez/",
    community:"Dubai Maritime City", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q1 2029", price:1304000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-3", developerId:"danube", name:"Aspirz by Danube", officialUrl:"https://danubeproperties.com/portfolio/aspirz/",
    community:"Dubai Sports City", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q4 2028", price:866000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-4", developerId:"danube", name:"Sparklz by Danube", officialUrl:"https://danubeproperties.com/portfolio/sparklz/",
    community:"Al Furjan", type:"Apartments", beds:"1–3BR",
    status:"Off Plan", handover:"Q2 2028", price:1811000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-5", developerId:"danube", name:"Timez by Danube", officialUrl:"https://danubeproperties.com/portfolio/timez/",
    community:"Dubai Silicon Oasis", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q2 2028", price:1351000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-6", developerId:"danube", name:"Bayz 102 by Danube", officialUrl:"https://danubeproperties.com/portfolio/bayz-102/",
    community:"Business Bay", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q4 2028", price:2295000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-7", developerId:"danube", name:"Oasiz by Danube", officialUrl:"https://danubeproperties.com/portfolio/oasiz/",
    community:"Dubai Silicon Oasis", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q4 2027", price:844000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-8", developerId:"danube", name:"Diamondz by Danube", officialUrl:"https://danubeproperties.com/portfolio/diamondz/",
    community:"JLT", type:"Apartments", beds:"1–3BR",
    status:"Under Construction", handover:"Q4 2027", price:2500000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-9", developerId:"danube", name:"Bayz 101 by Danube", officialUrl:"https://danubeproperties.com/portfolio/bayz101/",
    community:"Business Bay", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q4 2027", price:1900000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-10", developerId:"danube", name:"Sportz by Danube", officialUrl:"https://danubeproperties.com/portfolio/sportz/",
    community:"Dubai Sports City", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q4 2026", price:900000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-11", developerId:"danube", name:"Oceanz by Danube T2", officialUrl:"https://danubeproperties.com/portfolio/oceanz/",
    community:"Dubai Maritime City", type:"Apartments", beds:"1–3BR",
    status:"Under Construction", handover:"Q1 2027", price:1988000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-12", developerId:"danube", name:"Elitz 3 by Danube", officialUrl:"https://danubeproperties.com/portfolio/elitz-3/",
    community:"JVC", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q4 2026", price:1434000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-13", developerId:"danube", name:"Elitz 2 by Danube", officialUrl:"https://danubeproperties.com/portfolio/elitz-2/",
    community:"JVC", type:"Apartments", beds:"1–3BR+TH",
    status:"Under Construction", handover:"Q4 2026", price:2290000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-14", developerId:"danube", name:"Fashionz by Danube", officialUrl:"https://danubeproperties.com/portfolio/fashionz/",
    community:"JVC", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q4 2026", price:1500000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-15", developerId:"danube", name:"Viewz by Danube", officialUrl:"https://danubeproperties.com/portfolio/viewz/",
    community:"JLT", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q2 2026", price:1800000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-16", developerId:"danube", name:"Elitz by Danube", officialUrl:"https://danubeproperties.com/portfolio/elitz/",
    community:"JVC", type:"Apartments", beds:"Studio–3BR+TH",
    status:"Ready", handover:"Q4 2025", price:1100000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-17", developerId:"danube", name:"Petalz by Danube", officialUrl:"https://danubeproperties.com/portfolio/petalz/",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Q4 2025", price:800000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-18", developerId:"danube", name:"Skyz by Danube", officialUrl:"https://danubeproperties.com/portfolio/skyz/",
    community:"Dubai Sports City", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Q4 2025", price:700000,
    payment:"1% monthly", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-19", developerId:"danube", name:"Opalz by Danube", officialUrl:"https://danubeproperties.com/portfolio/opalz/",
    community:"Dubai Silicon Oasis", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:750000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-20", developerId:"danube", name:"Gemz by Danube", officialUrl:"https://danubeproperties.com/portfolio/gemz/",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:700000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-21", developerId:"danube", name:"Pearlz by Danube", officialUrl:"https://danubeproperties.com/portfolio/pearlz/",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:650000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-22", developerId:"danube", name:"Wavez by Danube", officialUrl:"https://danubeproperties.com/portfolio/wavez/",
    community:"Dubai Residence Complex", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:600000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-23", developerId:"danube", name:"Bayz by Danube", officialUrl:"https://danubeproperties.com/portfolio/bayz/",
    community:"Business Bay", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:1100000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-24", developerId:"danube", name:"Lawnz by Danube", officialUrl:"https://danubeproperties.com/portfolio/lawnz/",
    community:"International City", type:"Apartments", beds:"Studio–1BR",
    status:"Ready", handover:"Delivered", price:450000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-25", developerId:"danube", name:"Starz by Danube", officialUrl:"https://danubeproperties.com/portfolio/starz/",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:580000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-26", developerId:"danube", name:"Glamz by Danube", officialUrl:"https://danubeproperties.com/portfolio/glamz/",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:550000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-27", developerId:"danube", name:"Miraclz by Danube", officialUrl:"https://danubeproperties.com/portfolio/miraclz/",
    community:"JVC", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:600000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-28", developerId:"danube", name:"Resortz by Danube", officialUrl:"https://danubeproperties.com/portfolio/resortz/",
    community:"Dubai Sports City", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:650000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"dan-29", developerId:"danube", name:"Dreamz by Danube", officialUrl:"https://danubeproperties.com/portfolio/dreamz/",
    community:"Al Furjan", type:"Townhouses", beds:"2–3BR TH",
    status:"Ready", handover:"Delivered", price:1200000,
    payment:"Ready", developer:"Danube Properties", color:"#E74C3C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
];