// Imtiaz Developments — Verified from official site + DLD Q1 2026
// Source: https://imtiaz.ae
// Projects: 21 | DLD Q1 2026 transactions: 735

export const imtiazIdentity = {
  id: "imtiaz", name: "Imtiaz Developments", legalName: "Imtiaz Developments LLC",
  founded: 1993, website: "https://imtiaz.ae", color: "#8E44AD",
  dld: { transactions: 735, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

export const imtiazProjects = [
  { id:"imt-1", developerId:"imtiaz", name:"Wynwood by Imtiaz",
    officialUrl:"https://imtiaz.ae/projects/wynwood",
    community:"Dubai Islands", type:"Apartments", beds:"1–4BR",
    status:"Off Plan", handover:"Q3 2027", price:2000000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-2", developerId:"imtiaz", name:"Beach Walk Residences 4",
    officialUrl:"https://imtiaz.ae/projects/beach-walk-4",
    community:"Dubai Islands", type:"Apartments", beds:"1–3BR",
    status:"Off Plan", handover:"Q4 2026", price:1942000,
    payment:"20/40/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-3", developerId:"imtiaz", name:"Beach Walk Residences 2",
    officialUrl:"https://imtiaz.ae/projects/beach-walk-2",
    community:"Dubai Islands", type:"Apartments", beds:"1–2BR",
    status:"Off Plan", handover:"Q3 2026", price:1900000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-4", developerId:"imtiaz", name:"Beach Walk Residences",
    officialUrl:"https://imtiaz.ae/projects/beach-walk",
    community:"Dubai Islands", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:2200000,
    payment:"Ready", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-5", developerId:"imtiaz", name:"Beach Walk Grand",
    officialUrl:"https://imtiaz.ae/projects/beach-walk-grand",
    community:"Dubai Islands", type:"Apartments", beds:"1BR+",
    status:"Off Plan", handover:"Q4 2026", price:3500000,
    payment:"20/40/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-6", developerId:"imtiaz", name:"Beach Walk Grand 2",
    officialUrl:"https://imtiaz.ae/projects/beach-walk-grand-2",
    community:"Dubai Islands", type:"Apartments", beds:"1–2BR",
    status:"Off Plan", handover:"Q4 2026", price:2050000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-7", developerId:"imtiaz", name:"Cotier House",
    officialUrl:"https://imtiaz.ae/projects/cotier-house",
    community:"Dubai Islands", type:"Apartments", beds:"1–3BR",
    status:"Off Plan", handover:"Q4 2026", price:2425000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-8", developerId:"imtiaz", name:"Sunset Bay by Imtiaz",
    officialUrl:"https://imtiaz.ae/projects/sunset-bay",
    community:"Dubai Islands", type:"Apartments", beds:"1–3BR",
    status:"Off Plan", handover:"Q2 2027", price:1690000,
    payment:"20/40/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-9", developerId:"imtiaz", name:"Pearl House",
    officialUrl:"https://imtiaz.ae/projects/pearl-house",
    community:"JVC", type:"Apartments", beds:"Studio–1BR",
    status:"Ready", handover:"Delivered", price:590000,
    payment:"Ready", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-10", developerId:"imtiaz", name:"Pearl House II",
    officialUrl:"https://imtiaz.ae/projects/pearl-house-ii",
    community:"JVC", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Q4 2025", price:600000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-11", developerId:"imtiaz", name:"Pearl House III",
    officialUrl:"https://imtiaz.ae/projects/pearl-house-iii",
    community:"JVC", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q3 2026", price:630000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-12", developerId:"imtiaz", name:"Luxor by Imtiaz",
    officialUrl:"https://imtiaz.ae/projects/luxor",
    community:"JVC", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q4 2026", price:676000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-13", developerId:"imtiaz", name:"Hyde Walk Residence",
    officialUrl:"https://imtiaz.ae/projects/hyde-walk",
    community:"Jumeirah Garden City", type:"Apartments", beds:"Studio–1BR",
    status:"Ready", handover:"Q4 2025", price:1500000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-14", developerId:"imtiaz", name:"Cove by Imtiaz",
    officialUrl:"https://imtiaz.ae/projects/cove",
    community:"Dubai Land", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q1 2027", price:580000,
    payment:"50/50", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-15", developerId:"imtiaz", name:"Cove Edition 1",
    officialUrl:"https://imtiaz.ae/projects/cove-edition",
    community:"Dubai Land", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q1 2027", price:688888,
    payment:"20/30/50", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-16", developerId:"imtiaz", name:"Cove Edition 2",
    officialUrl:"https://imtiaz.ae/projects/cove-edition-2",
    community:"Dubai Land", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q3 2026", price:650000,
    payment:"20/30/50", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-17", developerId:"imtiaz", name:"Cove Edition 3",
    officialUrl:"https://imtiaz.ae/projects/cove-edition-3",
    community:"Dubai Land", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q4 2026", price:670000,
    payment:"20/30/50", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-18", developerId:"imtiaz", name:"Cove Edition 4",
    officialUrl:"https://imtiaz.ae/projects/cove-edition-4",
    community:"Dubai Land", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q1 2027", price:675000,
    payment:"20/30/50", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-19", developerId:"imtiaz", name:"Cove Edition 5",
    officialUrl:"https://imtiaz.ae/projects/cove-edition-5",
    community:"Dubai Land", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q2 2027", price:734692,
    payment:"20/30/50", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-20", developerId:"imtiaz", name:"Cove Grand by Imtiaz",
    officialUrl:"https://imtiaz.ae/projects/cove-grand",
    community:"Dubai Land", type:"Apartments", beds:"1BR",
    status:"Off Plan", handover:"Q2 2027", price:741000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"imt-21", developerId:"imtiaz", name:"Westwood by Imtiaz",
    officialUrl:"https://imtiaz.ae/projects/westwood",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q2 2026", price:700000,
    payment:"60/40", developer:"Imtiaz Developments", color:"#8E44AD",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
];