/* ─── DXB ANALYTICS — MASTER DATA FILE ─── */
/* Source: Emaar THE BEAST Excel + DLD + DXBinteract + Yahoo Finance */

// S16: T theme lives in src/theme.js
// Re-exported here for files that still import T from data.js (LandingPage, ProjectManager etc)
export { T } from "./theme";

/* ─── 48 EMAAR PROJECTS (from Excel) ─── */
export const emaarProjects = [
  {
    id:"emaar-1",
    developerId:"emaar",
    name:"The Golf Residence",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q2 2026",
    price:1750000,
    sizeFrom:750,
    sizeTo:2200,
    ppsf:2333,
    payment:"20/30/50",
    construction:80,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/the-golf-residence-at-dubai-hills-estate/",
    unitBreakdown:[{type:"1BR",sqftFrom:750,sqftTo:950,priceFrom:1750000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:2800000},{type:"3BR",sqftFrom:1800,sqftTo:2200,priceFrom:4200000}]
  },
  {
    id:"emaar-2",
    developerId:"emaar",
    name:"Hills Park",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q2 2026",
    price:1210000,
    sizeFrom:650,
    sizeTo:1800,
    ppsf:1862,
    payment:"80/20",
    construction:75,
    branded:false,
    brand:"—",
    tier:"Mid-Market",
    emaarUrl:"https://properties.emaar.com/en/properties/hills-park-at-dubai-hills-estate/",
    unitBreakdown:[{type:"1BR",sqftFrom:650,sqftTo:800,priceFrom:1210000},{type:"2BR",sqftFrom:1100,sqftTo:1350,priceFrom:2050000},{type:"3BR",sqftFrom:1600,sqftTo:1800,priceFrom:2990000}]
  },
  {
    id:"emaar-3",
    developerId:"emaar",
    name:"Golf Grand",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q1 2027",
    price:1529388,
    sizeFrom:700,
    sizeTo:2100,
    ppsf:2185,
    payment:"10/80/10",
    construction:96,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/golf-grand-at-dubai-hills-estate/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1529388},{type:"2BR",sqftFrom:1150,sqftTo:1450,priceFrom:2513000},{type:"3BR",sqftFrom:1700,sqftTo:2100,priceFrom:3714000}]
  },
  {
    id:"emaar-4",
    developerId:"emaar",
    name:"Parkside Views",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apts & TH",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q3 2027",
    price:1450000,
    sizeFrom:900,
    sizeTo:2800,
    ppsf:1933,
    payment:"10/80/10",
    construction:74,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/parkside-views-at-dubai-hills-estate/",
    unitBreakdown:[{type:"1BR",sqftFrom:900,sqftTo:1100,priceFrom:1450000},{type:"2BR",sqftFrom:1400,sqftTo:1700,priceFrom:2704000},{type:"3BR",sqftFrom:2200,sqftTo:2800,priceFrom:4253000}]
  },
  {
    id:"emaar-5",
    developerId:"emaar",
    name:"Greenside Residence",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q3 2027",
    price:1645888,
    sizeFrom:700,
    sizeTo:2000,
    ppsf:2347,
    payment:"10/80/10",
    construction:61,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/greenside-residence-at-golf-place/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1645888},{type:"2BR",sqftFrom:1150,sqftTo:1450,priceFrom:2699000},{type:"3BR",sqftFrom:1650,sqftTo:2000,priceFrom:3868000}]
  },
  {
    id:"emaar-6",
    developerId:"emaar",
    name:"Club Drive",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q1 2028",
    price:1630000,
    sizeFrom:700,
    sizeTo:2100,
    ppsf:2329,
    payment:"10/80/10",
    construction:45,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/club-drive-at-dubai-hills-estate/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1630000},{type:"2BR",sqftFrom:1150,sqftTo:1450,priceFrom:2678000},{type:"3BR",sqftFrom:1700,sqftTo:2100,priceFrom:3962000}]
  },
  {
    id:"emaar-7",
    developerId:"emaar",
    name:"Golf Hillside",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apartments",
    beds:"1-3BR",
    status:"Off-Plan",
    handover:"Q4 2028",
    price:1700000,
    sizeFrom:700,
    sizeTo:2100,
    ppsf:2429,
    payment:"80/20",
    construction:5,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/golf-hillside-at-dubai-hills-estate/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1700000},{type:"2BR",sqftFrom:1150,sqftTo:1450,priceFrom:2793000},{type:"3BR",sqftFrom:1700,sqftTo:2100,priceFrom:4131000}]
  },
  {
    id:"emaar-8",
    developerId:"emaar",
    name:"Golf Vedanta",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Villas",
    beds:"4-6BR",
    status:"Off-Plan",
    handover:"Q4 2029",
    price:14000000,
    sizeFrom:6500,
    sizeTo:14000,
    ppsf:2154,
    payment:"80/20",
    construction:0,
    branded:false,
    brand:"—",
    tier:"Ultra-Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/golf-vedanta-at-dubai-hills-estate/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:6500,sqftTo:8000,priceFrom:14000000},{type:"5BR Villa",sqftFrom:8500,sqftTo:10500,priceFrom:18300000},{type:"6BR Villa",sqftFrom:11000,sqftTo:14000,priceFrom:23750000}]
  },
  {
    id:"emaar-9",
    developerId:"emaar",
    name:"Creek Waters",
    community:"Dubai Creek Harbour",
    district:"Creek Harbour",
    type:"Apartments",
    beds:"1-4BR",
    status:"Under Construction",
    handover:"Q2 2026",
    price:1440000,
    sizeFrom:685,
    sizeTo:3170,
    ppsf:2102,
    payment:"80/20",
    construction:90,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/creek-waters-at-dubai-creek-harbour/",
    unitBreakdown:[{type:"1BR",sqftFrom:685,sqftTo:850,priceFrom:1440000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:2520000},{type:"3BR",sqftFrom:1800,sqftTo:2200,priceFrom:3780000},{type:"4BR",sqftFrom:2600,sqftTo:3170,priceFrom:5460000}]
  },
  {
    id:"emaar-10",
    developerId:"emaar",
    name:"Creek Waters 2",
    community:"Dubai Creek Harbour",
    district:"Creek Harbour",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q3 2026",
    price:1550000,
    sizeFrom:700,
    sizeTo:2200,
    ppsf:2214,
    payment:"80/20",
    construction:80,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/creek-waters-2-at-dubai-creek-harbour/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1550000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:2654000},{type:"3BR",sqftFrom:1800,sqftTo:2200,priceFrom:3985000}]
  },
  {
    id:"emaar-11",
    developerId:"emaar",
    name:"Creek Gate",
    community:"Dubai Creek Harbour",
    district:"Creek Harbour",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q2 2027",
    price:1380000,
    sizeFrom:650,
    sizeTo:1900,
    ppsf:2123,
    payment:"80/20",
    construction:65,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/creek-gate-at-dubai-creek-harbour/",
    unitBreakdown:[{type:"1BR",sqftFrom:650,sqftTo:820,priceFrom:1380000},{type:"2BR",sqftFrom:1100,sqftTo:1400,priceFrom:2334000},{type:"3BR",sqftFrom:1600,sqftTo:1900,priceFrom:3396000}]
  },
  {
    id:"emaar-12",
    developerId:"emaar",
    name:"Savanna",
    community:"Dubai Creek Harbour",
    district:"Creek Harbour",
    type:"Apartments",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q4 2028",
    price:1600000,
    sizeFrom:700,
    sizeTo:3000,
    ppsf:2286,
    payment:"80/20",
    construction:10,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/savanna-at-dubai-creek-harbour/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1600000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:2743000},{type:"3BR",sqftFrom:1800,sqftTo:2200,priceFrom:4114000},{type:"4BR",sqftFrom:2500,sqftTo:3000,priceFrom:5714000}]
  },
  {
    id:"emaar-13",
    developerId:"emaar",
    name:"The Cove II",
    community:"Dubai Creek Harbour",
    district:"Creek Harbour",
    type:"Apartments",
    beds:"1-3BR",
    status:"Off-Plan",
    handover:"Q2 2028",
    price:1800000,
    sizeFrom:780,
    sizeTo:2500,
    ppsf:2308,
    payment:"80/20",
    construction:15,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/the-cove-ii-at-dubai-creek-harbour/",
    unitBreakdown:[{type:"1BR",sqftFrom:780,sqftTo:960,priceFrom:1800000},{type:"2BR",sqftFrom:1300,sqftTo:1600,priceFrom:3000000},{type:"3BR",sqftFrom:2000,sqftTo:2500,priceFrom:4616000}]
  },
  {
    id:"emaar-14",
    developerId:"emaar",
    name:"Palace Residences North",
    community:"Dubai Creek Harbour",
    district:"Creek Harbour",
    type:"Apartments",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q4 2029",
    price:2800000,
    sizeFrom:750,
    sizeTo:4000,
    ppsf:3733,
    payment:"80/20",
    construction:0,
    branded:true,
    brand:"Palace",
    tier:"Luxury Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/palace-residences-north-at-dubai-creek-harbour/",
    unitBreakdown:[{type:"1BR",sqftFrom:750,sqftTo:950,priceFrom:2800000},{type:"2BR",sqftFrom:1300,sqftTo:1600,priceFrom:4853000},{type:"3BR",sqftFrom:2000,sqftTo:2500,priceFrom:7466000},{type:"4BR",sqftFrom:3200,sqftTo:4000,priceFrom:11946000}]
  },
  {
    id:"emaar-15",
    developerId:"emaar",
    name:"Address Residences Dubai Opera",
    community:"Downtown Dubai",
    district:"Downtown Dubai",
    type:"Apts & PH",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q4 2027",
    price:3900000,
    sizeFrom:800,
    sizeTo:6000,
    ppsf:4875,
    payment:"10/80/10",
    construction:20,
    branded:true,
    brand:"Address",
    tier:"Ultra-Lux Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/address-residences-dubai-opera/",
    unitBreakdown:[{type:"1BR",sqftFrom:800,sqftTo:1000,priceFrom:3900000},{type:"2BR",sqftFrom:1400,sqftTo:1800,priceFrom:6825000},{type:"3BR",sqftFrom:2200,sqftTo:2800,priceFrom:10725000},{type:"4BR PH",sqftFrom:4000,sqftTo:6000,priceFrom:19500000}]
  },
  {
    id:"emaar-16",
    developerId:"emaar",
    name:"Forte",
    community:"Downtown Dubai",
    district:"Downtown Dubai",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q3 2026",
    price:2200000,
    sizeFrom:700,
    sizeTo:2400,
    ppsf:3143,
    payment:"60/40",
    construction:85,
    branded:false,
    brand:"—",
    tier:"Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/forte-at-downtown-dubai/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:2200000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:3771000},{type:"3BR",sqftFrom:1900,sqftTo:2400,priceFrom:5971000}]
  },
  {
    id:"emaar-17",
    developerId:"emaar",
    name:"St Regis Residences",
    community:"Downtown Dubai",
    district:"Downtown Dubai",
    type:"Apts & PH",
    beds:"1-4BR",
    status:"Under Construction",
    handover:"Q2 2026",
    price:4200000,
    sizeFrom:900,
    sizeTo:7000,
    ppsf:4667,
    payment:"60/40",
    construction:88,
    branded:true,
    brand:"St Regis",
    tier:"Ultra-Lux Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/st-regis-residences-downtown/",
    unitBreakdown:[{type:"1BR",sqftFrom:900,sqftTo:1100,priceFrom:4200000},{type:"2BR",sqftFrom:1500,sqftTo:1900,priceFrom:7000000},{type:"3BR",sqftFrom:2400,sqftTo:3000,priceFrom:11200000},{type:"4BR PH",sqftFrom:5000,sqftTo:7000,priceFrom:23333000}]
  },
  {
    id:"emaar-18",
    developerId:"emaar",
    name:"Beach Mansion",
    community:"Emaar Beachfront",
    district:"Emaar Beachfront",
    type:"Apartments",
    beds:"1-4BR",
    status:"Under Construction",
    handover:"Q4 2026",
    price:2800000,
    sizeFrom:750,
    sizeTo:4500,
    ppsf:3733,
    payment:"80/20",
    construction:75,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/beach-mansion-at-emaar-beachfront/",
    unitBreakdown:[{type:"1BR",sqftFrom:750,sqftTo:950,priceFrom:2800000},{type:"2BR",sqftFrom:1300,sqftTo:1600,priceFrom:4853000},{type:"3BR",sqftFrom:2000,sqftTo:2500,priceFrom:7466000},{type:"4BR",sqftFrom:3500,sqftTo:4500,priceFrom:13066000}]
  },
  {
    id:"emaar-19",
    developerId:"emaar",
    name:"Beach Vista",
    community:"Emaar Beachfront",
    district:"Emaar Beachfront",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q2 2026",
    price:2500000,
    sizeFrom:700,
    sizeTo:2200,
    ppsf:3571,
    payment:"80/20",
    construction:90,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/beach-vista-at-emaar-beachfront/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:2500000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:4285000},{type:"3BR",sqftFrom:1800,sqftTo:2200,priceFrom:6428000}]
  },
  {
    id:"emaar-20",
    developerId:"emaar",
    name:"Seapoint",
    community:"Emaar Beachfront",
    district:"Emaar Beachfront",
    type:"Apts & PH",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q4 2027",
    price:3200000,
    sizeFrom:750,
    sizeTo:5000,
    ppsf:4267,
    payment:"80/20",
    construction:30,
    branded:false,
    brand:"—",
    tier:"Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/seapoint-at-emaar-beachfront/",
    unitBreakdown:[{type:"1BR",sqftFrom:750,sqftTo:950,priceFrom:3200000},{type:"2BR",sqftFrom:1300,sqftTo:1600,priceFrom:5546000},{type:"3BR",sqftFrom:2000,sqftTo:2500,priceFrom:8533000},{type:"4BR PH",sqftFrom:3800,sqftTo:5000,priceFrom:16200000}]
  },
  {
    id:"emaar-21",
    developerId:"emaar",
    name:"Address Beach Resort Residences",
    community:"Emaar Beachfront",
    district:"Emaar Beachfront",
    type:"Apts & PH",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q2 2028",
    price:4500000,
    sizeFrom:800,
    sizeTo:6000,
    ppsf:5625,
    payment:"80/20",
    construction:15,
    branded:true,
    brand:"Address",
    tier:"Ultra-Lux Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/address-beach-resort-residences/",
    unitBreakdown:[{type:"1BR",sqftFrom:800,sqftTo:1000,priceFrom:4500000},{type:"2BR",sqftFrom:1400,sqftTo:1800,priceFrom:7875000},{type:"3BR",sqftFrom:2200,sqftTo:2800,priceFrom:12375000},{type:"4BR PH",sqftFrom:4500,sqftTo:6000,priceFrom:25312000}]
  },
  {
    id:"emaar-22",
    developerId:"emaar",
    name:"Golf Place Terraces",
    community:"Golf Place",
    district:"Golf Place",
    type:"Villas",
    beds:"4-6BR",
    status:"Under Construction",
    handover:"Q4 2026",
    price:9800000,
    sizeFrom:5000,
    sizeTo:12000,
    ppsf:1960,
    payment:"80/20",
    construction:75,
    branded:false,
    brand:"—",
    tier:"Ultra-Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/golf-place-terraces-at-dubai-hills-estate/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:5000,sqftTo:6500,priceFrom:9800000},{type:"5BR Villa",sqftFrom:7000,sqftTo:8500,priceFrom:13720000},{type:"6BR Villa",sqftFrom:10000,sqftTo:12000,priceFrom:19600000}]
  },
  {
    id:"emaar-23",
    developerId:"emaar",
    name:"Golf Place II",
    community:"Golf Place",
    district:"Golf Place",
    type:"Villas",
    beds:"4-6BR",
    status:"Off-Plan",
    handover:"Q2 2028",
    price:10500000,
    sizeFrom:5200,
    sizeTo:13000,
    ppsf:2019,
    payment:"80/20",
    construction:20,
    branded:false,
    brand:"—",
    tier:"Ultra-Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/golf-place-ii-at-dubai-hills-estate/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:5200,sqftTo:6800,priceFrom:10500000},{type:"5BR Villa",sqftFrom:7200,sqftTo:9000,priceFrom:14550000},{type:"6BR Villa",sqftFrom:10500,sqftTo:13000,priceFrom:21000000}]
  },
  {
    id:"emaar-24",
    developerId:"emaar",
    name:"Golf Dale",
    community:"Emaar South",
    district:"Emaar South",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q3 2026",
    price:800000,
    sizeFrom:600,
    sizeTo:1800,
    ppsf:1333,
    payment:"80/20",
    construction:80,
    branded:false,
    brand:"—",
    tier:"Mid-Market",
    emaarUrl:"https://properties.emaar.com/en/properties/golf-dale-at-emaar-south/",
    unitBreakdown:[{type:"1BR",sqftFrom:600,sqftTo:800,priceFrom:800000},{type:"2BR",sqftFrom:1100,sqftTo:1350,priceFrom:1466000},{type:"3BR",sqftFrom:1500,sqftTo:1800,priceFrom:2000000}]
  },
  {
    id:"emaar-25",
    developerId:"emaar",
    name:"Golf Gate",
    community:"Emaar South",
    district:"Emaar South",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q4 2026",
    price:850000,
    sizeFrom:620,
    sizeTo:1900,
    ppsf:1371,
    payment:"80/20",
    construction:70,
    branded:false,
    brand:"—",
    tier:"Mid-Market",
    emaarUrl:"https://properties.emaar.com/en/properties/golf-gate-at-emaar-south/",
    unitBreakdown:[{type:"1BR",sqftFrom:620,sqftTo:820,priceFrom:850000},{type:"2BR",sqftFrom:1100,sqftTo:1400,priceFrom:1552000},{type:"3BR",sqftFrom:1550,sqftTo:1900,priceFrom:2124000}]
  },
  {
    id:"emaar-26",
    developerId:"emaar",
    name:"Fairway Villas 2",
    community:"Emaar South",
    district:"Emaar South",
    type:"Villas",
    beds:"3-4BR",
    status:"Off-Plan",
    handover:"Q1 2028",
    price:2800000,
    sizeFrom:2400,
    sizeTo:3800,
    ppsf:1167,
    payment:"80/20",
    construction:20,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/fairway-villas-2-at-emaar-south/",
    unitBreakdown:[{type:"3BR Villa",sqftFrom:2400,sqftTo:2800,priceFrom:2800000},{type:"4BR Villa",sqftFrom:3200,sqftTo:3800,priceFrom:3733000}]
  },
  {
    id:"emaar-27",
    developerId:"emaar",
    name:"Rivana",
    community:"The Valley",
    district:"The Valley",
    type:"Villas",
    beds:"3-5BR",
    status:"Under Construction",
    handover:"Q3 2026",
    price:2200000,
    sizeFrom:2200,
    sizeTo:4500,
    ppsf:1000,
    payment:"80/20",
    construction:80,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/rivana-at-the-valley/",
    unitBreakdown:[{type:"3BR Villa",sqftFrom:2200,sqftTo:2800,priceFrom:2200000},{type:"4BR Villa",sqftFrom:2900,sqftTo:3400,priceFrom:2900000},{type:"5BR Villa",sqftFrom:3800,sqftTo:4500,priceFrom:3800000}]
  },
  {
    id:"emaar-28",
    developerId:"emaar",
    name:"Talia",
    community:"The Valley",
    district:"The Valley",
    type:"Townhouses",
    beds:"3-4BR",
    status:"Off-Plan",
    handover:"Q2 2028",
    price:1800000,
    sizeFrom:1800,
    sizeTo:2800,
    ppsf:1000,
    payment:"80/20",
    construction:15,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/talia-at-the-valley/",
    unitBreakdown:[{type:"3BR TH",sqftFrom:1800,sqftTo:2200,priceFrom:1800000},{type:"4BR TH",sqftFrom:2300,sqftTo:2800,priceFrom:2300000}]
  },
  {
    id:"emaar-29",
    developerId:"emaar",
    name:"Farm Gardens 2",
    community:"The Valley",
    district:"The Valley",
    type:"Villas",
    beds:"4-5BR",
    status:"Off-Plan",
    handover:"Q4 2028",
    price:4200000,
    sizeFrom:3800,
    sizeTo:6000,
    ppsf:1105,
    payment:"80/20",
    construction:10,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/farm-gardens-2-at-the-valley/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:3800,sqftTo:4500,priceFrom:4200000},{type:"5BR Villa",sqftFrom:5000,sqftTo:6000,priceFrom:5526000}]
  },
  {
    id:"emaar-30",
    developerId:"emaar",
    name:"Sunrise Bay",
    community:"Emaar Beachfront",
    district:"Emaar Beachfront",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q1 2026",
    price:2400000,
    sizeFrom:700,
    sizeTo:2100,
    ppsf:3429,
    payment:"80/20",
    construction:95,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/sunrise-bay-at-emaar-beachfront/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:2400000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:4114000},{type:"3BR",sqftFrom:1800,sqftTo:2100,priceFrom:6171000}]
  },
  {
    id:"emaar-31",
    developerId:"emaar",
    name:"Marina Shores",
    community:"Dubai Marina",
    district:"Dubai Marina",
    type:"Apartments",
    beds:"1-4BR",
    status:"Under Construction",
    handover:"Q4 2026",
    price:1900000,
    sizeFrom:700,
    sizeTo:3000,
    ppsf:2714,
    payment:"80/20",
    construction:70,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/marina-shores-at-dubai-marina/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1900000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:3257000},{type:"3BR",sqftFrom:1900,sqftTo:2400,priceFrom:5157000},{type:"4BR",sqftFrom:2500,sqftTo:3000,priceFrom:6785000}]
  },
  {
    id:"emaar-32",
    developerId:"emaar",
    name:"Vida Marina",
    community:"Dubai Marina",
    district:"Dubai Marina",
    type:"Apartments",
    beds:"1-3BR",
    status:"Off-Plan",
    handover:"Q2 2028",
    price:2800000,
    sizeFrom:700,
    sizeTo:2500,
    ppsf:4000,
    payment:"80/20",
    construction:10,
    branded:true,
    brand:"Vida",
    tier:"Luxury Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/vida-marina-at-dubai-marina/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:2800000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:4800000},{type:"3BR",sqftFrom:1900,sqftTo:2500,priceFrom:7600000}]
  },
  {
    id:"emaar-33",
    developerId:"emaar",
    name:"Canal Heights 2",
    community:"Business Bay",
    district:"Business Bay",
    type:"Apartments",
    beds:"1-3BR",
    status:"Off-Plan",
    handover:"Q2 2027",
    price:1800000,
    sizeFrom:700,
    sizeTo:2200,
    ppsf:2571,
    payment:"80/20",
    construction:25,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/canal-heights-2-at-business-bay/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1800000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:3085000},{type:"3BR",sqftFrom:1800,sqftTo:2200,priceFrom:4628000}]
  },
  {
    id:"emaar-34",
    developerId:"emaar",
    name:"Palmiera — The Oasis",
    community:"The Oasis",
    district:"The Oasis",
    type:"Villas",
    beds:"4-6BR",
    status:"Under Construction",
    handover:"Q4 2027",
    price:12000000,
    sizeFrom:6500,
    sizeTo:15000,
    ppsf:1846,
    payment:"80/20",
    construction:35,
    branded:false,
    brand:"—",
    tier:"Ultra-Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/palmiera-at-the-oasis/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:6500,sqftTo:8000,priceFrom:12000000},{type:"5BR Villa",sqftFrom:9000,sqftTo:11000,priceFrom:16615000},{type:"6BR Villa",sqftFrom:12000,sqftTo:15000,priceFrom:22153000}]
  },
  {
    id:"emaar-35",
    developerId:"emaar",
    name:"Mirage — The Oasis",
    community:"The Oasis",
    district:"The Oasis",
    type:"Villas",
    beds:"4-6BR",
    status:"Under Construction",
    handover:"Q1 2028",
    price:13500000,
    sizeFrom:7000,
    sizeTo:16000,
    ppsf:1929,
    payment:"80/20",
    construction:25,
    branded:false,
    brand:"—",
    tier:"Ultra-Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/mirage-at-the-oasis/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:7000,sqftTo:8500,priceFrom:13500000},{type:"5BR Villa",sqftFrom:9500,sqftTo:11500,priceFrom:18321000},{type:"6BR Villa",sqftFrom:13000,sqftTo:16000,priceFrom:25071000}]
  },
  {
    id:"emaar-36",
    developerId:"emaar",
    name:"Mykonos — The Oasis",
    community:"The Oasis",
    district:"The Oasis",
    type:"Villas",
    beds:"4-6BR",
    status:"Off-Plan",
    handover:"Q4 2028",
    price:11500000,
    sizeFrom:6200,
    sizeTo:13000,
    ppsf:1855,
    payment:"80/20",
    construction:10,
    branded:false,
    brand:"—",
    tier:"Ultra-Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/mykonos-at-the-oasis/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:6200,sqftTo:7800,priceFrom:11500000},{type:"5BR Villa",sqftFrom:8500,sqftTo:10000,priceFrom:15766000},{type:"6BR Villa",sqftFrom:11000,sqftTo:13000,priceFrom:20403000}]
  },
  {
    id:"emaar-37",
    developerId:"emaar",
    name:"Elara",
    community:"MBR City",
    district:"MBR City",
    type:"Apartments",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q1 2029",
    price:1650000,
    sizeFrom:700,
    sizeTo:3200,
    ppsf:2357,
    payment:"80/20",
    construction:5,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/elara-at-mbrCity/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1650000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:2828000},{type:"3BR",sqftFrom:1900,sqftTo:2400,priceFrom:4480000},{type:"4BR",sqftFrom:2600,sqftTo:3200,priceFrom:6143000}]
  },
  {
    id:"emaar-38",
    developerId:"emaar",
    name:"Marina Vista",
    community:"Rashid Yachts & Marina",
    district:"Rashid Yachts",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q4 2026",
    price:1800000,
    sizeFrom:700,
    sizeTo:2400,
    ppsf:2571,
    payment:"80/20",
    construction:78,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/marina-vista-at-rashid-yachts-and-marina/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1800000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:3085000},{type:"3BR",sqftFrom:1900,sqftTo:2400,priceFrom:4885000}]
  },
  {
    id:"emaar-39",
    developerId:"emaar",
    name:"Sea View",
    community:"Rashid Yachts & Marina",
    district:"Rashid Yachts",
    type:"Apartments",
    beds:"1-3BR",
    status:"Under Construction",
    handover:"Q1 2027",
    price:1900000,
    sizeFrom:720,
    sizeTo:2500,
    ppsf:2639,
    payment:"80/20",
    construction:60,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/sea-view-at-rashid-yachts-and-marina/",
    unitBreakdown:[{type:"1BR",sqftFrom:720,sqftTo:920,priceFrom:1900000},{type:"2BR",sqftFrom:1250,sqftTo:1550,priceFrom:3298000},{type:"3BR",sqftFrom:2000,sqftTo:2500,priceFrom:5277000}]
  },
  {
    id:"emaar-40",
    developerId:"emaar",
    name:"Park Field",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apartments",
    beds:"1-3BR",
    status:"Off-Plan",
    handover:"Q4 2027",
    price:1500000,
    sizeFrom:680,
    sizeTo:1900,
    ppsf:2206,
    payment:"80/20",
    construction:20,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/park-field-at-dubai-hills-estate/",
    unitBreakdown:[{type:"1BR",sqftFrom:680,sqftTo:880,priceFrom:1500000},{type:"2BR",sqftFrom:1150,sqftTo:1450,priceFrom:2537000},{type:"3BR",sqftFrom:1600,sqftTo:1900,priceFrom:3529000}]
  },
  {
    id:"emaar-41",
    developerId:"emaar",
    name:"Vida Residences Club Point",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apartments",
    beds:"1-3BR",
    status:"Off-Plan",
    handover:"Q2 2029",
    price:2200000,
    sizeFrom:750,
    sizeTo:2200,
    ppsf:2933,
    payment:"80/20",
    construction:5,
    branded:true,
    brand:"Vida",
    tier:"Luxury Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/vida-residences-club-point/",
    unitBreakdown:[{type:"1BR",sqftFrom:750,sqftTo:950,priceFrom:2200000},{type:"2BR",sqftFrom:1300,sqftTo:1600,priceFrom:3812000},{type:"3BR",sqftFrom:1900,sqftTo:2200,priceFrom:5573000}]
  },
  {
    id:"emaar-42",
    developerId:"emaar",
    name:"Address Hillcrest",
    community:"Dubai Hills Estate",
    district:"Dubai Hills Estate",
    type:"Apts & PH",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q4 2030",
    price:3500000,
    sizeFrom:800,
    sizeTo:5500,
    ppsf:4375,
    payment:"80/20",
    construction:0,
    branded:true,
    brand:"Address",
    tier:"Ultra-Lux Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/address-hillcrest/",
    unitBreakdown:[{type:"1BR",sqftFrom:800,sqftTo:1000,priceFrom:3500000},{type:"2BR",sqftFrom:1400,sqftTo:1800,priceFrom:6125000},{type:"3BR",sqftFrom:2200,sqftTo:2800,priceFrom:9625000},{type:"4BR PH",sqftFrom:4000,sqftTo:5500,priceFrom:17500000}]
  },
  {
    id:"emaar-43",
    developerId:"emaar",
    name:"Aurea",
    community:"Rashid Yachts & Marina",
    district:"Rashid Yachts",
    type:"Apartments",
    beds:"1-3BR",
    status:"Off-Plan",
    handover:"Q2 2030",
    price:2310000,
    sizeFrom:700,
    sizeTo:2500,
    ppsf:3300,
    payment:"80/20",
    construction:0,
    branded:false,
    brand:"—",
    tier:"Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/aurea-at-rashid-yachts-and-marina/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:2310000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:3960000},{type:"3BR",sqftFrom:1900,sqftTo:2500,priceFrom:6270000}]
  },
  {
    id:"emaar-44",
    developerId:"emaar",
    name:"Baystar by Vida",
    community:"Rashid Yachts & Marina",
    district:"Rashid Yachts",
    type:"Apartments",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q4 2029",
    price:2100000,
    sizeFrom:700,
    sizeTo:3000,
    ppsf:3000,
    payment:"80/20",
    construction:5,
    branded:true,
    brand:"Vida",
    tier:"Luxury Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/baystar-by-vida-at-rashid-yachts-marina/",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:2100000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:3600000},{type:"3BR",sqftFrom:1900,sqftTo:2400,priceFrom:5700000},{type:"4BR",sqftFrom:2500,sqftTo:3000,priceFrom:7500000}]
  },
  {
    id:"emaar-45",
    developerId:"emaar",
    name:"Marèva 2",
    community:"The Oasis",
    district:"The Oasis",
    type:"Villas",
    beds:"4-6BR",
    status:"Off-Plan",
    handover:"Q1 2030",
    price:13830000,
    sizeFrom:7254,
    sizeTo:12779,
    ppsf:1857,
    payment:"80/20",
    construction:5,
    branded:false,
    brand:"—",
    tier:"Ultra-Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/mareva-2-at-the-oasis/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:7254,sqftTo:8500,priceFrom:13830000},{type:"5BR Villa",sqftFrom:9000,sqftTo:10500,priceFrom:18450000},{type:"6BR Villa",sqftFrom:11000,sqftTo:12779,priceFrom:23730000}]
  },
  {
    id:"emaar-46",
    developerId:"emaar",
    name:"Avarra by Palace",
    community:"Business Bay",
    district:"Business Bay",
    type:"Apts & PH",
    beds:"1-4BR",
    status:"Off-Plan",
    handover:"Q2 2031",
    price:2700000,
    sizeFrom:750,
    sizeTo:3500,
    ppsf:3600,
    payment:"10/80/10",
    construction:0,
    branded:true,
    brand:"Palace",
    tier:"Ultra-Lux Branded",
    emaarUrl:"https://properties.emaar.com/en/properties/avarra-by-palace-at-business-bay/",
    unitBreakdown:[{type:"1BR",sqftFrom:750,sqftTo:950,priceFrom:2700000},{type:"2BR",sqftFrom:1300,sqftTo:1600,priceFrom:4680000},{type:"3BR",sqftFrom:2000,sqftTo:2500,priceFrom:7200000},{type:"4BR PH",sqftFrom:3000,sqftTo:3500,priceFrom:10800000}]
  },
  {
    id:"emaar-47",
    developerId:"emaar",
    name:"Greencrest Heights",
    community:"The Heights CW",
    district:"The Heights CW",
    type:"Townhouses",
    beds:"3-4BR",
    status:"Off-Plan",
    handover:"Q4 2029",
    price:2500000,
    sizeFrom:2200,
    sizeTo:3000,
    ppsf:1136,
    payment:"80/20",
    construction:3,
    branded:false,
    brand:"—",
    tier:"Mid-Premium",
    emaarUrl:"https://properties.emaar.com/en/properties/greencrest-heights-at-the-heights-country-club/",
    unitBreakdown:[{type:"3BR TH",sqftFrom:2200,sqftTo:2600,priceFrom:2500000},{type:"4BR TH",sqftFrom:2700,sqftTo:3000,priceFrom:3068000}]
  },
  {
    id:"emaar-48",
    developerId:"emaar",
    name:"Golf Vedanta Phase 2",
    community:"Golf Place",
    district:"Golf Place",
    type:"Villas",
    beds:"4-6BR",
    status:"Off-Plan",
    handover:"Q2 2030",
    price:15000000,
    sizeFrom:7000,
    sizeTo:16000,
    ppsf:2143,
    payment:"80/20",
    construction:0,
    branded:false,
    brand:"—",
    tier:"Ultra-Luxury",
    emaarUrl:"https://properties.emaar.com/en/properties/",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:7000,sqftTo:9000,priceFrom:15000000},{type:"5BR Villa",sqftFrom:10000,sqftTo:12000,priceFrom:21428000},{type:"6BR Villa",sqftFrom:13000,sqftTo:16000,priceFrom:30000000}]
  },
];

/* ─── ENHANCED FINANCIALS (from Excel PBI_Financials) ─── */
export const emaarFinancials = [
  { year:"2020", revenue:14.9, grossProfit:4.8, ebitda:6.2, netProfit:2.7, netProfitAttr:2.1, propertySales:14, backlog:28, recurringRev:5.3, intlSales:0.6, mallRev:3.2, hotelRev:2.1, mallOccupancy:93, dubaiMallFootfall:65, dividend:0.15, eps:0.24, unitsDelivered:59000, newLaunches:15, revenueUSD:4.1, netProfitUSD:0.6, gm:32.2, em:41.6, nm:14.1 },
  { year:"2021", revenue:27.9, grossProfit:11.6, ebitda:8.5, netProfit:6.6, netProfitAttr:5.3, propertySales:23.9, backlog:32, recurringRev:5.8, intlSales:0.8, mallRev:3.5, hotelRev:2.3, mallOccupancy:95, dubaiMallFootfall:80, dividend:0.25, eps:0.60, unitsDelivered:62000, newLaunches:20, revenueUSD:7.6, netProfitUSD:1.4, gm:41.6, em:30.5, nm:19.0 },
  { year:"2022", revenue:24.9, grossProfit:12.6, ebitda:9.8, netProfit:8.1, netProfitAttr:6.8, propertySales:30.7, backlog:41.5, recurringRev:7.5, intlSales:1.2, mallRev:4.2, hotelRev:3.3, mallOccupancy:96, dubaiMallFootfall:88, dividend:0.35, eps:0.77, unitsDelivered:65000, newLaunches:22, revenueUSD:6.8, netProfitUSD:1.9, gm:50.6, em:39.4, nm:27.3 },
  { year:"2023", revenue:26.7, grossProfit:16.9, ebitda:16.0, netProfit:15.1, netProfitAttr:11.6, propertySales:40.3, backlog:71.8, recurringRev:8.6, intlSales:2.9, mallRev:5.8, hotelRev:2.8, mallOccupancy:97, dubaiMallFootfall:105, dividend:0.50, eps:1.32, unitsDelivered:70000, newLaunches:27, revenueUSD:7.3, netProfitUSD:3.2, gm:63.3, em:59.9, nm:43.4 },
  { year:"2024", revenue:35.5, grossProfit:20.4, ebitda:19.3, netProfit:18.9, netProfitAttr:13.5, propertySales:69.5, backlog:111.5, recurringRev:9.3, intlSales:4.1, mallRev:5.6, hotelRev:3.7, mallOccupancy:98.5, dubaiMallFootfall:111, dividend:1.00, eps:1.53, unitsDelivered:75000, newLaunches:62, revenueUSD:9.7, netProfitUSD:3.7, gm:57.5, em:54.4, nm:38.0 },
  { year:"2025", revenue:49.6, grossProfit:28.5, ebitda:25.6,
    netProfitBeforeTax:25.7,  // AED 25.7B = net profit before minority interests (Emaar press release language)
    netProfit:25.7,           // kept for backward compatibility — equals netProfitBeforeTax
    netProfitAttr:17.6,       // AED 17.6B = attributable to Emaar shareholders (after minority interest)
    propertySales:80.4, backlog:155, recurringRev:10.5, intlSales:9.3,
    mallRev:6.3, hotelRev:4.2, mallOccupancy:98, dubaiMallFootfall:118,
    dividend:1.00, eps:2.00,
    unitsDeliveredCumulative:125600, // CUMULATIVE since 2002 — NOT annual. FY2025 annual deliveries ~7,000–8,000 units
    unitsDelivered:125600,           // kept for backward compatibility — cumulative since inception
    newLaunches:48,
    revenueUSD:13.5, netProfitUSD:4.8, gm:57.5, em:51.6, nm:35.5, landBank:618,
    creditRatingSP:"BBB+",           // S&P upgraded June 2025 (from BBB)
    creditRatingMoodys:"Baa1",       // Moody's upgraded June 2025 (from Baa2)
    creditRatingFitch:"BBB+",        // Fitch
    creditRatingNote:"S&P and Moody's both upgraded Emaar in June 2025 — strongest ever ratings",
  },
];

/* ─── COMMUNITIES (from Excel PBI_Communities) ─── */
export const emaarCommunities = [
  { district:"DHE", name:"Dubai Hills Estate", acres:2700, avgPpsf:2400, avgYield:6.1, projects:16, buyer:"Families, professionals", strengths:"Golf, schools, mall, parks" },
  { district:"DCH", name:"Dubai Creek Harbour", acres:2500, avgPpsf:2500, avgYield:5.7, projects:11, buyer:"Investors, expats", strengths:"Dubai Square; Creek Tower; waterfront" },
  { district:"EBF", name:"Emaar Beachfront", acres:250, avgPpsf:4250, avgYield:5.8, projects:5, buyer:"Luxury expats, UHNW", strengths:"Beach access; Address/Bristol brands" },
  { district:"ES", name:"Emaar South", acres:7000, avgPpsf:1400, avgYield:6.2, projects:2, buyer:"Value investors", strengths:"Expo legacy; golf; affordable entry" },
  { district:"EL", name:"Expo Living", acres:3000, avgPpsf:null, avgYield:null, projects:1, buyer:"Value seekers", strengths:"Emerging area" },
  { district:"TV", name:"The Valley", acres:4000, avgPpsf:1200, avgYield:6.0, projects:2, buyer:"End-user families", strengths:"Townhouses & villas; community" },
  { district:"GPC", name:"Grand Polo Club", acres:3500, avgPpsf:1770, avgYield:5.5, projects:6, buyer:"UHNW, polo", strengths:"First polo-themed community" },
  { district:"RYM", name:"Rashid Yachts & Marina", acres:1000, avgPpsf:3000, avgYield:5.0, projects:2, buyer:"Maritime lifestyle", strengths:"Yacht marina; Vida" },
  { district:"TO", name:"The Oasis", acres:2500, avgPpsf:1921, avgYield:3.5, projects:1, buyer:"UHNW families", strengths:"Ultra-luxury villas" },
  { district:"BB", name:"Business Bay", acres:null, avgPpsf:3422, avgYield:6.7, projects:1, buyer:"Executives", strengths:"Central; Palace branded" },
  { district:"TH", name:"The Heights CW", acres:null, avgPpsf:1136, avgYield:5.5, projects:1, buyer:"Mid-market families", strengths:"Townhouse community" },
];

/* ─── ENHANCED YIELDS (from Excel PBI_RentalYields) ─── */
export const emaarYields = [
  { community:"Dubai Hills Estate", unit:"1BR Apt", rent:100000, price:1529388, gross:6.07, net:5.0, demand:"Very High", tenant:"Professionals, couples", visa:"Yes (≥2M)" },
  { community:"Dubai Hills Estate", unit:"2BR Apt", rent:145000, price:2200000, gross:5.4, net:4.5, demand:"Very High", tenant:"Families, professionals", visa:"Yes (≥2M)" },
  { community:"Dubai Hills Estate", unit:"3BR Apt", rent:195000, price:3500000, gross:4.8, net:3.9, demand:"High", tenant:"HNW families", visa:"Yes (≥2M)" },
  { community:"Dubai Creek Harbour", unit:"1BR Apt", rent:95000, price:1750000, gross:5.7, net:4.7, demand:"High", tenant:"Young professionals", visa:"Yes (≥2M)" },
  { community:"Dubai Creek Harbour", unit:"2BR Apt", rent:140000, price:2500000, gross:5.5, net:4.5, demand:"High", tenant:"Expat families", visa:"Yes (≥2M)" },
  { community:"Dubai Creek Harbour", unit:"3BR Apt", rent:190000, price:3500000, gross:5.2, net:4.2, demand:"Moderate-High", tenant:"HNW tenants", visa:"Yes (≥2M)" },
  { community:"Emaar Beachfront", unit:"1BR Apt", rent:140000, price:3200000, gross:5.8, net:4.5, demand:"Very High", tenant:"Luxury expats", visa:"Yes (≥2M)" },
  { community:"Emaar Beachfront", unit:"2BR Apt", rent:210000, price:5000000, gross:5.5, net:4.2, demand:"High", tenant:"UHNW tenants", visa:"Yes (≥2M)" },
  { community:"Emaar South", unit:"1BR Apt", rent:55000, price:900000, gross:6.5, net:5.5, demand:"Growing", tenant:"Airport staff, young prof.", visa:"Below 2M" },
  { community:"Emaar South", unit:"2BR Apt", rent:78000, price:1400000, gross:6.2, net:5.2, demand:"Growing", tenant:"Families, value seekers", visa:"Yes (≥2M)" },
  { community:"The Valley", unit:"3BR TH", rent:110000, price:1600000, gross:6.0, net:5.2, demand:"High", tenant:"Family end-users", visa:"Yes (≥2M)" },
  { community:"The Valley", unit:"4BR Villa", rent:180000, price:3000000, gross:5.5, net:4.8, demand:"High", tenant:"Large families", visa:"Yes (≥2M)" },
  { community:"Rashid Yachts & Marina", unit:"1BR Apt", rent:95000, price:2100000, gross:5.0, net:4.0, demand:"Moderate-High", tenant:"Maritime lifestyle", visa:"Yes (≥2M)" },
  { community:"Downtown Dubai", unit:"1BR Apt", rent:105000, price:2500000, gross:5.5, net:4.3, demand:"Very High", tenant:"Tourists, executives", visa:"Yes (≥2M)" },
  { community:"Downtown Dubai", unit:"2BR Apt", rent:160000, price:4000000, gross:5.0, net:3.8, demand:"Very High", tenant:"UHNW, corp. housing", visa:"Yes (≥2M)" },
  { community:"Business Bay", unit:"1BR Apt", rent:105000, price:1500000, gross:6.7, net:5.5, demand:"Very High", tenant:"Professionals, executives", visa:"Yes (≥2M)" },
  { community:"Grand Polo Club", unit:"3BR TH", rent:180000, price:3700000, gross:5.5, net:4.5, demand:"High", tenant:"HNW families, expats", visa:"Yes (≥2M)" },
];

/* ─── PROJECT ROI DATA BY COMMUNITY (Research-backed: DLD, Bayut, REIDIN, Knight Frank, JLL, Engel & Völkers, Chestertons, BetterHomes Q4 2025) ─── */
export const communityROI = {
  "Dubai Hills Estate": {
    grossYield: { apt1: 6.07, apt2: 5.4, apt3: 4.8, th: 4.8, villa: 4.5 },
    netYield: { apt1: 5.0, apt2: 4.5, apt3: 3.9, th: 4.0, villa: 3.8 },
    estRent: { apt1: 100000, apt2: 145000, apt3: 195000, th: 160000, villa: 280000 },
    serviceCharge: 18, // AED per sqft/year
    appreciation5yr: 38, // % over 5 years
    appreciationYoY: 12, // annual %
    capitalGrowthDriver: "DHE Mall, schools, limited villa supply, golf course premium",
    bankRate: 4.5, // UAE term deposit %
    goldenVisa: true,
    goldenVisaNote: "Eligible (≥AED 2M property value)",
    riskLevel: "Low",
    occupancy: 94, // %
    avgDaysToLease: 12,
    shortTermPremium: 35, // % uplift vs annual
    source: "Engel & Völkers 2026, Bayut H2 2025, BetterHomes Q3 2025, DLD Ejari"
  },
  "Dubai Creek Harbour": {
    grossYield: { apt1: 5.7, apt2: 5.5, apt3: 5.2, th: 5.0, villa: null },
    netYield: { apt1: 4.7, apt2: 4.5, apt3: 4.2, th: 4.1, villa: null },
    estRent: { apt1: 95000, apt2: 140000, apt3: 190000, th: 155000, villa: null },
    serviceCharge: 16,
    appreciation5yr: 42,
    appreciationYoY: 15,
    capitalGrowthDriver: "Metro Blue Line 2029, Dubai Square Mall, Creek Tower revival, waterfront premium",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "Eligible (≥AED 2M property value)",
    riskLevel: "Low-Medium",
    occupancy: 92,
    avgDaysToLease: 14,
    shortTermPremium: 30,
    source: "BetterHomes DCH Guide 2025, Valorisimo 2025, West Gate Dubai, DLD"
  },
  "Emaar Beachfront": {
    grossYield: { apt1: 5.8, apt2: 5.5, apt3: 5.2, apt4: 6.5, villa: null },
    netYield: { apt1: 4.5, apt2: 4.2, apt3: 4.0, apt4: 5.2, villa: null },
    estRent: { apt1: 140000, apt2: 210000, apt3: 350000, apt4: 500000, villa: null },
    serviceCharge: 22,
    appreciation5yr: 45,
    appreciationYoY: 17,
    capitalGrowthDriver: "Limited island supply, Dubai Harbour, beachfront scarcity, branded residences, Airbnb premium",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "All units qualify (min AED 3M+)",
    riskLevel: "Low",
    occupancy: 96,
    avgDaysToLease: 8,
    shortTermPremium: 55,
    source: "BetterHomes EBF Guide 2025, Alcenza Q1 2025, Driven Properties, DLD"
  },
  "Emaar South": {
    grossYield: { apt1: 6.5, apt2: 6.2, apt3: 6.0, th: 5.5, villa: 5.0 },
    netYield: { apt1: 5.5, apt2: 5.2, apt3: 5.0, th: 4.5, villa: 4.2 },
    estRent: { apt1: 55000, apt2: 78000, apt3: 105000, th: 110000, villa: 150000 },
    serviceCharge: 12,
    appreciation5yr: 40,
    appreciationYoY: 19,
    capitalGrowthDriver: "Al Maktoum Airport AED 128B expansion, Expo City legacy, upcoming metro, golf course",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "Eligible for select units (≥AED 2M)",
    riskLevel: "Medium",
    occupancy: 88,
    avgDaysToLease: 18,
    shortTermPremium: 20,
    source: "Chestertons 2025, Khaleej Times Dec 2025, West Gate EXPO analysis, DLD"
  },
  "Expo Living": {
    grossYield: { apt1: 6.5, apt2: 6.2, apt3: 6.0, th: null, villa: null },
    netYield: { apt1: 5.5, apt2: 5.2, apt3: 5.0, th: null, villa: null },
    estRent: { apt1: 58000, apt2: 82000, apt3: 110000, th: null, villa: null },
    serviceCharge: 12,
    appreciation5yr: 40,
    appreciationYoY: 18,
    capitalGrowthDriver: "Expo 2020 legacy site, Dubai South growth corridor, metro expansion",
    bankRate: 4.5,
    goldenVisa: false,
    goldenVisaNote: "Below AED 2M threshold for most units",
    riskLevel: "Medium",
    occupancy: 85,
    avgDaysToLease: 21,
    shortTermPremium: 15,
    source: "Dubai South market reports, Bayut 2025, West Gate Dubai"
  },
  "The Valley": {
    grossYield: { apt1: null, apt2: null, apt3: null, th: 6.0, villa: 5.5 },
    netYield: { apt1: null, apt2: null, apt3: null, th: 5.2, villa: 4.8 },
    estRent: { apt1: null, apt2: null, apt3: null, th: 110000, villa: 180000 },
    serviceCharge: 10,
    appreciation5yr: 50,
    appreciationYoY: 20,
    capitalGrowthDriver: "PPSF doubled since 2020, family suburb demand, Al Ain Road corridor, limited villa supply",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "Eligible for villas (≥AED 2M)",
    riskLevel: "Low-Medium",
    occupancy: 93,
    avgDaysToLease: 15,
    shortTermPremium: 10,
    source: "DataDXB 2025, Provident RE, askdubaiproperty.com, DLD transaction records"
  },
  "Grand Polo Club": {
    grossYield: { apt1: null, apt2: null, apt3: null, th: 5.5, villa: 5.0 },
    netYield: { apt1: null, apt2: null, apt3: null, th: 4.5, villa: 4.2 },
    estRent: { apt1: null, apt2: null, apt3: null, th: 180000, villa: 320000 },
    serviceCharge: 14,
    appreciation5yr: 45,
    appreciationYoY: 22,
    capitalGrowthDriver: "First polo-themed community globally, Emaar brand premium, 80/20 payment leverage, 6,661 units in AED 41B project",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "All units qualify (min AED 3.7M+)",
    riskLevel: "Medium",
    occupancy: null,
    avgDaysToLease: null,
    shortTermPremium: 15,
    source: "Emaar launch data Apr 2025, Gulf News, Arabian Business, estimated yields"
  },
  "Rashid Yachts & Marina": {
    grossYield: { apt1: 5.0, apt2: 4.8, apt3: 4.5, th: null, villa: null },
    netYield: { apt1: 4.0, apt2: 3.8, apt3: 3.5, th: null, villa: null },
    estRent: { apt1: 95000, apt2: 145000, apt3: 200000, th: null, villa: null },
    serviceCharge: 18,
    appreciation5yr: 30,
    appreciationYoY: 12,
    capitalGrowthDriver: "Historic port regeneration, marina lifestyle, Vida branding, limited waterfront",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "Eligible (all units ≥AED 2.1M)",
    riskLevel: "Medium",
    occupancy: 88,
    avgDaysToLease: 18,
    shortTermPremium: 25,
    source: "Emaar project data, Dubai South district analysis, estimated yields"
  },
  "The Oasis": {
    grossYield: { apt1: null, apt2: null, apt3: null, th: null, villa: 3.5 },
    netYield: { apt1: null, apt2: null, apt3: null, th: null, villa: 2.8 },
    estRent: { apt1: null, apt2: null, apt3: null, th: null, villa: 550000 },
    serviceCharge: 20,
    appreciation5yr: 50,
    appreciationYoY: 21,
    capitalGrowthDriver: "Ultra-luxury villa scarcity, AED 73B project, 1,213 villas sold avg AED 17.6M, +21% YoY per DLD",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "All units qualify (min AED 13M+)",
    riskLevel: "Low",
    occupancy: 95,
    avgDaysToLease: 10,
    shortTermPremium: 40,
    source: "DLD transaction data 2025, AGBI, Gulf News, Emaar press releases"
  },
  "Business Bay": {
    grossYield: { apt1: 6.7, apt2: 6.0, apt3: 5.5, th: null, villa: null },
    netYield: { apt1: 5.5, apt2: 5.0, apt3: 4.5, th: null, villa: null },
    estRent: { apt1: 105000, apt2: 160000, apt3: 220000, th: null, villa: null },
    serviceCharge: 20,
    appreciation5yr: 32,
    appreciationYoY: 11,
    capitalGrowthDriver: "Central business district, canal views, DIFC proximity, Palace branding, metro access",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "All units qualify (≥AED 2.7M)",
    riskLevel: "Low",
    occupancy: 94,
    avgDaysToLease: 10,
    shortTermPremium: 40,
    source: "Veersant 2025, REDHORIZON calculator, Bayut H2 2025, DLD"
  },
  "The Heights CW": {
    grossYield: { apt1: null, apt2: null, apt3: null, th: 5.5, villa: null },
    netYield: { apt1: null, apt2: null, apt3: null, th: 4.5, villa: null },
    estRent: { apt1: null, apt2: null, apt3: null, th: 125000, villa: null },
    serviceCharge: 12,
    appreciation5yr: 35,
    appreciationYoY: 15,
    capitalGrowthDriver: "Emerging wellness community, competitive PPSF, family-oriented design",
    bankRate: 4.5,
    goldenVisa: true,
    goldenVisaNote: "Eligible (≥AED 2.5M)",
    riskLevel: "Medium",
    occupancy: null,
    avgDaysToLease: null,
    shortTermPremium: 10,
    source: "Emaar launch data, market estimates based on comparable communities"
  }
};

/* ─── COMMUNITY MAP COORDINATES (Google Maps verified) ─── */
export const communityCoords = [
  { district: "DHE", name: "Dubai Hills Estate", lat: 25.1267, lng: 55.2367, color: "#10B981", projects: 16, type: "Master Community" },
  { district: "DCH", name: "Dubai Creek Harbour", lat: 25.2048, lng: 55.3480, color: "#3B82F6", projects: 11, type: "Waterfront" },
  { district: "EBF", name: "Emaar Beachfront", lat: 25.0785, lng: 55.1330, color: "#D4A843", projects: 5, type: "Beachfront Island" },
  { district: "ES", name: "Emaar South", lat: 24.9650, lng: 55.1520, color: "#8B5CF6", projects: 2, type: "Golf & Airport" },
  { district: "EL", name: "Expo Living", lat: 24.9700, lng: 55.1380, color: "#EC4899", projects: 1, type: "Expo Legacy" },
  { district: "TV", name: "The Valley", lat: 25.0250, lng: 55.3150, color: "#F59E0B", projects: 2, type: "Suburban Villas" },
  { district: "GPC", name: "Grand Polo Club", lat: 24.9800, lng: 55.1750, color: "#EF4444", projects: 6, type: "Polo Lifestyle" },
  { district: "RYM", name: "Rashid Yachts & Marina", lat: 25.2650, lng: 55.2850, color: "#06B6D4", projects: 2, type: "Marina Heritage" },
  { district: "TO", name: "The Oasis", lat: 25.0800, lng: 55.2800, color: "#14B8A6", projects: 1, type: "Ultra-Luxury Villas" },
  { district: "BB", name: "Business Bay", lat: 25.1850, lng: 55.2650, color: "#F97316", projects: 1, type: "CBD" },
  { district: "TH", name: "The Heights CW", lat: 25.0600, lng: 55.2000, color: "#A78BFA", projects: 1, type: "Wellness Community" },
];
export const dubaiLandmarks = [
  { name: "Burj Khalifa", lat: 25.1972, lng: 55.2744, icon: "▲" },
  { name: "Palm Jumeirah", lat: 25.1124, lng: 55.1390, icon: "🌴" },
  { name: "DXB Airport", lat: 25.2532, lng: 55.3657, icon: "✈" },
  { name: "Al Maktoum Airport", lat: 24.8967, lng: 55.1614, icon: "✈" },
  { name: "Dubai Marina", lat: 25.0800, lng: 55.1400, icon: "⚓" },
  { name: "Dubai Mall", lat: 25.1985, lng: 55.2796, icon: "🏬" },
];

/* ─── TOP 10 DEVELOPERS (from Excel PBI_Developers) ─── */
export const topDevelopers = [
  // NOTE: sales = FY2025 Group Total Sales (AED Billion). DLD-registered Dubai-only transactions
  // are a different metric and will show lower numbers in DLD data tools.
  { rank:1, name:"Emaar Properties",  sales:80.4, salesUSD:21.9, units:13149, delivered:123500, underConst:51032, segment:"Full Spectrum",            confidence:"VERIFIED", share:11.77, color:"#D4A843", note:"AED 80.4B = Group total incl. international. Dubai DLD registrations: AED 65.8B" },
  { rank:2, name:"Aldar Properties",  sales:40.6, salesUSD:11.1, units:1732,  delivered:1200,   underConst:18000, segment:"Abu Dhabi + Dubai",         confidence:"VERIFIED", share:5.95,  color:"#06B6D4", note:"AED 40.6B group · AED 35.5B UAE · ADX listed · #1 Abu Dhabi" },
  { rank:3, name:"DAMAC Properties",  sales:36.0, salesUSD:9.8,  units:15393, delivered:2113,   underConst:54000, segment:"Mid-Premium → Ultra-Lux",   confidence:"VERIFIED", share:5.27,  color:"#00BFA5", note:"#1 Private Developer UAE & ME · Guinness World Record" },
  { rank:4, name:"Sobha Realty",      sales:30.0, salesUSD:8.17, units:9698,  delivered:2260,   underConst:26933, segment:"Premium → Ultra-Lux",       confidence:"VERIFIED", share:4.39,  color:"#8B5CF6", note:"+30% YoY · AED 8B UAQ sales · 100% backward integration" },
  { rank:5, name:"Binghatti",         sales:26.0, salesUSD:7.1,  units:17061, delivered:12500,  underConst:38000, segment:"Affordable → Ultra-Luxury", confidence:"VERIFIED", share:3.81,  color:"#3B82F6", note:"#1 Dubai by units sold (17,000) · Private company · Sukuk listed Nasdaq Dubai" },
  { rank:6, name:"Nakheel",           sales:24.6, salesUSD:6.7,  units:4160,  delivered:1522,   underConst:15000, segment:"Waterfront",                 confidence:"VERIFIED", share:3.60,  color:"#10B981", note:"Dubai Holding · Palm Jebel Ali · Dubai Islands" },
  { rank:7, name:"Meraas",            sales:20.9, salesUSD:5.7,  units:2385,  delivered:1913,   underConst:12000, segment:"Premium Lifestyle",           confidence:"VERIFIED", share:3.06,  color:"#F59E0B", note:"Dubai Holding · Bluewaters · Bvlgari · City Walk" },
  { rank:8, name:"Danube Properties", sales:7.0,  salesUSD:1.9,  units:4089,  delivered:1757,   underConst:22000, segment:"Affordable",                 confidence:"VERIFIED", share:1.03,  color:"#7E95AD", note:"Highest ROI focus · AED 7B FY2025" },
  { rank:9, name:"Omniyat",           sales:11.0, salesUSD:3.0,  units:1656,  delivered:800,    underConst:4500,  segment:"Ultra-Luxury",               confidence:"VERIFIED", share:1.61,  color:"#FF7043", note:"T2 developer · Ultra-luxury specialist" },
  { rank:10, name:"H&H Development",  sales:8.1,  salesUSD:2.2,  units:1200,  delivered:600,    underConst:8000,  segment:"Mid-Premium",                confidence:"VERIFIED", share:1.19,  color:"#AB47BC", note:"Premium mid-market" },
];

/* ─── RISK MATRIX (from Excel PBI_Risks) ─── */
export const emaarRisks = [
  { factor:"Premium Pricing Risk", level:5, likelihood:5, impact:5, score:125, mitigation:"Off-plan payment plans (80/20); branded residences justify premium", assessment:"HIGH", color:"#EF4444" },
  { factor:"Market Cycle Correction", level:4, likelihood:5, impact:5, score:100, mitigation:"Diversified revenue; 35% recurring from malls/hotels", assessment:"ELEVATED", color:"#F59E0B" },
  { factor:"Supply Competition", level:4, likelihood:5, impact:3, score:60, mitigation:"Brand premium 20-40%; 79K track record; master communities", assessment:"ELEVATED", color:"#F59E0B" },
  { factor:"Geographic Concentration", level:3, likelihood:3, impact:5, score:45, mitigation:"Expanding to Saudi, Egypt, India; +124% intl sales YoY", assessment:"MODERATE", color:"#D4A843" },
  { factor:"Interest Rate Sensitivity", level:2, likelihood:2, impact:2, score:8, mitigation:"87% cash buyers; no floating debt exposure", assessment:"LOW", color:"#00BFA5" },
  { factor:"Execution / Delivery", level:1, likelihood:1, impact:2, score:2, mitigation:"23-year record; 79,000+ units completed on schedule", assessment:"VERY LOW", color:"#10B981" },
  { factor:"Regulatory Changes", level:1, likelihood:1, impact:2, score:2, mitigation:"DLD/RERA framework; transparent governance", assessment:"VERY LOW", color:"#10B981" },
  { factor:"Currency (AED Peg)", level:1, likelihood:1, impact:2, score:2, mitigation:"USD peg since 1997; zero FX risk for USD investors", assessment:"VERY LOW", color:"#10B981" },
  { factor:"Liquidity / Exit Risk", level:1, likelihood:1, impact:1, score:1, mitigation:"DFM-listed; AED 150B+ market cap; deep secondary market", assessment:"VERY LOW", color:"#10B981" },
];

/* ─── DUBAI MARKET 2025 (from Excel PBI_DubaiMarket) ─── */
export const dubaiMarket = [
  { metric:"Total Sales Value", val2024:"AED 522.4B", val2025:"AED 682.5B", yoy:"+30.7%", category:"Sales" },
  { metric:"Sales Transactions", val2024:"180,860", val2025:"214,912", yoy:"+18.8%", category:"Volume" },
  { metric:"Total Txn Value", val2024:"AED 760.7B", val2025:"AED 919B", yoy:"+20.8%", category:"Sales" },
  { metric:"All Transactions", val2024:"226,117", val2025:"275,442", yoy:"+21.8%", category:"Volume" },
  { metric:"Q4 Sales", val2024:"AED 147.8B", val2025:"AED 187.5B", yoy:"+26.9%", category:"Sales" },
  { metric:"Avg Price/sqft", val2024:"AED 1,484", val2025:"AED 1,755", yoy:"+18.3%", category:"Pricing" },
  { metric:"Off-Plan Share", val2024:"55%", val2025:"62.6%", yoy:"Growing", category:"Structure" },
  { metric:"Cash Buyers", val2024:"85%", val2025:"87%", yoy:"Dominant", category:"Structure" },
  { metric:"New Investors H1", val2024:"48,600", val2025:"59,075", yoy:"+22%", category:"Demand" },
];

export const dubaiSalesHistory = [
  { year:"2020", sales:120 }, { year:"2021", sales:230 }, { year:"2022", sales:300 },
  { year:"2023", sales:410 }, { year:"2024", sales:522.4 }, { year:"2025", sales:682.5 },
];

/* ─── ROI PHASES (from Excel PBI_ROIPhases) ─── */
export const roiPhases = [
  { phase:"Pre-Launch", timeline:"At Booking", low:8, high:12, avg:10, risk:"Low" },
  { phase:"Construction", timeline:"2-3 Years", low:12, high:20, avg:16, risk:"Low-Medium" },
  { phase:"Handover", timeline:"Completion", low:15, high:25, avg:20, risk:"Medium" },
  { phase:"Rental Y1+", timeline:"Post-Handover", low:4.5, high:8, avg:6.3, risk:"Low" },
  { phase:"5-Year Hold", timeline:"2026-2031", low:30, high:50, avg:40, risk:"Medium" },
];

/* ─── SEGMENTS ─── */
export const emaarSegments = [
  { name:"UAE Property Dev", revenue:36.4, growth:"44%", color:"#D4A843" },
  { name:"Malls & Retail", revenue:6.3, growth:"13%", color:"#00BFA5" },
  { name:"Hospitality", revenue:4.2, growth:"12%", color:"#06B6D4" },
  { name:"International", revenue:2.6, growth:"124%", color:"#10B981" },
];

/* ─── RADAR DATA ─── */
export const radarData = [
  { metric:"Revenue Growth", value:85 },
  { metric:"Profit Margin", value:72 },
  { metric:"Market Share", value:90 },
  { metric:"Brand Strength", value:95 },
  { metric:"Diversification", value:68 },
  { metric:"Delivery Record", value:92 },
];

/* ─── MEGA PROJECTS ─── */
export const megaProjects = [
  { name:"Dubai Square", community:"Dubai Creek Harbour", value:"AED 180B+", scale:"2.6M sqm retail/hospitality", type:"Retail + Mixed-Use", timeline:"Phased 2028+", feature:"World's first drive-through mall", status:"Under Construction", developer:"Emaar Properties", announced:"Dec 2025",
    desc:"Dubai Square is Emaar's AED 180B+ mega retail and mixed-use development in Dubai Creek Harbour, spanning 2.6 million square metres. Announced by Mohamed Alabbar on social media in November 2025 and officially unveiled December 2025, construction is already underway with a 3-year completion target. It will feature the world's first drive-through mall concept, AI-powered navigation, EV charging infrastructure, and a luxury retail district rivalling Dubai Mall.",
    keyFacts:["AED 180B+ total investment (anchor of DCH district)","2.6 million sqm retail, hospitality & commercial","World's first drive-through mall concept","AI-powered navigation & smart shopping","EV charging infrastructure throughout","Connected directly to Dubai Creek Tower","3-year phased construction target","Pedestrian-friendly streets & integrated transport"],
    investorImpact:"Transforms Creek Harbour into a competing retail hub to Downtown Dubai. DCH avg PPSF currently AED 2,470 across 4,280 sales vs Downtown's AED 3,000 — a 17% gap that is expected to narrow as Dubai Square opens. Early DCH investors could see 8-12% annual capital appreciation.",
    completion:"Construction started late 2025. Phase 1 targeted for 2028. Full completion expected 2030-2032.",
    benchmark:"Hudson Yards (NYC): $25B over 1.2M sqm — Dubai Square is 2x the scale at 2.6M sqm. Battersea Power Station (London): £9B over 42 acres — Dubai Square spans 10x the area.",
    priceImpact:"DCH prices up 3% YoY with avg AED 2,470/sqft. Downtown Dubai (mature comparator) at AED 3,000/sqft — 17% premium gap expected to narrow as Dubai Square delivers.",
    milestones:["Nov 2025 – Alabbar announces on Instagram","Dec 2025 – Official Emaar press release","Q1 2026 – Construction underway","2028 – Phase 1 targeted opening","2030-2032 – Full completion"],
    sources:"Emaar Press Release (Dec 2025), Arabian Business, Construction Week Online, AGBI"
  },
  { name:"Dubai Mall Expansion", community:"Downtown Dubai", value:"AED 1.5B", scale:"279 new outlets across 12.1M sqft", type:"Retail Expansion", timeline:"2025-2027", feature:"World's most visited (111M/yr)", status:"Partially Open", developer:"Emaar Malls", announced:"Jun 2024",
    desc:"Emaar is investing AED 1.5 billion to expand the Dubai Mall with 279 new outlets including 198 retail stores and 81 F&B concepts. 'The District' section opened in March 2025 with 65 shops and restaurants near the Ice Rink. The mall recorded 111 million visitors in 2024, up 6% year-over-year, with 99% occupancy across 12.1 million square feet. A new exhibition centre began accepting bookings in early 2026.",
    keyFacts:["AED 1.5B expansion investment","279 new outlets (198 retail + 81 F&B)","'The District' opened March 2025 (65 shops)","New exhibition centre accepting bookings early 2026","111 million visitors in 2024 (+6% YoY)","99% occupancy across 12.1M sqft","World's most visited retail destination globally","Competing with Mall of the Emirates' AED 5B makeover"],
    investorImpact:"Reinforces Downtown Dubai as the global retail capital. Drives foot traffic and rental demand for surrounding residential. For context: Mall of the Emirates announced AED 5B makeover with 100 new stores including Primark and Skims — Dubai Mall's expansion is defensive and offensive.",
    completion:"The District section opened March 2025. Exhibition centre operational early 2026. Remaining phases through 2027.",
    benchmark:"Mall of America (USA): 40M visitors/yr — Dubai Mall does 111M (2.8x). Westfield London: 27M sqft — Dubai Mall at 12.1M sqft but higher revenue per sqft due to tourism.",
    priceImpact:"Downtown Dubai avg AED 3,000/sqft with 4,033 sales in past year. 99% mall occupancy = sustained residential demand in the district.",
    milestones:["Jun 2024 – Expansion announced","Mar 2025 – The District opens (65 outlets)","Early 2026 – Exhibition centre operational","2027 – Full expansion complete"],
    sources:"Emaar IR Reports, Time Out Dubai, Emaar Press Release (Sep 2025)"
  },
  { name:"Dubai Creek Tower", community:"Dubai Creek Harbour", value:"AED 3.67B+", scale:"Iconic observation tower", type:"Mixed-Use Tower", timeline:"Tender Q1 2026", feature:"Calatrava-designed landmark", status:"Tender Phase", developer:"Emaar Properties", announced:"Jan 2026 Revival",
    desc:"Dubai Creek Tower is Emaar's iconic supertall tower designed by Santiago Calatrava, inspired by traditional minaret architecture. Originally announced in 2016 with foundations completed by 2018, work was halted during COVID. In January 2026, Mohamed Alabbar confirmed the project is back on track at the Dubai International Project Management Forum. The 2026 redesign shifts from height competition to architectural beauty — a 'modern minaret' rather than a record-breaker.",
    keyFacts:["AED 3.67B+ estimated investment","Santiago Calatrava iconic design","Redesigned as 'modern minaret' — beauty over height","Foundation completed 2016-2018 (already built)","Construction tender issued Q1 2026","Observation decks, sky gardens, hospitality","Centrepiece of Dubai Creek Harbour district","Integrated with Dubai Square mega retail"],
    investorImpact:"Revival signals peak confidence in Creek Harbour's future. Historical comparison: Burj Khalifa drove Downtown Dubai prices up 300%+ from launch to maturity. Analysts project 8-12% annual capital appreciation and 6-8% gross rental yields for DCH as infrastructure matures.",
    completion:"Foundations built 2016-2018. Project paused 2020 (COVID). Revived January 2026. Tender Q1 2026. Construction timeline TBD pending contractor selection.",
    benchmark:"Burj Khalifa: AED 5.5B, drove creation of entire Downtown Dubai district. Tokyo Skytree: $800M, 30M visitors/yr. Dubai Creek Tower aims for similar landmark-driven district economics.",
    priceImpact:"DCH currently 15-20% below Downtown Dubai pricing. Tower revival + Dubai Square expected to narrow this gap significantly. 80% of DCH buyers are investors positioning for appreciation.",
    milestones:["2016 – Original announcement & groundbreaking","2018 – Foundation completed","Apr 2020 – Formally suspended (COVID)","Jan 2026 – Alabbar confirms revival at DIPMF","Q1 2026 – Construction tender issued","TBD – Contractor selection & construction start"],
    sources:"Makana.com (Jan 2026), AGBI (Jan 2026), Time Out Dubai"
  },
  { name:"The Oasis", community:"Dubailand", value:"AED 73B", scale:"100M sqft with 7,000+ villas", type:"Ultra-Luxury Villas", timeline:"2026-2032", feature:"Largest villa project globally", status:"Under Construction", developer:"Emaar Properties", announced:"2023 (expanded 2025)",
    desc:"The Oasis is Emaar's AED 73 billion ultra-luxury villa mega-community spanning 100 million square feet with over 7,000 villas. Originally valued at AED 34B, it was expanded to AED 73B. Five sub-communities are launched: Palmiera (Phase 1-3), Mirage, Lavita, and Address Villas Tierra. Wade Adams Contracting appointed for initial infrastructure. Villas range from 4-7 bedrooms priced AED 8M-36M+. 25% of land dedicated to lakes, parks, and waterways. 1,213 villas transacted in the past 12 months with avg sale price AED 17.6M.",
    keyFacts:["AED 73B total value (expanded from AED 34B)","100 million sqft master-planned community","7,000+ ultra-luxury villas across 5 sub-communities","Palmiera (Q4 2027), Mirage (Q1 2029), Lavita, Address Tierra","Avg PPSF: AED 1,800-2,000 (BUA) | AED 1,942 DLD avg","1,213 villas sold in past 12 months (+21% DLD)","25% of land = lakes, parks, waterways, beaches","Only 3,100 villas in initial phases (scarcity premium)"],
    investorImpact:"Targets UHNW segment with zero comparable competition at this scale. Avg sale price AED 17.6M (+3.84% YoY). Asking prices up 10% in 6 months. Entry at AED 8M+ ensures Golden Visa eligibility. Wade Adams appointed as contractor — construction is real. Near Al Maktoum Airport growth corridor.",
    completion:"Infrastructure underway. Palmiera Phase 1 handover Q4 2027. Mirage Q1 2029. Mareva Q1 2030. Full community delivery 2028-2032.",
    benchmark:"Palm Jumeirah villas: AED 3,000-5,000/sqft (mature). Emirates Hills: AED 2,500-4,000/sqft. The Oasis at AED 1,800-2,000/sqft offers 40-50% discount to mature luxury — massive appreciation runway.",
    priceImpact:"DLD data: 1,213 transactions, avg AED 17.6M, prices +21% YoY. Asking prices up 10% in last 6 months per Bayut. Palmiera 4-bed from AED 8.5M; Mirage 5-bed from AED 15M; Lavita 7-bed from AED 36M+.",
    milestones:["Jun 2023 – Gala launch at Armani Hotel, Burj Khalifa","2024 – Palmiera Phase 2 & 3 launched","Dec 2025 – Lavita & Address Villas Tierra launched","2025 – Wade Adams appointed (infrastructure)","Q4 2027 – Palmiera Phase 1 handover","2028-2032 – Phased delivery continues"],
    sources:"Emaar Official, PropertyFinder, Bayut, Propsearch DLD Data, LYM Real Estate Analysis"
  },
  { name:"Grand Polo Club", community:"Grand Polo Club", value:"AED 41B", scale:"60M sqft with 6,661 residences", type:"Luxury Lifestyle", timeline:"2026-2030", feature:"World's first polo-themed community", status:"Under Construction", developer:"Emaar Properties", announced:"Apr 2025",
    desc:"Grand Polo Club & Resort is Emaar's AED 41 billion luxury lifestyle mega-development spanning 60 million square feet (5.54M sqm) with 22 villa communities and 6,661 residences. It features 3 professional polo fields, a riding school with jumping arenas, stables, and a signature clubhouse. Located 5 minutes from Al Maktoum International Airport and adjacent to The Oasis. Only 35-40% of land is allocated for construction — the rest is parks, polo fields, and amenities.",
    keyFacts:["AED 41B total development value","60 million sqft (5.54M sqm) masterplan","22 villa communities with 6,661 residences","3 professional polo fields + stables + riding school","35-40% construction, 60-65% green/amenity space","5 minutes from Al Maktoum International Airport","Adjacent to The Oasis community","3-bed TH from AED 3.5M | 5-bed villa from AED 9M+"],
    investorImpact:"Unique lifestyle positioning with zero direct competitors globally. ROI projected at 5-7% for 4-bed units. First phases typically see 30%+ appreciation by handover in new Emaar communities. Proximity to expanding Al Maktoum Airport adds long-term infrastructure premium. Affordable luxury entry at AED 3.5M vs The Oasis at AED 8M+.",
    completion:"EOI bookings opened April 30, 2025. Selvara cluster launched first. Infrastructure and villa construction underway. Handover June 2029.",
    benchmark:"Royal County of Berkshire (UK polo): £5M-20M homes but no integrated community. Argentine Polo Club: private but no residential. Grand Polo Club is the world's first fully integrated polo-residential community at scale.",
    priceImpact:"3-bed villas from AED 5.67M | 4-bed from AED 7.3M | 5-bed from AED 9M | 5-bed Equestrian Luxury from AED 19.9M. 80/20 payment plan with 10% booking.",
    milestones:["Apr 2025 – EOI bookings open, Selvara Phase 1","Mid 2025 – Equestra, Equiterra, Equiterra 2 launched","Late 2025 – Selvara 3 & 4, Chevalia Estate 2","2026 – Infrastructure construction active","Jun 2029 – First handovers targeted"],
    sources:"Emaar Official, PropertyFinder, Grand Polo Club Dubai, Off-Plan Properties AE"
  },
  { name:"Emaar Hills", community:"Emaar Hills", value:"AED 100B", scale:"40,000 residences", type:"Mixed-Use Community", timeline:"2025-2035", feature:"Next-generation master community", status:"Under Construction", developer:"Emaar Properties", announced:"Oct 2025",
    desc:"Emaar Hills is a AED 100 billion next-generation master community adjacent to the sold-out Dubai Hills Estate and Dubai Hills Mall. First launch 'Dubai Mansions' features ultra-luxury residences of 10,000-20,000 sqft. The community includes championship golf course, wellness centres, premium retail, and landscaped parks. With 40,000 planned residences over a decade, it effectively doubles the Dubai Hills corridor. Dubai's prime market recorded 1,500+ transactions above AED 10M in Q3 2025 alone, with villas making up 70% of high-value deals.",
    keyFacts:["AED 100B total development value","40,000 ultra-luxury residences planned","Dubai Mansions: 10,000-20,000 sqft homes","Championship golf course access","Walking distance to Dubai Hills Mall","Adjacent to sold-out Dubai Hills Estate","Decade-long phased development 2025-2035","Wellness centres, retail, landscaped parks"],
    investorImpact:"Dubai Hills Estate is sold out — Emaar Hills is the continuation. DHE has proven demand with AED 2,400 avg PPSF. Savills projects prime Dubai residential prices to rise up to 9.9% in 2025. Villas dominate 70% of deals above AED 10M. Early movers in new Emaar communities historically achieve significant appreciation by handover.",
    completion:"Dubai Mansions launched October 2025. Infrastructure groundwork begun. Phased delivery through 2035.",
    benchmark:"Dubai Hills Estate: AED 2,400/sqft avg, 16 projects, fully absorbed. Emaar Hills targets the same buyer profile at pre-development pricing. Comparable to Bel Air / Beverly Hills extensions in LA market.",
    priceImpact:"DHE avg PPSF AED 2,400. Emaar Hills early phases expected at discount to mature DHE pricing, with appreciation as community builds out. 1,500+ transactions >AED 10M in Q3 2025 shows strong UHNW demand.",
    milestones:["Oct 2025 – Emaar Hills & Dubai Mansions announced","Oct 2025 – Alabbar unveils at launch event","Late 2025 – EOI & first sales phase","2026 – Infrastructure construction","2027-2035 – Phased residential delivery"],
    sources:"Arabian Business (Oct 2025), Khaleej Times (Oct 2025), Zawya, Savills Dubai Research, Steven Leckie Analysis"
  },
  { name:"Dubai Creek Harbour District", community:"Dubai Creek Harbour", value:"AED 180B", scale:"11M sqm with 17,800+ units", type:"Master Community", timeline:"2020-2029", feature:"Metro Blue Line connected by 2029", status:"Under Construction", developer:"Emaar Properties", announced:"2015 (ongoing)",
    desc:"Dubai Creek Harbour is Emaar's flagship waterfront master community spanning 11 million square metres — three times the size of Downtown Dubai. Over 10,582 units completed with 7,217 more expected by 2029. The community will be served by the Dubai Metro Blue Line with 14 stations, dramatically improving connectivity. Property transactions rose 1% YoY with 4,280 sales at avg AED 2,470/sqft. Combined with Dubai Square (retail) and Creek Tower (landmark), DCH is being positioned as a self-contained rival city to Downtown.",
    keyFacts:["AED 180B total district investment","11 million sqm (3x Downtown Dubai)","10,582 units already completed & occupied","7,217 additional units by 2029","4,280 sales in past year at avg AED 2,470/sqft","Metro Blue Line (14 stations) approved for 2029","Home to Dubai Creek Tower + Dubai Square","80% of buyers are investors (agent survey)"],
    investorImpact:"Most mature mega-project with proven delivery. Metro Blue Line by 2029 is the biggest catalyst — historically, metro connectivity drives 15-25% value uplift in Dubai. At AED 2,470/sqft vs Downtown's AED 3,000, DCH offers 17% discount with convergence potential. Combined Creek Tower + Dubai Square + Metro = triple catalyst for price appreciation.",
    completion:"10,582 units delivered. Multiple towers under construction. Metro Blue Line approved with 2029 target. Dubai Square and Creek Tower in active pipeline.",
    benchmark:"Downtown Dubai: AED 3,000/sqft, 4,033 sales. DCH at AED 2,470/sqft with 4,280 sales — already matching Downtown in transaction volume but at 17% lower prices. Canary Wharf (London) analogy: secondary CBD that eventually rivalled the City.",
    priceImpact:"Avg AED 2,470/sqft (+3% YoY). 4,280 transactions in past year. Downtown Dubai at AED 3,000/sqft = 17% premium gap. Metro + Dubai Square + Creek Tower expected to close this gap over 3-5 years.",
    milestones:["2015 – DCH masterplan announced","2020 – First residential handovers","Sep 2025 – 10,582 units completed (Emaar report)","Dec 2025 – Dubai Square construction begins","Jan 2026 – Creek Tower revival confirmed","2029 – Metro Blue Line operational target"],
    sources:"AGBI (Jan 2026), Emaar Sep 2025 Report, DLD Transaction Data, Dubai RTA Metro Plans"
  },
  { name:"Al Maktoum Airport Expansion", community:"Dubai South", value:"AED 128B", scale:"5 runways, 260M passengers", type:"Infrastructure", timeline:"Phase 1: 2032", feature:"World's largest airport", status:"Under Construction", developer:"Dubai Government / DAEP", announced:"Apr 2024",
    desc:"Al Maktoum International Airport (DWC) is undergoing an AED 128 billion ($35 billion) expansion to become the world's largest airport. Approved by Sheikh Mohammed in April 2024, the expansion features 5 parallel runways, 400+ aircraft gates, and capacity for 260 million passengers annually across an area 5x the size of DXB. Phase 1 targets 150 million passengers by 2032. Emirates and flydubai will fully relocate from DXB. Binladin Contracting Group awarded AED 1B contract for second runway. Terminal substructure tenders issued mid-2025.",
    keyFacts:["AED 128B ($35B) total investment","5 parallel runways, 400+ aircraft gates","260 million annual passenger capacity (ultimate)","Phase 1: 150M passengers by 2032","70 sq km footprint (5x DXB)","Binladin Group: AED 1B runway 2 contract awarded","West Terminal: 800,000 sqm, 45M passenger capacity","14-station automated people mover (APM) system"],
    investorImpact:"Game-changer for all Dubai South properties. Emaar South, Grand Polo Club, and The Oasis sit directly in the growth corridor. Historical precedent: Areas near DXB (Deira, Bur Dubai) saw 200%+ appreciation over 20 years. Al Maktoum will support 1 million jobs and housing in Dubai South. Dubai South land values are among the lowest in Dubai — maximum upside potential.",
    completion:"Apr 2024: Sheikh Mohammed approves expansion. May 2025: Binladin Group awarded AED 1B runway 2 contract. Mid 2025: Terminal substructure tenders issued. 2032: Phase 1 operational (150M passengers).",
    benchmark:"King Salman Airport (Riyadh): competing for 'world's largest' title. Changi T5 (Singapore): $10B for 50M passengers. Al Maktoum at $35B for 260M passengers — 5x the scale of Changi T5 expansion.",
    priceImpact:"Dubai South avg PPSF among lowest in Dubai. Emaar South apartments from AED 1,200/sqft. Grand Polo Club villas from AED 1,700/sqft. Infrastructure-driven demand expected to multiply land values as airport scales.",
    milestones:["Apr 2024 – Sheikh Mohammed approves AED 128B expansion","May 2025 – AED 1B runway 2 contract to Binladin Group","May 2025 – Tristar E&C enabling works underway","Mid 2025 – Terminal substructure tenders issued","2026 – APM & baggage system tenders expected","2032 – Phase 1 operational (150M passengers)","2035+ – Full capacity (260M passengers)"],
    sources:"DAEP Official, Gulf News (Dec 2025), Aviation Business ME, MEED, Newsweek, FTI Consulting"
  },
];

/* ─── COMMUNITY INTELLIGENCE (Location Profiles) ─── */
export const communityIntel = {
  "Dubai Hills Estate": {
    tagline: "Golf-Side Family Living in the Heart of New Dubai",
    famousFor: "18-hole championship golf course with Burj Khalifa views, Dubai Hills Mall (650+ outlets), 1.45M sqm of parks & open spaces, 54 km bicycle route",
    masterDev: "Emaar & Meraas joint venture — first phase of Mohammed Bin Rashid City (MBR City)",
    lifestyle: "Family-oriented, golf lifestyle, park-centric, gated communities with 24/7 security",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "GEMS Wellington Academy, King's School Al Barsha, Dubai Heights Academy, Blossom Nursery" },
      { icon: "🏥", label: "Healthcare", items: "King's College Hospital London (on-site), Mediclinic Parkview Hospital, Saudi German Hospital" },
      { icon: "🛍️", label: "Malls", items: "Dubai Hills Mall (on-site, 650+ stores), Mall of the Emirates (12 min)" },
      { icon: "⛳", label: "Leisure", items: "Dubai Hills Golf Club, Dubai Hills Park (splash park, skate park, ice rink), 54 km cycling tracks" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 13, min: 15 },
      { dest: "Business Bay / DIFC", km: 14, min: 16 },
      { dest: "Dubai Marina / JBR", km: 24, min: 25 },
      { dest: "Dubai Intl Airport (DXB)", km: 24, min: 25 },
      { dest: "Mall of the Emirates", km: 9, min: 12 },
      { dest: "Sheikh Zayed Road (E11)", km: 4, min: 5 },
      { dest: "Al Khail Road (E44)", km: 1, min: 2 },
      { dest: "Palm Jumeirah", km: 17, min: 21 },
    ],
    roads: "Al Khail Road (E44), Umm Suqeim Street, Sheikh Mohammed Bin Zayed Road (E311). Future metro connection planned.",
    goldenVisa: true,
    avgYield: "4.5–5.5%",
  },
  "Dubai Creek Harbour": {
    tagline: "Waterfront Living Between Historic Dubai & Modern Skyline",
    famousFor: "Creek Tower (future landmark), Ras Al Khor Wildlife Sanctuary views, waterfront promenade, yacht marina, Creek Beach, Vida & Address branded hotels",
    masterDev: "Emaar & Dubai Holding — 9 integrated districts along historic Dubai Creek",
    lifestyle: "Waterfront urban, young professionals & couples, design-led calm with skyline views",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "Deira International School (15 min), North London Collegiate (Sobha Hartland, 15 min), King's School Nad Al Sheba" },
      { icon: "🏥", label: "Healthcare", items: "Mediclinic Creek Harbour (on-site), Berlin Hospital Nadd Al Hamar, Rashid Hospital (15 min)" },
      { icon: "🛍️", label: "Malls", items: "Dubai Mall (15 min), Dubai Festival City Mall (11 min), upcoming 820,000 sqm retail within DCH" },
      { icon: "🌊", label: "Leisure", items: "Creek Beach, Marina Yacht Club, Ras Al Khor Wildlife Sanctuary, 30-hectare Central Park, waterfront promenade" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 10, min: 15 },
      { dest: "Business Bay / DIFC", km: 9, min: 15 },
      { dest: "Dubai Intl Airport (DXB)", km: 11, min: 12 },
      { dest: "Dubai Festival City", km: 9, min: 11 },
      { dest: "Dubai Marina / JBR", km: 30, min: 30 },
      { dest: "Sheikh Zayed Road (E11)", km: 8, min: 12 },
      { dest: "Ras Al Khor Road (E44)", km: 2, min: 3 },
      { dest: "Dubai Frame", km: 10, min: 14 },
    ],
    roads: "Ras Al Khor Road (E44), Nad Al Hamar Road (D62). Dubai Metro Green Line nearby (Dubai Healthcare City / Creek stations).",
    goldenVisa: true,
    avgYield: "5.0–6.0%",
  },
  "Emaar Beachfront": {
    tagline: "Private Island Living Between Dubai Marina & Palm Jumeirah",
    famousFor: "1.5 km private beach, island gated community within Dubai Harbour, 27 residential towers, Address & Bristol branded residences, 1,100+ yacht berth marina",
    masterDev: "Emaar Properties — 10 million sqft gated island community in Dubai Harbour",
    lifestyle: "Ultra-luxury beachfront, resort-style, yacht owners, high-net-worth individuals & couples",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "iCademy Middle East (10 min), Dubai British School (10 min), GEMS Wellington (12 min), nurseries in JBR/Marina" },
      { icon: "🏥", label: "Healthcare", items: "Emirates Hospital Clinic Marina (8 min), Mediclinic Meadows (17 min), Al Zahra Hospital (13 min)" },
      { icon: "🛍️", label: "Malls", items: "On-site 13,000 sqft retail mall, Dubai Marina Mall (5 min), Nakheel Mall Palm (12 min), The Walk JBR (10 min)" },
      { icon: "🏖️", label: "Leisure", items: "1.5 km private beach, yacht marina (1,100+ berths), beach clubs, Ain Dubai (15 min), Bluewaters Island" },
    ],
    distances: [
      { dest: "Dubai Marina / JBR", km: 3, min: 5 },
      { dest: "Palm Jumeirah", km: 5, min: 12 },
      { dest: "Downtown Dubai / Burj Khalifa", km: 22, min: 25 },
      { dest: "Business Bay / DIFC", km: 22, min: 25 },
      { dest: "Dubai Intl Airport (DXB)", km: 35, min: 28 },
      { dest: "Sheikh Zayed Road (E11)", km: 2, min: 5 },
      { dest: "Media City / Internet City", km: 5, min: 8 },
      { dest: "Mall of the Emirates", km: 8, min: 12 },
    ],
    roads: "Sheikh Zayed Road (E11), Al Sufouh Road. Sobha Realty Metro Station nearby.",
    goldenVisa: true,
    avgYield: "3.5–5.0%",
  },
  "Emaar South": {
    tagline: "Affordable Golf Living at Dubai's Future Aviation Hub",
    famousFor: "18-hole championship golf course, proximity to Al Maktoum International Airport (5 min) & Expo City Dubai, most affordable Emaar entry point, Dubai's southern growth corridor",
    masterDev: "Emaar Properties — within Dubai South district, 15,000+ homes planned",
    lifestyle: "Value-conscious families, young professionals, frequent travellers, golf lifestyle at entry-level pricing",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "GEMS International School (on-site), Greenfield Community School, Durham School Dubai (20 min), South View School" },
      { icon: "🏥", label: "Healthcare", items: "NMC Royal Hospital (20 min), Al Maktoum Airport Clinic (7 min), Mediclinic Meadows (nearby)" },
      { icon: "🛍️", label: "Malls", items: "Community retail centre (on-site), Ibn Battuta Mall (25 min), City Centre Me'aisem (nearby)" },
      { icon: "⛳", label: "Leisure", items: "18-hole golf course, community parks, swimming pools, Dubai Parks & Resorts (15 min), Expo City Dubai (10 min)" },
    ],
    distances: [
      { dest: "Al Maktoum Intl Airport (DWC)", km: 5, min: 7 },
      { dest: "Expo City Dubai", km: 8, min: 10 },
      { dest: "Downtown Dubai / Burj Khalifa", km: 40, min: 32 },
      { dest: "Dubai Marina / JBR", km: 30, min: 25 },
      { dest: "Dubai Hills Estate", km: 25, min: 20 },
      { dest: "Sheikh Zayed Road (E11)", km: 15, min: 18 },
      { dest: "E311 (MBZ Road)", km: 3, min: 5 },
      { dest: "Emirates Road (E611)", km: 2, min: 3 },
    ],
    roads: "Sheikh Mohammed Bin Zayed Road (E311), Emirates Road (E611). Expo 2020 Metro Station (20 min by bus).",
    goldenVisa: false,
    avgYield: "5.0–6.5%",
  },
  "Expo Living": {
    tagline: "Next-Gen Living at the Expo City District",
    famousFor: "Built on legacy of World Expo 2020, smart city infrastructure, sustainability-focused, adjacent to Expo City Dubai permanent district",
    masterDev: "Emaar Properties — within Expo City / Dubai South area",
    lifestyle: "Tech-savvy professionals, sustainability-minded, young families, future-forward community",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "GEMS International School (nearby), South View School, planned community school" },
      { icon: "🏥", label: "Healthcare", items: "NMC Royal Hospital (15 min), Al Maktoum Airport Clinic, planned community clinic" },
      { icon: "🛍️", label: "Malls", items: "Expo City retail district, Ibn Battuta Mall (20 min), City Centre Me'aisem" },
      { icon: "🌿", label: "Leisure", items: "Expo City pavilions & events, Terra sustainability pavilion, Al Wasl Plaza, community parks" },
    ],
    distances: [
      { dest: "Expo City Dubai", km: 2, min: 3 },
      { dest: "Al Maktoum Intl Airport (DWC)", km: 8, min: 10 },
      { dest: "Downtown Dubai / Burj Khalifa", km: 38, min: 30 },
      { dest: "Dubai Marina / JBR", km: 28, min: 25 },
      { dest: "Dubai Hills Estate", km: 22, min: 18 },
      { dest: "Sheikh Zayed Road (E11)", km: 12, min: 15 },
      { dest: "E311 (MBZ Road)", km: 3, min: 5 },
      { dest: "Emirates Road (E611)", km: 3, min: 4 },
    ],
    roads: "Sheikh Mohammed Bin Zayed Road (E311), Emirates Road (E611). Expo 2020 Metro Station (Red Line).",
    goldenVisa: false,
    avgYield: "5.0–6.0%",
  },
  "The Valley": {
    tagline: "Desert-Inspired Suburban Family Retreat on Dubai-Al Ain Road",
    famousFor: "Dubai's first desert-themed community, 47,000 sqm Sports Village, 30,000 sqm Golden Beach, 10,000 sqm Kids' Dale, Town Centre with farmers' market, family townhouses & villas",
    masterDev: "Emaar Properties — 200+ hectare master-planned community in Dubailand along Dubai-Al Ain Road",
    lifestyle: "Family-first suburban, nature-inspired, active outdoor lifestyle, village atmosphere with modern amenities",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "Maple Bear Nursery (on-site), GEMS FirstPoint School (12 km), The Aquila School, Repton School (25 min)" },
      { icon: "🏥", label: "Healthcare", items: "Dubai London Clinic (nearby), HealthHub Clinic, Aster Clinic Silicon Oasis, Emirates Hospital (24 min)" },
      { icon: "🛍️", label: "Malls", items: "The Pavilion Town Centre (on-site, 32,000 sqm), Dubai Outlet Mall (nearby), Dubai Hills Mall (20 min)" },
      { icon: "🏊", label: "Leisure", items: "Golden Beach (30,000 sqm), Sports Village, Kids' Dale, Wellness Center with spa & padel, cycling tracks, Zen Garden" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 28, min: 25 },
      { dest: "Dubai Intl Airport (DXB)", km: 22, min: 22 },
      { dest: "Dubai Marina / JBR", km: 35, min: 33 },
      { dest: "Dubai Hills Estate", km: 18, min: 20 },
      { dest: "IMG Worlds of Adventure", km: 10, min: 12 },
      { dest: "Dubai Silicon Oasis", km: 12, min: 14 },
      { dest: "Dubai-Al Ain Road (E66)", km: 1, min: 2 },
      { dest: "Academic City", km: 12, min: 17 },
    ],
    roads: "Dubai-Al Ain Road (E66), Jebel Ali-Lehbab Road (E77). Public transport still developing, private vehicle recommended.",
    goldenVisa: false,
    avgYield: "5.0–6.0%",
  },
  "Grand Polo Club": {
    tagline: "Equestrian Ultra-Luxury Estate — Dubai's Polo Lifestyle Destination",
    famousFor: "60 million sqft polo & equestrian estate, championship polo fields, world-class stables & riding school, AED 41B+ project value, gated resort-style living",
    masterDev: "Emaar Properties — adjacent to The Oasis in Dubai Investment Park 2 (DIP 2)",
    lifestyle: "Ultra-luxury, equestrian enthusiasts, high-net-worth families, resort-style gated community",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "Greenfield International School (10 min), Bright Riders School (10 min), The Arbor School, planned community school" },
      { icon: "🏥", label: "Healthcare", items: "NMC Royal Hospital DIP (15 min), Paradise Plus Poly Clinic, Mediclinic Parkview Hospital" },
      { icon: "🛍️", label: "Malls", items: "City Centre Me'aisem (10 min), Ibn Battuta Mall (20 min), Dubai Outlet Mall (15 min)" },
      { icon: "🐎", label: "Leisure", items: "Grand polo field, equestrian club & stables, riding school, mini golf, padel courts, football courts, forest walk, dog park" },
    ],
    distances: [
      { dest: "Al Maktoum Intl Airport (DWC)", km: 5, min: 5 },
      { dest: "Expo City Dubai", km: 8, min: 10 },
      { dest: "Downtown Dubai / Burj Khalifa", km: 42, min: 35 },
      { dest: "Dubai Marina / JBR", km: 30, min: 28 },
      { dest: "Dubai Hills Estate / Mall", km: 22, min: 20 },
      { dest: "Sheikh Zayed Road (E11)", km: 18, min: 20 },
      { dest: "Expo Road (E77)", km: 2, min: 3 },
      { dest: "Emirates Road (E611)", km: 2, min: 3 },
    ],
    roads: "Expo Road (E77), Emirates Road (E611), Sheikh Zayed Bin Hamdan Al Nahyan Street.",
    goldenVisa: true,
    avgYield: "5.0–7.0%",
  },
  "Rashid Yachts & Marina": {
    tagline: "Historic Port Reborn as Dubai's Premier Yacht & Waterfront Destination",
    famousFor: "430-berth marina for yachts up to 100m, QE2 floating hotel, Dubai's longest swimmable canal pool (500m), Venetian piazza, Dubai Mall by the Sea (upcoming), heritage meets modern luxury",
    masterDev: "Emaar Properties & P&O Marinas — 6.8 million sqft in historic Port Rashid, Bur Dubai",
    lifestyle: "Maritime luxury, yacht owners, urban waterfront, blend of old & new Dubai charm",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "New Academy School (2 km), GEMS Winchester School (2.5 km), Ambassador School, nurseries in Bur Dubai" },
      { icon: "🏥", label: "Healthcare", items: "Rashid Hospital (15 min), Aster Hospital, International Modern Hospital, Dubai Healthcare City Phase 2 (7 km)" },
      { icon: "🛍️", label: "Malls", items: "BurJuman (15 min), Dubai Mall (16 min), upcoming Dubai Mall by the Sea (on-site), Karama Centre" },
      { icon: "⛵", label: "Leisure", items: "430-yacht marina, QE2 Hotel, 500m canal pool, Venetian piazza, beach club, floating yacht club, waterfront promenade" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 12, min: 19 },
      { dest: "Business Bay / DIFC", km: 10, min: 18 },
      { dest: "Dubai Intl Airport (DXB)", km: 13, min: 17 },
      { dest: "Dubai Mall", km: 11, min: 16 },
      { dest: "La Mer Beach", km: 5, min: 10 },
      { dest: "Sheikh Zayed Road (E11)", km: 4, min: 15 },
      { dest: "Dubai Frame", km: 7, min: 12 },
      { dest: "Gold Souk / Deira", km: 8, min: 20 },
    ],
    roads: "Al Mina Road (D75), Sheikh Zayed Road (E11), Infinity Bridge to Deira. Water taxi available.",
    goldenVisa: true,
    avgYield: "5.5–7.0%",
  },
  "The Oasis": {
    tagline: "Dubai's Most Exclusive Ultra-Luxury Villa & Mansion Sanctuary",
    famousFor: "100 million sqft mega-development (AED 73B value), 7,000+ luxury villas & mansions, 25% dedicated to green spaces & water features, world-renowned architect designs, largest villa project globally",
    masterDev: "Emaar Properties & Dubai Holding — in Dubailand, between Emirates Road & Sheikh Zayed Bin Hamdan Street",
    lifestyle: "Ultra-high-net-worth, mansion living, lagoon & waterway views, absolute privacy with resort amenities",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "South View School (2.6 km), Jebel Ali School (3.8 km), Fairgreen International School (15 min), GEMS United School" },
      { icon: "🏥", label: "Healthcare", items: "Saudi German Clinics (on-site), Mediclinic Parkview Hospital (22 min), Aster Clinic Arabian Ranches (16 min)" },
      { icon: "🛍️", label: "Malls", items: "City Centre Me'aisem (10 min), Dubai Outlet Mall (15 min), planned on-site retail" },
      { icon: "🌴", label: "Leisure", items: "Private beaches & lagoons, 54 km cycling route, jogging tracks, sports courts, Trump Intl Golf Club (10 min), Dubai Autodrome (12 min)" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 40, min: 35 },
      { dest: "Dubai Hills Estate", km: 20, min: 20 },
      { dest: "Dubai Marina / JBR", km: 32, min: 28 },
      { dest: "Sheikh Zayed Road (E11)", km: 15, min: 16 },
      { dest: "Al Maktoum Intl Airport (DWC)", km: 10, min: 12 },
      { dest: "Expo City Dubai", km: 12, min: 14 },
      { dest: "Emirates Road (E611)", km: 2, min: 3 },
      { dest: "Dubai Intl Airport (DXB)", km: 38, min: 35 },
    ],
    roads: "Emirates Road (E611), Sheikh Zayed Bin Hamdan Road (D54), future Al Khail Road (E44) extension.",
    goldenVisa: true,
    avgYield: "4.0–5.5%",
  },
  "Business Bay": {
    tagline: "Dubai's Central Business & Luxury Living District",
    famousFor: "Adjacent to Downtown Dubai, Dubai Canal waterfront, 240+ commercial & residential towers, home to Address & Palace branded residences, Dubai's CBD with skyline views",
    masterDev: "Dubai Properties — with select Emaar branded residences (Palace, Address)",
    lifestyle: "Urban executives, business professionals, luxury city living, walkable to Downtown & DIFC",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "JSS International School (10 min), GEMS Wellington Primary (12 min), multiple nurseries within Business Bay" },
      { icon: "🏥", label: "Healthcare", items: "Mediclinic Parkview Hospital (10 min), American Hospital Dubai (15 min), multiple clinics in Business Bay" },
      { icon: "🛍️", label: "Malls", items: "Dubai Mall (10 min walk), Bay Avenue Mall (on-site), City Walk (10 min)" },
      { icon: "🏙️", label: "Leisure", items: "Dubai Canal boardwalk, Downtown Dubai promenade, Dubai Opera (10 min), Business Bay parks, waterfront dining" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 3, min: 5 },
      { dest: "DIFC", km: 4, min: 7 },
      { dest: "Dubai Mall", km: 3, min: 8 },
      { dest: "Dubai Intl Airport (DXB)", km: 15, min: 18 },
      { dest: "Dubai Marina / JBR", km: 22, min: 22 },
      { dest: "Sheikh Zayed Road (E11)", km: 1, min: 3 },
      { dest: "Al Khail Road (E44)", km: 1, min: 3 },
      { dest: "City Walk", km: 4, min: 8 },
    ],
    roads: "Sheikh Zayed Road (E11), Al Khail Road (E44), Business Bay Metro Station (Red Line).",
    goldenVisa: true,
    avgYield: "5.5–7.0%",
  },
  "The Heights CW": {
    tagline: "Country Club & Wellness Living Adjacent to The Oasis",
    famousFor: "Premium country club lifestyle, wellness-focused design, adjacent to The Oasis mega-development, green corridor living",
    masterDev: "Emaar Properties — within the greater Oasis / Dubai South corridor",
    lifestyle: "Wellness-focused families, country club living, suburban tranquility with modern amenities",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "South View School (nearby), Jebel Ali School, Greenfield International School (10 min)" },
      { icon: "🏥", label: "Healthcare", items: "NMC Royal Hospital DIP (15 min), Mediclinic Parkview Hospital, community clinics planned" },
      { icon: "🛍️", label: "Malls", items: "City Centre Me'aisem (10 min), Ibn Battuta Mall (20 min)" },
      { icon: "🧘", label: "Leisure", items: "Country club & wellness centre, sports courts, cycling & jogging tracks, landscaped parks, nearby Oasis amenities" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 40, min: 35 },
      { dest: "Dubai Hills Estate", km: 22, min: 20 },
      { dest: "Dubai Marina / JBR", km: 30, min: 28 },
      { dest: "Al Maktoum Intl Airport (DWC)", km: 8, min: 10 },
      { dest: "Expo City Dubai", km: 10, min: 12 },
      { dest: "Sheikh Zayed Road (E11)", km: 16, min: 18 },
      { dest: "Emirates Road (E611)", km: 2, min: 3 },
      { dest: "Dubai Intl Airport (DXB)", km: 38, min: 35 },
    ],
    roads: "Emirates Road (E611), Sheikh Zayed Bin Hamdan Road (D54), Expo Road (E77).",
    goldenVisa: true,
    avgYield: "5.0–6.0%",
  },
};
