// Ellington Properties — Verified from official site + DLD Q1 2026
// Source: https://ellingtonproperties.ae
// Projects: 17 | DLD Q1 2026 transactions: 376

export const ellingtonIdentity = {
  id: "ellington", name: "Ellington Properties", legalName: "Ellington Properties LLC",
  founded: 2014, website: "https://ellingtonproperties.ae", color: "#2C3E50",
  dld: { transactions: 376, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

export const ellingtonProjects = [
  { id:"ell-1", developerId:"ellington", name:"Ellington Sands 1",
    officialUrl:"https://ellingtonproperties.ae/en/properties/ellington-sands",
    community:"Palm Deira / Dubai Islands", type:"Apartments", beds:"1–4BR+PH",
    status:"Off Plan", handover:"Q4 2026", price:3357000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-2", developerId:"ellington", name:"Ellington Sands 2",
    officialUrl:"https://ellingtonproperties.ae/en/properties/ellington-sands-2",
    community:"Palm Deira / Dubai Islands", type:"Apartments", beds:"1–4BR+PH",
    status:"Off Plan", handover:"Q4 2026", price:3449000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-3", developerId:"ellington", name:"Ellington Cove",
    officialUrl:"https://ellingtonproperties.ae/en/properties/ellington-cove",
    community:"Dubai Islands", type:"Apartments", beds:"1–3BR",
    status:"Off Plan", handover:"Q2 2028", price:2500000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-4", developerId:"ellington", name:"Ocean House",
    officialUrl:"https://ellingtonproperties.ae/en/properties/ocean-house",
    community:"Palm Jumeirah", type:"Apartments", beds:"1–4BR+PH",
    status:"Off Plan", handover:"Q2 2026", price:8370000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-5", developerId:"ellington", name:"The Waterside Villas",
    officialUrl:"https://ellingtonproperties.ae/en/properties/the-waterside",
    community:"MBR City District 11", type:"Villas", beds:"4–6BR Villas",
    status:"Ready", handover:"Q4 2025", price:17000000,
    payment:"60/40", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-6", developerId:"ellington", name:"Lakeshore",
    officialUrl:"https://ellingtonproperties.ae/en/properties/lakeshore",
    community:"MBR City District 11", type:"Villas", beds:"4–6BR Villas",
    status:"Off Plan", handover:"Q4 2026", price:12900000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-7", developerId:"ellington", name:"The Watercrest",
    officialUrl:"https://ellingtonproperties.ae/en/properties/the-watercrest",
    community:"MBR City District 11", type:"Villas", beds:"3–5BR TH/Villa",
    status:"Off Plan", handover:"Q1 2028", price:5000000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-8", developerId:"ellington", name:"Hillmont Residences",
    officialUrl:"https://ellingtonproperties.ae/en/properties/hillmont-residences",
    community:"JVC", type:"Apartments", beds:"1–4BR",
    status:"Off Plan", handover:"Q4 2026", price:1330000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-9", developerId:"ellington", name:"Upper House",
    officialUrl:"https://ellingtonproperties.ae/en/properties/upper-house",
    community:"JLT", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q1 2026", price:750000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-10", developerId:"ellington", name:"The Highbury",
    officialUrl:"https://ellingtonproperties.ae/en/properties/the-highbury",
    community:"Sobha Hartland", type:"Apartments", beds:"Studio–4BR+PH",
    status:"Off Plan", handover:"Q4 2026", price:912000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-11", developerId:"ellington", name:"The Portman",
    officialUrl:"https://ellingtonproperties.ae/en/properties/the-portman",
    community:"JVC", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Q3 2025", price:420000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-12", developerId:"ellington", name:"Highgrove by Ellington",
    officialUrl:"https://ellingtonproperties.ae/en/properties/highgrove",
    community:"Sobha Hartland", type:"Apartments", beds:"1–4BR+PH",
    status:"Off Plan", handover:"Q4 2027", price:1700000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-13", developerId:"ellington", name:"Claydon House",
    officialUrl:"https://ellingtonproperties.ae/en/properties/claydon-house",
    community:"Sobha Hartland", type:"Apartments", beds:"1–4BR",
    status:"Off Plan", handover:"Q4 2027", price:1560000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-14", developerId:"ellington", name:"The Crestmark",
    officialUrl:"https://ellingtonproperties.ae/en/properties/the-crestmark",
    community:"Business Bay", type:"Apartments", beds:"1–3BR+PH",
    status:"Off Plan", handover:"Q1 2026", price:1500000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-15", developerId:"ellington", name:"Art Bay West",
    officialUrl:"https://ellingtonproperties.ae/en/properties/art-bay",
    community:"Al Jaddaf", type:"Apartments", beds:"1–3BR+PH",
    status:"Off Plan", handover:"Q3 2026", price:1980000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-16", developerId:"ellington", name:"Art Bay East",
    officialUrl:"https://ellingtonproperties.ae/en/properties/art-bay",
    community:"Al Jaddaf", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q3 2026", price:1050000,
    payment:"70/30", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"ell-17", developerId:"ellington", name:"Ellington House 4",
    officialUrl:"https://ellingtonproperties.ae/en/properties/ellington-house-iv",
    community:"Dubai Hills Estate", type:"Apartments", beds:"1–3BR",
    status:"Ready", handover:"Q4 2025", price:2200000,
    payment:"50/50", developer:"Ellington Properties", color:"#2C3E50",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
];