// Omniyat — Verified from omniyat.com + PropertyFinder + Bayut
// Source: https://www.omniyat.com
// DLD Q1 2026: 73 transactions | Avg AED 27.6M | Ultra Luxury

export const omniyatIdentity = {
  id: "omniyat", name: "Omniyat", legalName: "Omniyat Properties LLC",
  founded: 2005, website: "https://www.omniyat.com", color: "#B8860B",
  dld: { transactions: 73, avgPrice: 27557997, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

export const omniyatProjects = [
  { id:"omn-1",  developerId:"omniyat", name:"Orla by Omniyat",          officialUrl:"https://www.omniyat.com/properties/orla",          community:"Palm Jumeirah",      type:"Apartments", beds:"2–4BR+Sky Palace+Mansion", status:"Under Construction", handover:"Q4 2026", price:25000000, payment:"5/65/30",  developer:"Omniyat", color:"#B8860B", source:"Official+Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-2",  developerId:"omniyat", name:"Orla Infinity",             officialUrl:"https://www.omniyat.com/properties/orla-infinity",  community:"Palm Jumeirah",      type:"Apartments", beds:"4BR Duplex",                status:"Under Construction", handover:"Q4 2027", price:72344755,payment:"5/65/30",  developer:"Omniyat", color:"#B8860B", source:"Official+PropertyFinder", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-3",  developerId:"omniyat", name:"AVA by Omniyat",            officialUrl:"https://www.omniyat.com/properties/ava",            community:"Palm Jumeirah",      type:"Apartments", beds:"3–5BR+PH",                  status:"Under Construction", handover:"Q2 2026", price:45000000,payment:"Custom",   developer:"Omniyat", color:"#B8860B", source:"Official+Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-4",  developerId:"omniyat", name:"Vela by Omniyat",           officialUrl:"https://www.omniyat.com/properties/vela",           community:"Business Bay",       type:"Apartments", beds:"3–5BR+PH",                  status:"Under Construction", handover:"Q4 2026", price:18000000,payment:"Custom",   developer:"Omniyat", color:"#B8860B", source:"Official+PropertyFinder", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-5",  developerId:"omniyat", name:"Vela Dorchester Collection", officialUrl:"https://www.omniyat.com/properties/vela",           community:"Business Bay",       type:"Apartments", beds:"3–5BR+PH",                  status:"Under Construction", handover:"Q1 2027", price:22000000,payment:"Custom",   developer:"Omniyat", color:"#B8860B", source:"Official", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-6",  developerId:"omniyat", name:"The Opus by Omniyat",       officialUrl:"https://www.omniyat.com/properties/the-opus",       community:"Business Bay",       type:"Apartments", beds:"1–2BR",                     status:"Ready",              handover:"Delivered", price:3500000,payment:"Ready",    developer:"Omniyat", color:"#B8860B", source:"Official", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-7",  developerId:"omniyat", name:"One at Palm Jumeirah",      officialUrl:"https://www.omniyat.com/properties/one-palm",       community:"Palm Jumeirah",      type:"Apartments", beds:"3–4BR+PH",                  status:"Ready",              handover:"Delivered", price:15000000,payment:"Ready",    developer:"Omniyat", color:"#B8860B", source:"Official", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-8",  developerId:"omniyat", name:"The Lana Residences",       officialUrl:"https://www.omniyat.com/properties/the-lana",       community:"Business Bay",       type:"Apartments", beds:"1–4BR+PH",                  status:"Ready",              handover:"Delivered", price:5000000,payment:"Ready",    developer:"Omniyat", color:"#B8860B", source:"Official", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-9",  developerId:"omniyat", name:"Omni 1 Business Bay",       officialUrl:"https://www.omniyat.com",                           community:"Business Bay",       type:"Apartments", beds:"Studio–2BR",                 status:"Ready",              handover:"Delivered", price:1800000,payment:"Ready",    developer:"Omniyat", color:"#B8860B", source:"Official", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-10", developerId:"omniyat", name:"The Sterling",              officialUrl:"https://www.omniyat.com/properties/the-sterling",   community:"Business Bay",       type:"Apartments", beds:"Studio–3BR",                 status:"Ready",              handover:"Delivered", price:1600000,payment:"Ready",    developer:"Omniyat", color:"#B8860B", source:"Official", confidence:"VERIFIED", dldVerified:true },
  { id:"omn-11", developerId:"omniyat", name:"The Pad",                   officialUrl:"https://www.omniyat.com/properties/the-pad",         community:"Business Bay",       type:"Apartments", beds:"Studio–1BR",                 status:"Ready",              handover:"Delivered", price:1200000,payment:"Ready",    developer:"Omniyat", color:"#B8860B", source:"Official", confidence:"VERIFIED", dldVerified:true },
];
