// Vincitore — Verified from official site + DLD Q1 2026
// Source: https://vincitore.ae
// Projects: 8 | DLD Q1 2026 transactions: 85

export const vincitoreIdentity = {
  id: "vincitore", name: "Vincitore", legalName: "Vincitore Real Estate Dev",
  founded: 2016, website: "https://vincitore.ae", color: "#9B59B6",
  dld: { transactions: 85, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

export const vincitoreProjects = [
  { id:"vin-1", developerId:"vincitore", name:"Vincitore Dolce Vita",
    officialUrl:"https://vincitore.ae/projects/dolce-vita",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q4 2026", price:650000,
    payment:"60/40", developer:"Vincitore", color:"#9B59B6",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"vin-2", developerId:"vincitore", name:"Vincitore Benessere",
    officialUrl:"https://vincitore.ae/projects/benessere",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q2 2026", price:750000,
    payment:"60/40", developer:"Vincitore", color:"#9B59B6",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"vin-3", developerId:"vincitore", name:"Vincitore Volare",
    officialUrl:"https://vincitore.ae/projects/volare",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q1 2027", price:800000,
    payment:"60/40", developer:"Vincitore", color:"#9B59B6",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"vin-4", developerId:"vincitore", name:"Vincitore Boulevard",
    officialUrl:"https://vincitore.ae/projects/boulevard",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:600000,
    payment:"Ready", developer:"Vincitore", color:"#9B59B6",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"vin-5", developerId:"vincitore", name:"Vincitore Palacio",
    officialUrl:"https://vincitore.ae/projects/palacio",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q4 2026", price:700000,
    payment:"60/40", developer:"Vincitore", color:"#9B59B6",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"vin-6", developerId:"vincitore", name:"Vincitore Aqua Dimore",
    officialUrl:"https://vincitore.ae/projects/aqua-dimore",
    community:"Dubai Sports City", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q2 2027", price:800000,
    payment:"60/40", developer:"Vincitore", color:"#9B59B6",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"vin-7", developerId:"vincitore", name:"Vincitore Lumini",
    officialUrl:"https://vincitore.ae/projects/lumini",
    community:"Dubai Science Park", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q4 2027", price:900000,
    payment:"60/40", developer:"Vincitore", color:"#9B59B6",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"vin-8", developerId:"vincitore", name:"Vincitore Velvet",
    officialUrl:"https://vincitore.ae/projects/velvet",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:700000,
    payment:"Ready", developer:"Vincitore", color:"#9B59B6",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
];