export const aziziIdentity = {
  id: "azizi", name: "Azizi Developments", legalName: "Azizi Developments LLC",
  founded: 2007, website: "https://www.azizidevelopments.com", color: "#16A085",
  dld: { transactions: 1150, avgPrice: 1009886, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

// Azizi Developments — Verified from official site + DLD Q1 2026
// Source: https://www.azizidevelopments.com
// Generated: 2026-04-01 | 30 projects
export const aziziProjects = [
  { id:"azizi-1", developerId:"azizi", name:"Azizi Venice", officialUrl:"https://www.azizidevelopments.com/en/venice",
    community:"Dubai South", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q4 2026", price:699000,
    payment:"50/50", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-2", developerId:"azizi", name:"Azizi Milan", officialUrl:"https://www.azizidevelopments.com/en/milan",
    community:"City of Arabia", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q4 2027", price:600000,
    payment:"50/50", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-3", developerId:"azizi", name:"Azizi Riviera Reve", officialUrl:"https://www.azizidevelopments.com/en/riviera-reve",
    community:"Meydan One", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q4 2025", price:900000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-4", developerId:"azizi", name:"Azizi Riviera Beachfront A", officialUrl:"https://www.azizidevelopments.com/en/riviera-beachfront",
    community:"Meydan One", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q4 2025", price:720000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-5", developerId:"azizi", name:"Azizi Riviera Beachfront B", officialUrl:"https://www.azizidevelopments.com/en/riviera-beachfront",
    community:"Meydan One", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q4 2025", price:720000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-6", developerId:"azizi", name:"Azizi Riviera Beachfront C", officialUrl:"https://www.azizidevelopments.com/en/riviera-beachfront",
    community:"Meydan One", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q4 2025", price:720000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-7", developerId:"azizi", name:"Azizi Riviera Azure", officialUrl:"https://www.azizidevelopments.com/en/riviera",
    community:"Meydan One", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q3 2025", price:800000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-8", developerId:"azizi", name:"Burj Azizi", officialUrl:"https://www.azizidevelopments.com/en/burj-azizi",
    community:"Sheikh Zayed Road", type:"Apartments", beds:"1–5BR+PH",
    status:"Off Plan", handover:"Q3 2030", price:7500000,
    payment:"20/50/30", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-9", developerId:"azizi", name:"Azizi Wasel", officialUrl:"https://www.azizidevelopments.com/en/wasel",
    community:"Dubai Islands", type:"Apartments", beds:"Studio–3BR+PH",
    status:"Off Plan", handover:"Q4 2027", price:900000,
    payment:"50/50", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-10", developerId:"azizi", name:"Azizi Beach Oasis", officialUrl:"https://www.azizidevelopments.com/en/beach-oasis",
    community:"Dubai Studio City", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Q3 2025", price:457000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-11", developerId:"azizi", name:"Azizi Beach Oasis 2", officialUrl:"https://www.azizidevelopments.com/en/beach-oasis-2",
    community:"Dubai Studio City", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q2 2026", price:514000,
    payment:"50/50", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-12", developerId:"azizi", name:"Azizi Venice 15A", officialUrl:"https://www.azizidevelopments.com/en/venice",
    community:"Dubai South", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q2 2027", price:619000,
    payment:"50/50", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-13", developerId:"azizi", name:"Azizi Venice Monaco Mansions", officialUrl:"https://www.azizidevelopments.com/en/venice-monaco-mansions",
    community:"Dubai South", type:"Villas", beds:"6–8BR Mansions",
    status:"Off Plan", handover:"Q4 2027", price:25000000,
    payment:"50/50", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-14", developerId:"azizi", name:"Azizi Raffi", officialUrl:"https://www.azizidevelopments.com/en/raffi",
    community:"Al Furjan", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q1 2028", price:686000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-15", developerId:"azizi", name:"Azizi Arian", officialUrl:"https://www.azizidevelopments.com/en/arian",
    community:"Jebel Ali Free Zone", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q1 2028", price:569000,
    payment:"50/50", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-16", developerId:"azizi", name:"Azizi Central", officialUrl:"https://www.azizidevelopments.com/en/central",
    community:"Al Furjan", type:"Apartments", beds:"1–3BR",
    status:"Ready", handover:"Q4 2025", price:1270000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-17", developerId:"azizi", name:"Azizi Creek Views 3", officialUrl:"https://www.azizidevelopments.com/en/creek-views-iii",
    community:"Al Jaddaf", type:"Apartments", beds:"Studio–3BR",
    status:"Ready", handover:"Q3 2025", price:1380000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-18", developerId:"azizi", name:"Azizi Vista", officialUrl:"https://www.azizidevelopments.com/en/vista",
    community:"Dubai Studio City", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Q3 2025", price:585000,
    payment:"30/70", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-19", developerId:"azizi", name:"Azizi Neila", officialUrl:"https://www.azizidevelopments.com/en/neila",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q4 2026", price:700000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-20", developerId:"azizi", name:"Azizi Ruby", officialUrl:"https://www.azizidevelopments.com/en/ruby",
    community:"JVC", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q4 2026", price:596000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-21", developerId:"azizi", name:"Azizi Star", officialUrl:"https://www.azizidevelopments.com/en/star",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q4 2026", price:650000,
    payment:"40/60", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-22", developerId:"azizi", name:"Mina by Azizi", officialUrl:"https://www.azizidevelopments.com/en/mina",
    community:"Palm Jumeirah", type:"Apartments", beds:"1–4BR+PH",
    status:"Ready", handover:"Delivered", price:3500000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-23", developerId:"azizi", name:"Azizi Riviera", officialUrl:"https://www.azizidevelopments.com/en/riviera",
    community:"Meydan One", type:"Apartments", beds:"Studio–3BR+TH",
    status:"Ready", handover:"Delivered", price:800000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-24", developerId:"azizi", name:"Azizi Amber", officialUrl:"https://www.azizidevelopments.com/en/amber",
    community:"Al Furjan", type:"Apartments", beds:"Studio–3BR",
    status:"Ready", handover:"Delivered", price:700000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-25", developerId:"azizi", name:"Azizi Aura", officialUrl:"https://www.azizidevelopments.com/en/aura",
    community:"Downtown Jebel Ali", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:550000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-26", developerId:"azizi", name:"Creek Views 1", officialUrl:"https://www.azizidevelopments.com/en/creek-views",
    community:"Al Jaddaf", type:"Apartments", beds:"Studio–3BR",
    status:"Ready", handover:"Delivered", price:900000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-27", developerId:"azizi", name:"Creek Views 2", officialUrl:"https://www.azizidevelopments.com/en/creek-views-ii",
    community:"Al Jaddaf", type:"Apartments", beds:"Studio–3BR",
    status:"Ready", handover:"Delivered", price:950000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-28", developerId:"azizi", name:"Azizi Aliyah", officialUrl:"https://www.azizidevelopments.com/en/aliyah",
    community:"Dubai Healthcare City", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:700000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-29", developerId:"azizi", name:"Park Avenue", officialUrl:"https://www.azizidevelopments.com/en/park-avenue",
    community:"Meydan One", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:750000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"azizi-30", developerId:"azizi", name:"Azizi Grand", officialUrl:"https://www.azizidevelopments.com/en/grand",
    community:"Dubai Sports City", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:650000,
    payment:"Ready", developer:"Azizi Developments", color:"#16A085",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
];