export const samanaIdentity = {
  id: "samana", name: "Samana Developers", legalName: "Samana Developers LLC",
  founded: 2017, website: "https://www.samanadevelopers.com", color: "#2980B9",
  dld: { transactions: 1020, avgPrice: 1106801, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

// Samana Developers — Verified from official site + DLD Q1 2026
// Source: https://www.samanadevelopers.com
// Generated: 2026-04-01 | 25 projects
export const samanaProjects = [
  { id:"sam-1", developerId:"samana", name:"Samana Barari Heights", officialUrl:"https://www.samanadevelopers.com/projects/samana-barari-heights",
    community:"Majan", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q4 2026", price:749000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-2", developerId:"samana", name:"Samana Barari Views", officialUrl:"https://www.samanadevelopers.com/projects/samana-barari-views",
    community:"Majan", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q2 2027", price:749000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-3", developerId:"samana", name:"Samana Barari Views 2", officialUrl:"https://www.samanadevelopers.com/projects/samana-barari-views-2",
    community:"Majan", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q4 2027", price:749000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-4", developerId:"samana", name:"Samana Waves 2", officialUrl:"https://www.samanadevelopers.com/projects/samana-waves-2",
    community:"JVC", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q1 2026", price:608000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-5", developerId:"samana", name:"Samana Manhattan 2", officialUrl:"https://www.samanadevelopers.com/projects/samana-manhattan-2",
    community:"JVC", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q4 2026", price:689000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-6", developerId:"samana", name:"Samana Skyros", officialUrl:"https://www.samanadevelopers.com/projects/samana-skyros",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q2 2026", price:649000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-7", developerId:"samana", name:"IVY Gardens by Samana", officialUrl:"https://www.samanadevelopers.com/projects/ivy-gardens",
    community:"Dubai Land", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q2 2026", price:522000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-8", developerId:"samana", name:"IVY Gardens 2 by Samana", officialUrl:"https://www.samanadevelopers.com/projects/ivy-gardens-2",
    community:"Dubai Land", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q4 2027", price:575000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-9", developerId:"samana", name:"Samana Portofino", officialUrl:"https://www.samanadevelopers.com/projects/samana-portofino",
    community:"Dubai Production City", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q1 2027", price:669000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-10", developerId:"samana", name:"Samana Lake Views", officialUrl:"https://www.samanadevelopers.com/projects/samana-lake-views",
    community:"Dubai Production City", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q4 2027", price:639000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-11", developerId:"samana", name:"Samana Lake Views 2", officialUrl:"https://www.samanadevelopers.com/projects/samana-lake-views-2",
    community:"Dubai Production City", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q4 2027", price:639000,
    payment:"71/29", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-12", developerId:"samana", name:"Samana California 2", officialUrl:"https://www.samanadevelopers.com/projects/samana-california-2",
    community:"Discovery Gardens", type:"Apartments", beds:"Studio–2BR",
    status:"Under Construction", handover:"Q4 2026", price:700000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-13", developerId:"samana", name:"Ocean Pearl by Samana", officialUrl:"https://www.samanadevelopers.com/projects/ocean-pearl",
    community:"Dubai Islands", type:"Apartments", beds:"1–4BR",
    status:"Off Plan", handover:"Q4 2026", price:1600000,
    payment:"58/42", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-14", developerId:"samana", name:"Ocean Pearl 2 by Samana", officialUrl:"https://www.samanadevelopers.com/projects/ocean-pearl-2",
    community:"Dubai Islands", type:"Apartments", beds:"1–4BR",
    status:"Off Plan", handover:"Q1 2027", price:2000000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-15", developerId:"samana", name:"Rome by Samana", officialUrl:"https://www.samanadevelopers.com/projects/rome",
    community:"MBR City District 11", type:"Apartments", beds:"Studio–3BR",
    status:"Off Plan", handover:"Q4 2027", price:1880000,
    payment:"50/50", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-16", developerId:"samana", name:"Samana Park Views", officialUrl:"https://www.samanadevelopers.com/projects/samana-park-views",
    community:"Arjan", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q2 2026", price:700000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-17", developerId:"samana", name:"Samana Manhattan", officialUrl:"https://www.samanadevelopers.com/projects/samana-manhattan",
    community:"JVC", type:"Apartments", beds:"Studio–3BR",
    status:"Ready", handover:"Q4 2025", price:630000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-18", developerId:"samana", name:"Samana Mykonos", officialUrl:"https://www.samanadevelopers.com/projects/samana-mykonos",
    community:"Dubai Studio City", type:"Apartments", beds:"Studio–3BR",
    status:"Under Construction", handover:"Q4 2026", price:999000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-19", developerId:"samana", name:"Samana California", officialUrl:"https://www.samanadevelopers.com/projects/samana-california",
    community:"Al Furjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Q4 2025", price:650000,
    payment:"100/0", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-20", developerId:"samana", name:"Samana Waves", officialUrl:"https://www.samanadevelopers.com/projects/samana-waves",
    community:"JVC", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:580000,
    payment:"Ready", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-21", developerId:"samana", name:"Samana Santorini", officialUrl:"https://www.samanadevelopers.com/projects/samana-santorini",
    community:"Dubai Studio City", type:"Apartments", beds:"Studio–3BR",
    status:"Ready", handover:"Delivered", price:900000,
    payment:"Ready", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-22", developerId:"samana", name:"Samana Miami", officialUrl:"https://www.samanadevelopers.com/projects/samana-miami",
    community:"JVC", type:"Apartments", beds:"Studio–3BR",
    status:"Ready", handover:"Delivered", price:700000,
    payment:"Ready", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-23", developerId:"samana", name:"Samana Golf Avenue", officialUrl:"https://www.samanadevelopers.com/projects/samana-golf-avenue",
    community:"Dubai Studio City", type:"Apartments", beds:"Studio–3BR",
    status:"Ready", handover:"Delivered", price:800000,
    payment:"Ready", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-24", developerId:"samana", name:"Samana Greens", officialUrl:"https://www.samanadevelopers.com/projects/samana-greens",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:500000,
    payment:"Ready", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"sam-25", developerId:"samana", name:"Samana Hills", officialUrl:"https://www.samanadevelopers.com/projects/samana-hills",
    community:"Arjan", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:550000,
    payment:"Ready", developer:"Samana Developers", color:"#2980B9",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
];