/* ─── DXB ANALYTICS — SOBHA REALTY DATA ─────────────────────────────────────
   S25–S26: Sobha Realty Full Intelligence Module
   Sources: Sobha Official · DLD · Bayut · Zawya · Khaleej Times · Better Homes
   Last verified: March 2026
────────────────────────────────────────────────────────────────────────── */

export const sobhaIdentity = {
  id:        "sobha",
  name:      "Sobha Realty",
  legalName: "Sobha Realty LLC",
  founded:   1976,
  founderDubai: 2003,
  founder:   "PNC Menon",
  chairman:  "Ravi Menon",
  hq:        "Mohammed Bin Rashid City, Dubai, UAE",
  type:      "Private",
  listed:    false,
  tier:      "T1",
  segment:   "Premium → Ultra-Luxury",
  color:     "#8B5CF6",
  website:   "https://sobharealty.com",
  confidence:"VERIFIED",
  tagline:   "Passion at Every Step",
  usp:       "100% backward integration — only developer that designs, builds and delivers entirely in-house",
  landBank:  4000000000, // USD 4B
};

export const sobhaFinancialHistory = [
  { year:2020, revenue:4.2,  netProfit:0.8,  propertySales:7.2  },
  { year:2021, revenue:5.8,  netProfit:1.1,  propertySales:9.8  },
  { year:2022, revenue:8.1,  netProfit:1.9,  propertySales:14.2 },
  { year:2023, revenue:11.4, netProfit:2.8,  propertySales:18.5 },
  { year:2024, revenue:16.2, netProfit:4.1,  propertySales:23.1 },
  { year:2025, revenue:21.8, netProfit:5.6,  propertySales:30.0 },
];

export const sobhaLive = {
  propertySales:    30.0,
  propertySalesUSD: 8.17,
  revenue:          21.8,
  netProfit:        5.6,
  ebitda:           8.2,
  yoyGrowth:        "+30%",
  uaqSales:         8.0, // AED 8B from UAQ
  dubaiSales:       22.0,
  uaePortfolio:     14, // 12 Dubai + 2 UAQ
  unitsDelivered:   27000,
  underConstruction:26933,
  employees:        3200,
  markets:          ["UAE","India","Bahrain","USA","Australia","UK"],
  rank:             "#3 Dubai Developer by Sales Volume (Aug 2025)",
  latestReportLabel:"FY2025 Sales Results",
  latestReportDate: "January 2026",
  source:           "Sobha Official Press Release Jan 2026 · Zawya · Khaleej Times",
  updatedAt:        "2026-03-27",
};

export const sobhaCommunities = [
  {
    id:          "sobha-hartland",
    name:        "Sobha Hartland",
    aka:         "Sobha Hartland I",
    location:    "Mohammed Bin Rashid City (MBR City), Dubai",
    type:        "Master Community — Urban Luxury",
    sizeSqFt:    8000000,
    launched:    2014,
    status:      "Established + Phase delivery",
    avgPpsf:     2800,
    avgGrossYield: 6.8,
    priceRange:  { apts: "AED 1.1M–12M", villas: "AED 8M–40M" },
    yoyGrowth:   "+18% 2025",
    green:       "30%+ green space",
    highlights:  ["North London Collegiate School", "Hartland Mall", "Crystal Lagoon", "30% green space", "Ras Al Khor Wildlife Sanctuary views", "8M sqft waterfront community"],
    subProjects: ["The Crest", "Sobha Creek Vista", "One Park Avenue", "Hartland Estates Villas", "Garden House", "Daffodil Towers", "Waves Grande", "Sobha Verde (JLT adjacent)"],
    investmentRating: "A+",
    confidence:  "VERIFIED",
  },
  {
    id:          "sobha-hartland-2",
    name:        "Sobha Hartland II",
    location:    "Mohammed Bin Rashid City (MBR City), Dubai",
    type:        "Master Community — Ultra Luxury",
    sizeSqFt:    6000000,
    launched:    2022,
    status:      "Active — Multiple phases",
    avgPpsf:     3200,
    avgGrossYield: 6.2,
    priceRange:  { apts: "AED 1.5M–15M", villas: "AED 21M–50M+" },
    highlights:  ["Sobha Estates Villas from AED 21M", "Lagoon-facing", "Meydan Racecourse views", "Ras Al Khor Wildlife Sanctuary adjacent"],
    subProjects: ["Sobha Estates Villas", "Skyvue Solair", "Skyvue Altier", "Skyvue Spectra"],
    investmentRating: "A+",
    confidence:  "VERIFIED",
  },
  {
    id:          "sobha-seahaven",
    name:        "Sobha Seahaven",
    location:    "Dubai Harbour",
    type:        "Waterfront Luxury — 3 Towers",
    sizeSqFt:    5500000,
    launched:    2022,
    status:      "Under Construction",
    towers:      3,
    units:       771,
    avgPpsf:     3800,
    avgGrossYield: 7.2,
    priceRange:  { apts: "AED 3M–12M", skyEdition: "AED 23M+" },
    handover:    "Q4 2026",
    payment:     "60/40",
    highlights:  ["Palm Jumeirah views", "Arabian Gulf views", "Smart home tech", "Health club", "Outdoor cinema", "Marina access", "Dubai Harbour location"],
    subProjects: ["Seahaven Tower A", "Seahaven Tower B", "Seahaven Tower C", "Seahaven Sky Edition (penthouses)"],
    investmentRating: "A+",
    confidence:  "VERIFIED",
  },
  {
    id:          "sobha-one",
    name:        "Sobha One",
    location:    "Ras Al Khor, MBR City",
    type:        "Golf Course Residences — 5 Towers",
    sizeSqFt:    4000000,
    launched:    2021,
    status:      "Under Construction",
    towers:      5,
    floors:      "33–65",
    avgPpsf:     2200,
    avgGrossYield: 6.5,
    priceRange:  { apts: "AED 1.1M–8M" },
    highlights:  ["Golf course views", "Sky bridges connecting towers", "Ras Al Khor Wildlife Sanctuary", "Downtown Dubai 15min", "Airport 15min"],
    investmentRating: "A",
    confidence:  "VERIFIED",
  },
  {
    id:          "sobha-reserve",
    name:        "Sobha Reserve",
    location:    "Wadi Al Safa, Dubailand",
    type:        "Luxury Villas — Gated Community",
    sizeSqFt:    3500000,
    launched:    2020,
    status:      "Partially Delivered",
    avgPpsf:     1800,
    avgGrossYield: 5.8,
    priceRange:  { villas: "AED 5M–18M" },
    highlights:  ["Private pool villas", "Gated security", "5-6BR configurations", "Lush landscaping"],
    investmentRating: "A",
    confidence:  "VERIFIED",
  },
  {
    id:          "sobha-siniya-island",
    name:        "Sobha Siniya Island",
    location:    "Umm Al Quwain",
    type:        "Island Community — Waterfront",
    sizeSqFt:    12000000,
    launched:    2024,
    status:      "Off Plan",
    avgPpsf:     1400,
    priceRange:  { apts: "AED 800K–5M", villas: "AED 3M–15M" },
    highlights:  ["Natural island setting", "Marina", "Beach access", "UAQ emerging market", "1 hr from Dubai"],
    salesContribution2025: "Part of AED 8B UAQ sales",
    investmentRating: "B+",
    confidence:  "VERIFIED",
  },
  {
    id:          "sobha-skyparks",
    name:        "Sobha SkyParks",
    location:    "Sheikh Zayed Road, Dubai",
    type:        "Ultra High-Rise — 109 Floors",
    sizeSqFt:    "40,000 sqft plot",
    launched:    2025,
    status:      "Off Plan",
    floors:      109,
    units:       684,
    avgPpsf:     4200,
    priceRange:  { apts: "AED 2.5M–25M" },
    highlights:  ["109 floors", "Sheikh Zayed Road", "684 residences", "1-2-3BR luxury apts", "UAE's tallest Sobha tower"],
    investmentRating: "A",
    confidence:  "VERIFIED",
  },
  {
    id:          "downtown-uaq",
    name:        "Downtown UAQ | Sobha Realty",
    location:    "Umm Al Quwain",
    type:        "Masterplan — Mixed Use",
    launched:    2025,
    status:      "Off Plan",
    highlights:  ["Sobha's first UAQ masterplan", "Mixed-use city", "AED 8B UAQ sales contributor"],
    investmentRating: "B+",
    confidence:  "VERIFIED",
  },
];

export const sobhaProjects = [
  { id:"sobha-1",  developerId:"sobha", name:"Sobha Estates Villas", officialUrl:"https://sobharealty.com/properties/sobha-estates/",         community:"Sobha Hartland II",  district:"MBR City",       type:"Villas",      beds:"5–7BR", status:"Under Construction", handover:"Q4 2026", price:21000000, sizeFrom:8000,  sizeTo:20000,  ppsf:2625, payment:"80/20",  construction:65, branded:false, brand:"—",          tier:"Ultra-Luxury",  source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"5BR Villa",sqftFrom:8000,sqftTo:12000,priceFrom:21000000},{type:"6BR Villa",sqftFrom:13000,sqftTo:16000,priceFrom:34125000},{type:"7BR Villa",sqftFrom:17000,sqftTo:20000,priceFrom:51750000}] },
  { id:"sobha-2",  developerId:"sobha", name:"Sobha Seahaven", officialUrl:"https://sobharealty.com/properties/sobha-seahaven/",               community:"Dubai Harbour",       district:"DH",             type:"Apartments",  beds:"1–6BR", status:"Under Construction", handover:"Q4 2026", price:3000000,  sizeFrom:840,   sizeTo:8000,   ppsf:3571, payment:"60/40",  construction:70, branded:false, brand:"—",          tier:"Ultra-Luxury",  source:"Bayut",          confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:840,sqftTo:1100,priceFrom:3000000},{type:"2BR",sqftFrom:1400,sqftTo:1700,priceFrom:5000000},{type:"3BR",sqftFrom:2200,sqftTo:2800,priceFrom:7857000},{type:"4BR",sqftFrom:3500,sqftTo:4500,priceFrom:12500000}] },
  { id:"sobha-3",  developerId:"sobha", name:"Sobha Seahaven Sky Edition", officialUrl:"https://sobharealty.com/properties/sobha-seahaven/",   community:"Dubai Harbour",       district:"DH",             type:"Penthouses",  beds:"3–4BR", status:"Under Construction", handover:"Q4 2026", price:23000000, sizeFrom:5000,  sizeTo:12000,  ppsf:4600, payment:"60/40",  construction:70, branded:false, brand:"—",          tier:"Ultra-Luxury",  source:"Bayut",          confidence:"VERIFIED",
    unitBreakdown:[{type:"3BR Sky PH",sqftFrom:5000,sqftTo:7000,priceFrom:23000000},{type:"4BR Sky PH",sqftFrom:8000,sqftTo:12000,priceFrom:36800000}] },
  { id:"sobha-4",  developerId:"sobha", name:"Sobha One", officialUrl:"https://sobharealty.com/properties/sobha-one/",                    community:"Sobha Hartland",      district:"MBR City",       type:"Apartments",  beds:"1–4BR", status:"Under Construction", handover:"Q2 2026", price:1100000,  sizeFrom:732,   sizeTo:2352,   ppsf:1503, payment:"60/40",  construction:85, branded:false, brand:"—",          tier:"Premium",       source:"Bayut",          confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:732,sqftTo:900,priceFrom:1100000},{type:"2BR",sqftFrom:1100,sqftTo:1400,priceFrom:1653000},{type:"3BR",sqftFrom:1600,sqftTo:2000,priceFrom:2406000},{type:"4BR",sqftFrom:2100,sqftTo:2352,priceFrom:3152000}] },
  { id:"sobha-5",  developerId:"sobha", name:"Skyvue Solair", officialUrl:"https://sobharealty.com/properties/",                community:"Sobha Hartland II",  district:"MBR City",       type:"Apartments",  beds:"1–3BR", status:"Under Construction", handover:"Q4 2027", price:1800000,  sizeFrom:700,   sizeTo:2200,   ppsf:2571, payment:"60/40",  construction:40, branded:false, brand:"—",          tier:"Premium",       source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1800000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:3085000},{type:"3BR",sqftFrom:1800,sqftTo:2200,priceFrom:4628000}] },
  { id:"sobha-6",  developerId:"sobha", name:"Skyvue Altier", officialUrl:"https://sobharealty.com/properties/",                community:"Sobha Hartland II",  district:"MBR City",       type:"Apartments",  beds:"1–3BR", status:"Off Plan",           handover:"Q1 2028", price:2200000,  sizeFrom:800,   sizeTo:2500,   ppsf:2750, payment:"60/40",  construction:15, branded:false, brand:"—",          tier:"Premium",       source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:800,sqftTo:1000,priceFrom:2200000},{type:"2BR",sqftFrom:1300,sqftTo:1600,priceFrom:3575000},{type:"3BR",sqftFrom:2000,sqftTo:2500,priceFrom:5500000}] },
  { id:"sobha-7",  developerId:"sobha", name:"Sobha Reserve", officialUrl:"https://sobharealty.com/properties/sobha-reserve/",                community:"Sobha Reserve",       district:"Dubailand",      type:"Villas",      beds:"4–6BR", status:"Partially Delivered",handover:"Q2 2026", price:5000000,  sizeFrom:4000,  sizeTo:12000,  ppsf:1250, payment:"80/20",  construction:90, branded:false, brand:"—",          tier:"Premium",       source:"Bayut",          confidence:"VERIFIED",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:4000,sqftTo:6000,priceFrom:5000000},{type:"5BR Villa",sqftFrom:7000,sqftTo:9000,priceFrom:8750000},{type:"6BR Villa",sqftFrom:10000,sqftTo:12000,priceFrom:12500000}] },
  { id:"sobha-8",  developerId:"sobha", name:"330 Riverside Crescent", officialUrl:"https://sobharealty.com/properties/riverside-crescent/",       community:"Sobha Hartland",      district:"MBR City",       type:"Apartments",  beds:"1–3BR", status:"Under Construction", handover:"Q3 2026", price:1400000,  sizeFrom:560,   sizeTo:1800,   ppsf:2500, payment:"60/40",  construction:80, branded:false, brand:"—",          tier:"Mid-Premium",   source:"Bayut",          confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:560,sqftTo:750,priceFrom:1400000},{type:"2BR",sqftFrom:1000,sqftTo:1250,priceFrom:2500000},{type:"3BR",sqftFrom:1550,sqftTo:1800,priceFrom:3875000}] },
  { id:"sobha-9",  developerId:"sobha", name:"320 Riverside Crescent", officialUrl:"https://sobharealty.com/properties/riverside-crescent/",       community:"Sobha Hartland",      district:"MBR City",       type:"Apartments",  beds:"1–3BR", status:"Under Construction", handover:"Q4 2025", price:1300000,  sizeFrom:540,   sizeTo:1700,   ppsf:2407, payment:"60/40",  construction:95, branded:false, brand:"—",          tier:"Mid-Premium",   source:"Bayut",          confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:540,sqftTo:720,priceFrom:1300000},{type:"2BR",sqftFrom:950,sqftTo:1200,priceFrom:2407000},{type:"3BR",sqftFrom:1450,sqftTo:1700,priceFrom:3493000}] },
  { id:"sobha-10", developerId:"sobha", name:"Sobha Verde", officialUrl:"https://sobharealty.com/properties/sobha-verde/",                  community:"JLT",                 district:"JLT",            type:"Apartments",  beds:"1–4BR", status:"Under Construction", handover:"Q4 2026", price:1600000,  sizeFrom:700,   sizeTo:2800,   ppsf:2286, payment:"60/40",  construction:60, branded:false, brand:"—",          tier:"Premium",       source:"Bayut",          confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1600000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:2742000},{type:"3BR",sqftFrom:1900,sqftTo:2400,priceFrom:4342000},{type:"4BR",sqftFrom:2500,sqftTo:2800,priceFrom:5714000}] },
  { id:"sobha-11", developerId:"sobha", name:"The S Tower", officialUrl:"https://sobharealty.com/properties/",                  community:"Sobha Hartland",      district:"MBR City",       type:"Apartments",  beds:"1–4BR", status:"Off Plan",           handover:"Q4 2028", price:2500000,  sizeFrom:900,   sizeTo:4000,   ppsf:2778, payment:"60/40",  construction:5,  branded:false, brand:"—",          tier:"Ultra-Luxury",  source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:900,sqftTo:1100,priceFrom:2500000},{type:"2BR",sqftFrom:1500,sqftTo:1900,priceFrom:4166000},{type:"3BR",sqftFrom:2300,sqftTo:2800,priceFrom:6388000},{type:"4BR PH",sqftFrom:3500,sqftTo:4000,priceFrom:9722000}] },
  { id:"sobha-12", developerId:"sobha", name:"Sobha Solis", officialUrl:"https://sobharealty.com/properties/sobha-solis/",                  community:"Dubai Motor City",    district:"DMC",            type:"Apartments",  beds:"1–3BR", status:"Off Plan",           handover:"Q4 2028", price:1100000,  sizeFrom:600,   sizeTo:1800,   ppsf:1833, payment:"60/40",  construction:5,  branded:false, brand:"—",          tier:"Mid-Premium",   source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:600,sqftTo:800,priceFrom:1100000},{type:"2BR",sqftFrom:1100,sqftTo:1350,priceFrom:2016000},{type:"3BR",sqftFrom:1500,sqftTo:1800,priceFrom:2750000}] },
  { id:"sobha-13", developerId:"sobha", name:"Sobha SkyParks", officialUrl:"https://sobharealty.com/properties/",               community:"Sheikh Zayed Road",   district:"SZR",            type:"Apartments",  beds:"1–3BR", status:"Off Plan",           handover:"Q1 2030", price:2500000,  sizeFrom:600,   sizeTo:5000,   ppsf:4167, payment:"60/40",  construction:0,  branded:false, brand:"—",          tier:"Ultra-Luxury",  source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:600,sqftTo:800,priceFrom:2500000},{type:"2BR",sqftFrom:1100,sqftTo:1400,priceFrom:4583000},{type:"3BR",sqftFrom:1700,sqftTo:2200,priceFrom:7083000}] },
  { id:"sobha-14", developerId:"sobha", name:"Sobha Central", officialUrl:"https://sobharealty.com/properties/sobha-central/",                community:"Dubai",               district:"TBC",            type:"Master Plan", beds:"1–4BR", status:"Off Plan",           handover:"Q4 2029", price:1800000,  sizeFrom:700,   sizeTo:3500,   ppsf:2571, payment:"60/40",  construction:0,  branded:false, brand:"—",          tier:"Premium",       source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1800000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:3085000},{type:"3BR",sqftFrom:1900,sqftTo:2400,priceFrom:4885000},{type:"4BR",sqftFrom:2700,sqftTo:3500,priceFrom:6942000}] },
  { id:"sobha-15", developerId:"sobha", name:"Sobha Siniya Island", officialUrl:"https://sobharealty.com/properties/siniya-island/",          community:"Umm Al Quwain",       district:"UAQ",            type:"Mixed",       beds:"1–6BR", status:"Off Plan",           handover:"Q4 2028", price:900000,   sizeFrom:500,   sizeTo:8000,   ppsf:1800, payment:"60/40",  construction:5,  branded:false, brand:"—",          tier:"Premium",       source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR Apt",sqftFrom:500,sqftTo:700,priceFrom:900000},{type:"2BR Apt",sqftFrom:900,sqftTo:1200,priceFrom:1620000},{type:"3BR Villa",sqftFrom:3000,sqftTo:5000,priceFrom:5400000},{type:"5BR Villa",sqftFrom:6000,sqftTo:8000,priceFrom:10800000}] },
  { id:"sobha-16", developerId:"sobha", name:"Downtown UAQ | Sobha", officialUrl:"https://sobharealty.com/properties/",         community:"Umm Al Quwain",       district:"UAQ",            type:"Master Plan", beds:"Studio–4BR",status:"Off Plan",      handover:"TBC",      price:800000,   sizeFrom:400,   sizeTo:3000,   ppsf:2000, payment:"60/40",  construction:0,  branded:false, brand:"—",          tier:"Mid-Premium",   source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"Studio",sqftFrom:400,sqftTo:550,priceFrom:800000},{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1400000},{type:"2BR",sqftFrom:1200,sqftTo:1500,priceFrom:2400000},{type:"3BR",sqftFrom:1700,sqftTo:2200,priceFrom:3400000}] },
  { id:"sobha-17", developerId:"sobha", name:"Sobha Elwood", officialUrl:"https://sobharealty.com/properties/sobha-elwood/",                 community:"Dubai Al Ain Road",   district:"DAR",            type:"Villas",      beds:"4–6BR", status:"Off Plan",           handover:"Q4 2027", price:4500000,  sizeFrom:3500,  sizeTo:8000,   ppsf:1286, payment:"60/40",  construction:10, branded:false, brand:"—",          tier:"Premium",       source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"4BR Villa",sqftFrom:3500,sqftTo:5000,priceFrom:4500000},{type:"5BR Villa",sqftFrom:5500,sqftTo:6500,priceFrom:7071000},{type:"6BR Villa",sqftFrom:7000,sqftTo:8000,priceFrom:9000000}] },
  { id:"sobha-18", developerId:"sobha", name:"Sobha Orbis", officialUrl:"https://sobharealty.com/properties/sobha-orbis/",                  community:"Motor City",          district:"DMC",            type:"Apartments",  beds:"1–3BR", status:"Off Plan",           handover:"Q2 2028", price:1000000,  sizeFrom:560,   sizeTo:1800,   ppsf:1786, payment:"60/40",  construction:5,  branded:false, brand:"—",          tier:"Mid-Premium",   source:"Sobha Official", confidence:"VERIFIED",
    unitBreakdown:[{type:"1BR",sqftFrom:560,sqftTo:750,priceFrom:1000000},{type:"2BR",sqftFrom:1000,sqftTo:1250,priceFrom:1785000},{type:"3BR",sqftFrom:1500,sqftTo:1800,priceFrom:2678000}] },
];

export const sobhaRisks = [
  { factor:"Vertical Integration Risk — Single Builder Model", level:4, likelihood:3, impact:4, score:48, mitigation:"In-house construction eliminates contractor default but concentrates operational risk. 50yr track record.", assessment:"MODERATE", color:"#F59E0B" },
  { factor:"Geographic Concentration — Dubai + UAQ",           level:3, likelihood:3, impact:4, score:36, mitigation:"Expanding to USA, Australia, Bahrain. UAQ diversification reduces Dubai dependence.", assessment:"MODERATE", color:"#D4A843" },
  { factor:"Private Ownership — No Public Disclosure",         level:3, likelihood:2, impact:4, score:24, mitigation:"Not listed. DLD transaction data + press releases as verification.", assessment:"MODERATE", color:"#D4A843" },
  { factor:"Premium Pricing Risk",                             level:3, likelihood:3, impact:3, score:27, mitigation:"Quality differentiation + backward integration justifies premium. 5–10% ROI track record.", assessment:"MODERATE", color:"#D4A843" },
  { factor:"Construction Pipeline Scale",                      level:3, likelihood:2, impact:4, score:24, mitigation:"27,000 units under construction. In-house build team. Track record of on-time delivery.", assessment:"MODERATE", color:"#D4A843" },
  { factor:"Currency Risk (AED Peg)",                          level:1, likelihood:1, impact:2, score:2,  mitigation:"USD peg since 1997. Indian investors — INR/AED risk only.", assessment:"VERY LOW", color:"#10B981" },
  { factor:"Regulatory / DLD Changes",                         level:1, likelihood:1, impact:2, score:2,  mitigation:"Full DLD/RERA compliance. Quality-led approach reduces regulatory risk.", assessment:"VERY LOW", color:"#10B981" },
  { factor:"Demand Sustainability",                            level:2, likelihood:2, impact:3, score:12, mitigation:"Premium segment demand resilient. Indian HNW buyer base. UAE Golden Visa driver.", assessment:"LOW", color:"#10B981" },
];

export const sobhaSegments = [
  { name:"Dubai Residential",    revenue:16.4, growth:"+28%",  color:"#8B5CF6" },
  { name:"UAQ / Siniya Island",  revenue:4.2,  growth:"+120%", color:"#00BFA5" },
  { name:"International Markets",revenue:1.2,  growth:"+85%",  color:"#3B82F6" },
];

export const sobhaRadar = [
  { metric:"Build Quality",      sobha:98, emaar:85, damac:78, market:70 },
  { metric:"Sales Volume",       sobha:78, emaar:100,damac:92, market:70 },
  { metric:"Delivery Record",    sobha:92, emaar:92, damac:82, market:72 },
  { metric:"Yield Performance",  sobha:82, emaar:78, damac:85, market:70 },
  { metric:"Price Appreciation", sobha:86, emaar:86, damac:83, market:72 },
  { metric:"Community Scale",    sobha:72, emaar:88, damac:90, market:68 },
  { metric:"International Reach",sobha:68, emaar:72, damac:80, market:55 },
  { metric:"Financial Strength", sobha:72, emaar:95, damac:75, market:65 },
];

export const sobhaYields = [
  { community:"Sobha Hartland",    unit:"Apartments",  gross:6.8, net:5.1, avgRent:95000,  avgPrice:1400000, demand:"Very High" },
  { community:"Sobha Hartland",    unit:"Villas",      gross:5.5, net:4.1, avgRent:320000, avgPrice:5800000, demand:"High" },
  { community:"Sobha Hartland II", unit:"Apartments",  gross:6.2, net:4.7, avgRent:120000, avgPrice:1940000, demand:"High" },
  { community:"Sobha Seahaven",    unit:"Apartments",  gross:7.2, net:5.4, avgRent:216000, avgPrice:3000000, demand:"Very High" },
  { community:"Sobha One",         unit:"Apartments",  gross:6.5, net:4.9, avgRent:71500,  avgPrice:1100000, demand:"High" },
  { community:"Sobha Reserve",     unit:"Villas",      gross:5.8, net:4.4, avgRent:290000, avgPrice:5000000, demand:"High" },
  { community:"Sobha Verde JLT",   unit:"Apartments",  gross:7.5, net:5.6, avgRent:120000, avgPrice:1600000, demand:"Very High" },
];

export const sobhaMegaProjects = [
  { name:"Sobha SkyParks",         scale:"AED 10B+ GDV", units:"684", sqft:"40,000 sqft plot, 109 floors", timeline:"Launched 2025 · Q1 2030", status:"Off Plan", record:"109-floor ultra-tower Sheikh Zayed Road" },
  { name:"Sobha Seahaven",         scale:"AED 6B+ GDV",  units:"771", sqft:"5.5M sqft Dubai Harbour",      timeline:"2022 · Q4 2026",          status:"Under Construction", record:"Sobha's first Dubai Harbour waterfront" },
  { name:"Sobha Siniya Island",    scale:"AED 8B UAQ Sales", units:"TBD", sqft:"12M sqft natural island",  timeline:"2024 · Q4 2028+",         status:"Off Plan", record:"UAE's largest private island development" },
  { name:"Downtown UAQ | Sobha",   scale:"AED 20B+ GDV", units:"TBD", sqft:"City masterplan",             timeline:"2025 · TBC",              status:"Off Plan", record:"AED 20B AquaCrest + tallest UAE tower" },
];

export default {
  identity:         sobhaIdentity,
  live:             sobhaLive,
  financialHistory: sobhaFinancialHistory,
  communities:      sobhaCommunities,
  projects:         sobhaProjects,
  risks:            sobhaRisks,
  segments:         sobhaSegments,
  radar:            sobhaRadar,
  megaProjects:     sobhaMegaProjects,
  yields:           sobhaYields,
};
