// Reportage Properties — Verified from official site + DLD Q1 2026
// Source: https://reportageuae.com
// Projects: 8 | DLD Q1 2026 transactions: 220

export const reportageIdentity = {
  id: "reportage", name: "Reportage Properties", legalName: "Reportage Properties LLC",
  founded: 2014, website: "https://reportageuae.com", color: "#27AE60",
  dld: { transactions: 220, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

export const reportageProjects = [
  { id:"rep-1", developerId:"reportage", name:"Bianca by Reportage",
    officialUrl:"https://reportageuae.com/projects/bianca",
    community:"Dubailand", type:"Townhouses", beds:"2–4BR TH",
    status:"Off Plan", handover:"Q4 2026", price:790000,
    payment:"62/38", developer:"Reportage Properties", color:"#27AE60",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"rep-2", developerId:"reportage", name:"Rukan Lofts Phase 3",
    officialUrl:"https://reportageuae.com/projects/rukan-lofts",
    community:"Dubailand", type:"Apartments", beds:"Studio–2BR",
    status:"Off Plan", handover:"Q1 2027", price:720000,
    payment:"62/38", developer:"Reportage Properties", color:"#27AE60",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"rep-3", developerId:"reportage", name:"Reportage Village",
    officialUrl:"https://reportageuae.com/projects/reportage-village",
    community:"Dubailand", type:"Townhouses", beds:"3–4BR TH",
    status:"Off Plan", handover:"Q4 2027", price:1550000,
    payment:"20/80", developer:"Reportage Properties", color:"#27AE60",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"rep-4", developerId:"reportage", name:"Taormina Village",
    officialUrl:"https://reportageuae.com/projects/taormina-village",
    community:"Dubailand", type:"Villas", beds:"3–4BR Villas",
    status:"Off Plan", handover:"Q4 2027", price:2860000,
    payment:"20/80", developer:"Reportage Properties", color:"#27AE60",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"rep-5", developerId:"reportage", name:"R. Hills by Reportage",
    officialUrl:"https://reportageuae.com/projects/r-hills",
    community:"Dubailand", type:"Townhouses", beds:"3–5BR TH",
    status:"Off Plan", handover:"Q4 2028", price:2590000,
    payment:"30/70", developer:"Reportage Properties", color:"#27AE60",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"rep-6", developerId:"reportage", name:"Verdana by Reportage",
    officialUrl:"https://reportageuae.com/projects/verdana",
    community:"Dubai Investment Park", type:"Townhouses", beds:"2–4BR TH",
    status:"Ready", handover:"Q4 2025", price:1250000,
    payment:"39/61", developer:"Reportage Properties", color:"#27AE60",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"rep-7", developerId:"reportage", name:"Verdana 4 by Reportage",
    officialUrl:"https://reportageuae.com/projects/verdana-4",
    community:"Dubai Investment Park", type:"Townhouses", beds:"2–4BR TH",
    status:"Off Plan", handover:"Q2 2028", price:900000,
    payment:"20/80", developer:"Reportage Properties", color:"#27AE60",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"rep-8", developerId:"reportage", name:"Alexis Tower by Reportage",
    officialUrl:"https://reportageuae.com/projects/alexis-tower",
    community:"Downtown Jebel Ali", type:"Apartments", beds:"Studio–2BR",
    status:"Ready", handover:"Delivered", price:514250,
    payment:"Ready", developer:"Reportage Properties", color:"#27AE60",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
];