/* ─── DXB ANALYTICS — BINGHATTI DATA ────────────────────────────────────────
   S28: Binghatti Full Intelligence Module
   Sources: Binghatti Official · Gulf News · Arabian Business · Zawya · The National
   Last verified: March 2026 — FY2025 AUDITED RESULTS
────────────────────────────────────────────────────────────────────────── */

export const binghattiIdentity = {
  id: "binghatti", name: "Binghatti", legalName: "Binghatti Holding Ltd",
  founded: 2008,  // Founded 2008 by Dr. Hussain BinGhatti — NOT 2012
  founder: "Dr. Hussain BinGhatti",
  chairman: "Muhammad BinGhatti",  // Chairman and brand face
  ceo: "Katralnada BinGhatti",     // CEO & MD per FY2025 financial results
  hq: "Business Bay, Dubai, UAE",
  type: "Private",   // PRIVATE company — NOT listed on ADX or any exchange
  listed: false,     // Company is NOT listed — only sukuk/bonds are listed
  exchange: null,    // No equity exchange listing
  sukukListed: "Nasdaq Dubai + London Stock Exchange (bonds only — not equity)",
  creditRating: "BB- (Fitch) · Ba3 (Moody's)",
  tier: "T1", segment: "Affordable → Ultra-Luxury",
  color: "#3B82F6", website: "https://www.binghatti.com",
  confidence: "VERIFIED",
  usp: "Dubai's #1 developer by units sold — fastest-growing RE company UAE",
  tagline: "Architecture is Art",
};

export const binghattiFinancialHistory = [
  { year:2021, revenue:1.8,  netProfit:0.4,  propertySales:5.2  },
  { year:2022, revenue:2.8,  netProfit:0.7,  propertySales:9.8  },
  { year:2023, revenue:3.4,  netProfit:1.0,  propertySales:14.5 },
  { year:2024, revenue:6.34, netProfit:1.83, propertySales:18.8 },
  { year:2025, revenue:12.43,netProfit:3.58, propertySales:26.0 },
];

export const binghattiLive = {
  propertySales:    26.0,   // AED Billion FY2025 (DLD rank #3 by value)
  propertySalesUSD: 7.1,
  revenue:          12.43,  // AED Billion FY2025 AUDITED (+96% YoY)
  netProfit:        3.58,   // AED Billion +96% YoY AUDITED
  ebitda:           4.40,   // AED Billion FY2025 AUDITED (+84% YoY) — NOT 5.2
  grossProfit:      5.43,   // AED Billion FY2025 AUDITED (+89% YoY) — NOT 5.0
  grossMargin:      44,     // % FY2025
  netMargin:        29,     // %
  unitsDelivered:   12500,  // since inception
  unitsSold2025:    17000,  // Dubai's #1 by units
  underConstruction:38000,
  revenueBacklog:   14000,  // AED million at Q3 2025
  portfolioGDV:     100000, // AED million — "nearly AED 100B"
  totalAssets:      24370,  // AED million FY2025 AUDITED — NOT 22000 (that was FY2024)
  cash:             8840,   // AED million FY2025 AUDITED — NOT 9000
  projects2025:     90,     // "over 90 projects" per FY2025 press release — NOT 80
  rank:             "#3 Dubai by Sales Value · #1 by Units Sold",
  latestReportLabel:"FY2025 Annual Results",
  latestReportDate: "February 2026",
  source:           "Binghatti Official FY2025 Audited Results · Gulf News · Arabian Business · Zawya",
  updatedAt:        "2026-03-27",
};

export const binghattiCommunities = [
  { id:"business-bay-bb",  name:"Business Bay",    type:"Urban Towers",          avgPpsf:2200, avgGrossYield:7.2, highlights:["Core market","Bugatti Residences","Binghatti Skyrise","Canal views"] },
  { id:"downtown-dubai",   name:"Downtown Dubai",  type:"Luxury Urban",          avgPpsf:3800, avgGrossYield:5.8, highlights:["Mercedes-Benz Places Downtown","Burj Khalifa adjacent","Iconic address"] },
  { id:"jvc-bing",         name:"JVC",             type:"Affordable-Mid",         avgPpsf:1100, avgGrossYield:8.2, highlights:["High ROI","Binghatti Home","Binghatti Crest","Top-selling community"] },
  { id:"meydan-city",      name:"Meydan / Nad Al Sheba", type:"Masterplan",      avgPpsf:2400, avgGrossYield:6.5, highlights:["Mercedes-Benz Places Binghatti City","13,386 units","12 towers","AED 30B GDV"] },
  { id:"dubai-science-park",name:"Dubai Science Park", type:"Innovation District",avgPpsf:1300, avgGrossYield:7.8, highlights:["Tech-hub adjacent","Mid-market","High occupancy"] },
  { id:"al-jaddaf",        name:"Al Jaddaf",       type:"Waterfront",            avgPpsf:1800, avgGrossYield:7.0, highlights:["Creek views","Jacob & Co partnership","Arts district"] },
];

export const binghattiProjects = [
  { id:"bing-1",  developerId:"binghatti", name:"Bugatti Residences",          officialUrl:"https://www.binghatti.com/bugatti-residences",       links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/bugatti-residences",bayut:"https://www.bayut.com/buildings/bugatti-residences/"}, community:"Business Bay",      district:"BB",   type:"Apartments", beds:"2–4BR+PH",   status:"Off Plan",  handover:"Q4 2025", price:19100000,sizeFrom:2000, sizeTo:15000,ppsf:9550, payment:"70/30",    construction:95, branded:true, brand:"Bugatti",         tier:"Ultra-Luxury", source:"Binghatti Official", confidence:"VERIFIED", unitBreakdown:[{type:"2BR",sqftFrom:2000,sqftTo:3000,priceFrom:19100000},{type:"3BR",sqftFrom:3500,sqftTo:5000,priceFrom:28650000},{type:"Sky Mansion",sqftFrom:8000,sqftTo:15000,priceFrom:57300000}] },
  { id:"bing-2",  developerId:"binghatti", name:"Mercedes-Benz Places",        officialUrl:"https://www.binghatti.com/mercedes-benz-places",     links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/mercedes-benz-places",bayut:"https://www.bayut.com/buildings/mercedes-benz-places/"}, community:"Downtown Dubai",    district:"DT",   type:"Apartments", beds:"2–5BR",      status:"Off Plan",  handover:"Q4 2026", price:8800000, sizeFrom:1500, sizeTo:8000, ppsf:5867, payment:"70/30",    construction:50, branded:true, brand:"Mercedes-Benz",   tier:"Ultra-Luxury", source:"Binghatti Official", confidence:"VERIFIED", unitBreakdown:[{type:"2BR",sqftFrom:1500,sqftTo:2000,priceFrom:8800000},{type:"3BR",sqftFrom:2500,sqftTo:3500,priceFrom:14667000},{type:"4BR PH",sqftFrom:5000,sqftTo:8000,priceFrom:29333000}] },
  { id:"bing-3",  developerId:"binghatti", name:"Burj Binghatti Jacob & Co",   officialUrl:"https://www.binghatti.com/jacob-and-co-residences",  links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/burj-binghatti-jacob-co",bayut:"https://www.bayut.com/buildings/burj-binghatti-jacob-co/"}, community:"Business Bay",      district:"BB",   type:"Apartments", beds:"2–3BR+PH",   status:"Off Plan",  handover:"Q2 2026", price:8200000, sizeFrom:1500, sizeTo:20000,ppsf:5467, payment:"80/20",    construction:90, branded:true, brand:"Jacob & Co",      tier:"Ultra-Luxury", source:"Binghatti Official", confidence:"VERIFIED", unitBreakdown:[{type:"2BR",sqftFrom:1500,sqftTo:2000,priceFrom:8200000},{type:"3BR",sqftFrom:2500,sqftTo:3500,priceFrom:13667000},{type:"PH",sqftFrom:10000,sqftTo:20000,priceFrom:54667000}] },
  { id:"bing-4",  developerId:"binghatti", name:"Binghatti Skyrise",           officialUrl:"https://www.binghatti.com/skyrise",                  links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-skyrise",bayut:"https://www.bayut.com/buildings/binghatti-skyrise/"}, community:"Business Bay",      district:"BB",   type:"Apartments", beds:"Studio–3BR", status:"Off Plan",  handover:"Q4 2026", price:975000,  sizeFrom:465,  sizeTo:2200, ppsf:2097, payment:"20/50/30", construction:40, branded:false, brand:"—",               tier:"Premium",      source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:465,sqftTo:600,priceFrom:975000},{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1463000},{type:"2BR",sqftFrom:1100,sqftTo:1400,priceFrom:2044000},{type:"3BR",sqftFrom:1800,sqftTo:2200,priceFrom:3317000}] },
  { id:"bing-5",  developerId:"binghatti", name:"Binghatti Aquarise",          officialUrl:"https://www.binghatti.com/aquarise",                 links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-aquarise",bayut:"https://www.bayut.com/buildings/binghatti-aquarise/"}, community:"Business Bay",      district:"BB",   type:"Apartments", beds:"Studio–4BR", status:"Off Plan",  handover:"Q4 2026", price:1100000, sizeFrom:400,  sizeTo:3000, ppsf:2750, payment:"20/50/30", construction:35, branded:false, brand:"—",               tier:"Premium",      source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:400,sqftTo:550,priceFrom:1100000},{type:"1BR",sqftFrom:700,sqftTo:950,priceFrom:1650000},{type:"2BR",sqftFrom:1100,sqftTo:1500,priceFrom:2750000},{type:"3BR",sqftFrom:1800,sqftTo:2500,priceFrom:4400000}] },
  { id:"bing-6",  developerId:"binghatti", name:"Binghatti Skyblade",          officialUrl:"https://www.binghatti.com/skyblade",                 links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-skyblade",bayut:"https://www.bayut.com/buildings/binghatti-skyblade/"}, community:"Downtown Dubai",    district:"DT",   type:"Apartments", beds:"Studio–3BR", status:"Off Plan",  handover:"Q1 2026", price:12586599,sizeFrom:800,  sizeTo:5000, ppsf:15733,payment:"10/50/40", construction:95, branded:false, brand:"—",               tier:"Ultra-Luxury", source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:800,sqftTo:1000,priceFrom:12586599},{type:"1BR",sqftFrom:1200,sqftTo:1500,priceFrom:18879899},{type:"2BR",sqftFrom:2000,sqftTo:3000,priceFrom:31466498}] },
  { id:"bing-7",  developerId:"binghatti", name:"Binghatti Hills",             officialUrl:"https://www.binghatti.com/binghatti-hills",          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-hills",bayut:"https://www.bayut.com/buildings/binghatti-hills/"}, community:"Dubai Science Park",district:"DSP",  type:"Apartments", beds:"Studio–3BR", status:"Off Plan",  handover:"Q2 2027", price:778000,  sizeFrom:350,  sizeTo:1800, ppsf:2223, payment:"70/30",    construction:45, branded:false, brand:"—",               tier:"Mid-Premium",  source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:350,sqftTo:500,priceFrom:778000},{type:"1BR",sqftFrom:650,sqftTo:850,priceFrom:1167000},{type:"2BR",sqftFrom:1000,sqftTo:1300,priceFrom:1778000},{type:"3BR",sqftFrom:1500,sqftTo:1800,priceFrom:2667000}] },
  { id:"bing-8",  developerId:"binghatti", name:"Binghatti Skyterraces",       officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-skyterraces",bayut:"https://www.bayut.com/buildings/binghatti-skyterraces/"}, community:"Motor City",        district:"DMC",  type:"Apartments", beds:"Studio–2BR", status:"Off Plan",  handover:"Q4 2026", price:774999,  sizeFrom:400,  sizeTo:1400, ppsf:1938, payment:"20/50/30", construction:55, branded:false, brand:"—",               tier:"Mid-Market",   source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:400,sqftTo:550,priceFrom:774999},{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1163000},{type:"2BR",sqftFrom:1100,sqftTo:1400,priceFrom:1550000}] },
  { id:"bing-9",  developerId:"binghatti", name:"Binghatti Hillcrest",         officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-hillcrest",bayut:"https://www.bayut.com/buildings/binghatti-hillcrest/"}, community:"Arjan",             district:"ARJ",  type:"Apartments", beds:"Studio–2BR", status:"Off Plan",  handover:"Q2 2027", price:799999,  sizeFrom:380,  sizeTo:1300, ppsf:2105, payment:"20/50/30", construction:40, branded:false, brand:"—",               tier:"Mid-Market",   source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:380,sqftTo:520,priceFrom:799999},{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1200000},{type:"2BR",sqftFrom:1000,sqftTo:1300,priceFrom:1600000}] },
  { id:"bing-10", developerId:"binghatti", name:"Binghatti Amberhall",         officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-amberhall",bayut:"https://www.bayut.com/buildings/binghatti-amberhall/"}, community:"JVC",               district:"JVC",  type:"Apartments", beds:"1–2BR",      status:"Off Plan",  handover:"Q2 2026", price:1110000, sizeFrom:600,  sizeTo:1400, ppsf:1850, payment:"20/50/30", construction:75, branded:false, brand:"—",               tier:"Mid-Premium",  source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"1BR",sqftFrom:600,sqftTo:800,priceFrom:1110000},{type:"2BR",sqftFrom:1000,sqftTo:1400,priceFrom:1850000}] },
  { id:"bing-11", developerId:"binghatti", name:"Binghatti Ruby",              officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-ruby",bayut:"https://www.bayut.com/buildings/binghatti-ruby/"}, community:"JVC",               district:"JVC",  type:"Apartments", beds:"Studio–3BR", status:"Off Plan",  handover:"Q1 2026", price:695000,  sizeFrom:350,  sizeTo:1600, ppsf:1986, payment:"20/50/30", construction:90, branded:false, brand:"—",               tier:"Mid-Market",   source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:350,sqftTo:500,priceFrom:695000},{type:"1BR",sqftFrom:650,sqftTo:850,priceFrom:1042500},{type:"2BR",sqftFrom:1000,sqftTo:1300,priceFrom:1390000},{type:"3BR",sqftFrom:1300,sqftTo:1600,priceFrom:1737500}] },
  { id:"bing-12", developerId:"binghatti", name:"Binghatti Hillside",          officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-hillside",bayut:"https://www.bayut.com/buildings/binghatti-hillside/"}, community:"Dubai Science Park",district:"DSP",  type:"Apartments", beds:"Studio–1BR", status:"Off Plan",  handover:"Q2 2026", price:1299999, sizeFrom:380,  sizeTo:850,  ppsf:3421, payment:"70/30",    construction:70, branded:false, brand:"—",               tier:"Mid-Premium",  source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:380,sqftTo:500,priceFrom:1299999},{type:"1BR",sqftFrom:700,sqftTo:850,priceFrom:1820000}] },
  { id:"bing-13", developerId:"binghatti", name:"Binghatti Cullinan",          officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-cullinan",bayut:"https://www.bayut.com/buildings/binghatti-cullinan/"}, community:"Al Jaddaf",         district:"JAD",  type:"Apartments", beds:"Studio–3BR", status:"Off Plan",  handover:"Q4 2026", price:800000,  sizeFrom:371,  sizeTo:1800, ppsf:2159, payment:"20/50/30", construction:60, branded:false, brand:"—",               tier:"Mid-Premium",  source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:371,sqftTo:500,priceFrom:800000},{type:"1BR",sqftFrom:650,sqftTo:850,priceFrom:1400000},{type:"2BR",sqftFrom:1000,sqftTo:1400,priceFrom:2160000},{type:"3BR",sqftFrom:1500,sqftTo:1800,priceFrom:3238000}] },
  { id:"bing-14", developerId:"binghatti", name:"Binghatti Phantom",           officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-phantom",bayut:"https://www.bayut.com/buildings/binghatti-phantom/"}, community:"JVC",               district:"JVC",  type:"Apartments", beds:"Studio–2BR", status:"Ready",     handover:"Q4 2025", price:1000000, sizeFrom:400,  sizeTo:1400, ppsf:2500, payment:"70/30",    construction:100,branded:false, brand:"—",               tier:"Mid-Premium",  source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:400,sqftTo:550,priceFrom:1000000},{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1750000},{type:"2BR",sqftFrom:1100,sqftTo:1400,priceFrom:2500000}] },
  { id:"bing-15", developerId:"binghatti", name:"Binghatti Amber",             officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-amber",bayut:"https://www.bayut.com/buildings/binghatti-amber/"}, community:"Al Jaddaf",         district:"JAD",  type:"Apartments", beds:"Studio–2BR", status:"Ready",     handover:"Delivered",price:600000,  sizeFrom:350,  sizeTo:1200, ppsf:1714, payment:"Ready",    construction:100,branded:false, brand:"—",               tier:"Mid-Market",   source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:350,sqftTo:500,priceFrom:600000},{type:"1BR",sqftFrom:650,sqftTo:850,priceFrom:1028000},{type:"2BR",sqftFrom:1000,sqftTo:1200,priceFrom:1714000}] },
  { id:"bing-16", developerId:"binghatti", name:"Binghatti Azure",             officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-azure",bayut:"https://www.bayut.com/buildings/binghatti-azure/"}, community:"JVC",               district:"JVC",  type:"Apartments", beds:"Studio–1BR", status:"Ready",     handover:"Delivered",price:500000,  sizeFrom:300,  sizeTo:900,  ppsf:1667, payment:"Ready",    construction:100,branded:false, brand:"—",               tier:"Mid-Market",   source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:300,sqftTo:450,priceFrom:500000},{type:"1BR",sqftFrom:650,sqftTo:900,priceFrom:1083000}] },
  { id:"bing-17", developerId:"binghatti", name:"Binghatti Skyhall",           officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-skyhall",bayut:"https://www.bayut.com/buildings/binghatti-skyhall/"}, community:"Business Bay",      district:"BB",   type:"Apartments", beds:"Studio–1BR", status:"Off Plan",  handover:"Q4 2027", price:1259600, sizeFrom:400,  sizeTo:900,  ppsf:3149, payment:"20/50/30", construction:20, branded:false, brand:"—",               tier:"Premium",      source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:400,sqftTo:550,priceFrom:1259600},{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:2204800}] },
  { id:"bing-18", developerId:"binghatti", name:"Binghatti Vintage",           officialUrl:"https://www.binghatti.com/vintage",                  links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-vintage",bayut:"https://www.bayut.com/buildings/binghatti-vintage/"}, community:"Majan",             district:"MAJ",  type:"Apartments", beds:"Studio–2BR", status:"Off Plan",  handover:"Q4 2026", price:679999,  sizeFrom:320,  sizeTo:1300, ppsf:2125, payment:"20/50/30", construction:60, branded:false, brand:"—",               tier:"Mid-Market",   source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:320,sqftTo:450,priceFrom:679999},{type:"1BR",sqftFrom:650,sqftTo:850,priceFrom:1445000},{type:"2BR",sqftFrom:1000,sqftTo:1300,priceFrom:1700000}] },
  { id:"bing-19", developerId:"binghatti", name:"Binghatti Skyflame",          officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-skyflame",bayut:"https://www.bayut.com/buildings/binghatti-skyflame/"}, community:"Majan",             district:"MAJ",  type:"Apartments", beds:"Studio–1BR", status:"Off Plan",  handover:"Q4 2026", price:705999,  sizeFrom:350,  sizeTo:900,  ppsf:2017, payment:"20/50/30", construction:55, branded:false, brand:"—",               tier:"Mid-Market",   source:"PropertyFinder",     confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:350,sqftTo:500,priceFrom:705999},{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1270000}] },
  { id:"bing-20", developerId:"binghatti", name:"Binghatti Onyx",              officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-onyx",bayut:"https://www.bayut.com/buildings/binghatti-onyx/"}, community:"Al Jaddaf",         district:"JAD",  type:"Apartments", beds:"Studio–2BR", status:"Off Plan",  handover:"Q3 2026", price:500000,  sizeFrom:300,  sizeTo:1200, ppsf:1667, payment:"60/40",    construction:70, branded:false, brand:"—",               tier:"Mid-Market",   source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:300,sqftTo:450,priceFrom:500000},{type:"1BR",sqftFrom:650,sqftTo:850,priceFrom:1083000},{type:"2BR",sqftFrom:1000,sqftTo:1200,priceFrom:1667000}] },
  { id:"bing-21", developerId:"binghatti", name:"One by Binghatti",            officialUrl:"https://www.binghatti.com/one",                      links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/one-by-binghatti",bayut:"https://www.bayut.com/buildings/one-by-binghatti/"}, community:"Business Bay",      district:"BB",   type:"Apartments", beds:"Studio–PH",  status:"Off Plan",  handover:"Q4 2026", price:1700000, sizeFrom:500,  sizeTo:10000,ppsf:3400, payment:"70/30",    construction:45, branded:false, brand:"—",               tier:"Luxury",       source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:500,sqftTo:700,priceFrom:1700000},{type:"1BR",sqftFrom:900,sqftTo:1200,priceFrom:3060000},{type:"Pool Villa",sqftFrom:3000,sqftTo:5000,priceFrom:10200000}] },
  { id:"bing-22", developerId:"binghatti", name:"Binghatti Apex",              officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-apex",bayut:"https://www.bayut.com/buildings/binghatti-apex/"}, community:"JVC",               district:"JVC",  type:"Apartments", beds:"Studio–2BR", status:"Off Plan",  handover:"Q4 2026", price:750000,  sizeFrom:350,  sizeTo:1400, ppsf:2143, payment:"20/50/30", construction:60, branded:false, brand:"—",               tier:"Mid-Market",   source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"Studio",sqftFrom:350,sqftTo:500,priceFrom:750000},{type:"1BR",sqftFrom:700,sqftTo:900,priceFrom:1500000},{type:"2BR",sqftFrom:1100,sqftTo:1400,priceFrom:2143000}] },
  { id:"bing-23", developerId:"binghatti", name:"Binghatti Twilight",          officialUrl:"https://www.binghatti.com",                          links:{pf:"https://www.propertyfinder.ae/en/new-projects/binghatti-developers/binghatti-twilight",bayut:"https://www.bayut.com/buildings/binghatti-twilight/"}, community:"Al Jaddaf",         district:"JAD",  type:"Apartments", beds:"1–3BR",      status:"Off Plan",  handover:"Q4 2027", price:1300000, sizeFrom:600,  sizeTo:2000, ppsf:2167, payment:"70/30",    construction:15, branded:false, brand:"—",               tier:"Mid-Premium",  source:"Bayut",              confidence:"VERIFIED", unitBreakdown:[{type:"1BR",sqftFrom:600,sqftTo:800,priceFrom:1300000},{type:"2BR",sqftFrom:1000,sqftTo:1400,priceFrom:2167000},{type:"3BR",sqftFrom:1500,sqftTo:2000,priceFrom:3250000}] },
];

export const binghattiRisks = [
  { factor:"Rapid Scale — 17,000 Units/Year Pace",     level:4, likelihood:3, impact:4, score:48, mitigation:"Vertically integrated. Strong cash AED 8.84B. Credit ratings BB- (Fitch) · Ba3 (Moody's) · RERA compliant.", assessment:"MODERATE", color:"#F59E0B" },
  { factor:"Affordable Segment Margin Pressure",        level:3, likelihood:3, impact:3, score:27, mitigation:"Portfolio diversification — ultra-luxury (Bugatti, Mercedes) offsets affordable margin compression.", assessment:"MODERATE", color:"#D4A843" },
  { factor:"Construction Delivery Risk (38K units)",    level:4, likelihood:3, impact:4, score:48, mitigation:"Track record 12,500+ delivered. 13 new projects FY2025 all on schedule. In-country contractor network.", assessment:"MODERATE", color:"#F59E0B" },
  { factor:"Branded Partnership Risk",                  level:2, likelihood:2, impact:4, score:16, mitigation:"Bugatti, Mercedes-Benz contracts signed. AED 550M penthouse sale validates ultra-luxury demand.", assessment:"LOW",      color:"#10B981" },
  { factor:"Market Concentration — Dubai Only",         level:3, likelihood:2, impact:3, score:18, mitigation:"80+ projects diversify across JVC, Business Bay, Downtown, Meydan, Science Park.", assessment:"LOW",      color:"#10B981" },
  { factor:"Currency Risk (AED Peg)",                   level:1, likelihood:1, impact:2, score:2,  mitigation:"USD peg stable.", assessment:"VERY LOW", color:"#10B981" },
  { factor:"Regulatory Risk",                           level:1, likelihood:1, impact:2, score:2,  mitigation:"Privately held. Fully RERA compliant. DIFC-registered LLC.", assessment:"VERY LOW", color:"#10B981" },
];

export const binghattiSegments = [
  { name:"Ultra-Luxury (Bugatti/MB)", revenue:4.8, growth:"+145%", color:"#3B82F6" },
  { name:"Premium (Business Bay)",    revenue:4.2, growth:"+82%",  color:"#8B5CF6" },
  { name:"Mid-Market (JVC/DSP)",      revenue:3.4, growth:"+65%",  color:"#00BFA5" },
];

export const binghattiRadar = [
  { metric:"Unit Volume",       binghatti:100,emaar:72, damac:85, market:70 },
  { metric:"Revenue Growth",    binghatti:98, emaar:65, damac:78, market:60 },
  { metric:"Brand Innovation",  binghatti:92, emaar:75, damac:88, market:65 },
  { metric:"Sales Speed",       binghatti:95, emaar:80, damac:90, market:70 },
  { metric:"Margin Quality",    binghatti:75, emaar:92, damac:78, market:70 },
  { metric:"Delivery Record",   binghatti:80, emaar:92, damac:82, market:72 },
  { metric:"Financial Strength",binghatti:72, emaar:95, damac:75, market:65 },
  { metric:"Community Scale",   binghatti:55, emaar:88, damac:90, market:68 },
];

export const binghattiYields = [
  { community:"JVC",          unit:"Apartments",  gross:8.2, net:6.2, avgRent:49200,  avgPrice:600000,  demand:"Very High" },
  { community:"Business Bay", unit:"Apartments",  gross:7.2, net:5.4, avgRent:64800,  avgPrice:900000,  demand:"Very High" },
  { community:"Downtown",     unit:"Apartments",  gross:5.8, net:4.4, avgRent:261000, avgPrice:4500000, demand:"High" },
  { community:"Dubai Sci Pk", unit:"Apartments",  gross:7.8, net:5.9, avgRent:54600,  avgPrice:700000,  demand:"High" },
];

export const binghattiMegaProjects = [
  { name:"Mercedes-Benz Places Binghatti City", scale:"AED 30B GDV", units:"13,386", sqft:"10M sqft", timeline:"Launched Jan 2026 · 2029 delivery", status:"Off Plan", record:"World's first Mercedes-Benz branded city" },
  { name:"Bugatti Residences",                  scale:"AED 2B+ GDV", units:"182",    sqft:"Business Bay", timeline:"2023–Q4 2026", status:"Under Construction", record:"AED 550M penthouse — most expensive Middle East" },
  { name:"Binghatti Skyrise",                   scale:"AED 8B GDV",  units:"3,333",  sqft:"Business Bay", timeline:"2024–Q4 2026", status:"Under Construction", record:"3,333 units single project" },
];

export default { identity:binghattiIdentity, live:binghattiLive, financialHistory:binghattiFinancialHistory, communities:binghattiCommunities, projects:binghattiProjects, risks:binghattiRisks, segments:binghattiSegments, radar:binghattiRadar, megaProjects:binghattiMegaProjects, yields:binghattiYields };
