// Beyond Developments — Verified from official site + DLD Q1 2026
// Source: https://beyonddevelopments.ae
// Projects: 8 | DLD Q1 2026 transactions: 980

export const beyondIdentity = {
  id: "beyond", name: "Beyond Developments", legalName: "Beyond Developments LLC",
  founded: 2024, website: "https://beyonddevelopments.ae", color: "#1ABC9C",
  dld: { transactions: 980, source: "DLD Q1 2026" },
  confidence: "VERIFIED",
};

export const beyondProjects = [
  { id:"byd-1", developerId:"beyond", name:"Hado by Beyond",
    officialUrl:"https://beyonddevelopments.ae/our-portfolio/hado/",
    community:"Dubai Islands", type:"Apartments", beds:"1–4BR+Duplex",
    status:"Off Plan", handover:"Q3 2029", price:2300000,
    payment:"50/50", developer:"Beyond Developments", color:"#1ABC9C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"byd-2", developerId:"beyond", name:"Kanyon by Beyond",
    officialUrl:"https://beyonddevelopments.ae/our-portfolio/kanyon/",
    community:"Dubai Maritime City", type:"Apartments", beds:"1–4BR+Duplex",
    status:"Off Plan", handover:"Q2 2029", price:8000000,
    payment:"50/50", developer:"Beyond Developments", color:"#1ABC9C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"byd-3", developerId:"beyond", name:"Soulever by Beyond",
    officialUrl:"https://beyonddevelopments.ae/our-portfolio/soulever/",
    community:"Dubai Maritime City", type:"Apartments", beds:"1–3BR+Duplex+PH",
    status:"Off Plan", handover:"Q4 2028", price:5500000,
    payment:"50/50", developer:"Beyond Developments", color:"#1ABC9C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"byd-4", developerId:"beyond", name:"Passo by Beyond",
    officialUrl:"https://beyonddevelopments.ae/our-portfolio/passo/",
    community:"Palm Jumeirah", type:"Apartments", beds:"1–6BR+PH",
    status:"Off Plan", handover:"Q4 2029", price:6000000,
    payment:"50/50", developer:"Beyond Developments", color:"#1ABC9C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"byd-5", developerId:"beyond", name:"Talea by Beyond",
    officialUrl:"https://beyonddevelopments.ae/our-portfolio/talea/",
    community:"Dubai Maritime City", type:"Apartments", beds:"1–4BR",
    status:"Off Plan", handover:"Q1 2029", price:2200000,
    payment:"50/50", developer:"Beyond Developments", color:"#1ABC9C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"byd-6", developerId:"beyond", name:"Sensia by Beyond",
    officialUrl:"https://beyonddevelopments.ae/our-portfolio/sensia/",
    community:"Dubai Maritime City", type:"Apartments", beds:"1–3BR+Garden Duplex+PH",
    status:"Off Plan", handover:"Q1 2029", price:2500000,
    payment:"50/50", developer:"Beyond Developments", color:"#1ABC9C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"byd-7", developerId:"beyond", name:"Orise by Beyond",
    officialUrl:"https://beyonddevelopments.ae/our-portfolio/orise/",
    community:"Dubai Maritime City", type:"Apartments", beds:"1–4BR+Chalet",
    status:"Off Plan", handover:"Q4 2027", price:2400000,
    payment:"50/50", developer:"Beyond Developments", color:"#1ABC9C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
  { id:"byd-8", developerId:"beyond", name:"The Mural by Beyond",
    officialUrl:"https://beyonddevelopments.ae/our-portfolio/the-mural/",
    community:"Dubai Maritime City", type:"Apartments", beds:"1–4BR+Duplex+PH",
    status:"Off Plan", handover:"Q4 2027", price:3000000,
    payment:"50/50", developer:"Beyond Developments", color:"#1ABC9C",
    source:"Official + Bayut", confidence:"VERIFIED", dldVerified:true },
];