/* ─── DXB ANALYTICS — MASTER DATA FILE ─── */
/* Source: Emaar THE BEAST Excel + DLD + DXBinteract + Yahoo Finance */

export const T = {
  bg: "#04090F", surface: "#0A1628", surfaceAlt: "#0E1D35", card: "#0D1B30", cardHover: "#112240",
  gold: "#D4A843", goldLight: "#E8C96A", goldGlow: "rgba(212,168,67,0.15)", goldMuted: "rgba(212,168,67,0.08)",
  teal: "#00BFA5", navy: "#0B1F3F", white: "#FFFFFF",
  textPrimary: "#E2E8F0", textSecondary: "#94A3B8", textMuted: "#64748B",
  border: "rgba(212,168,67,0.12)", borderHover: "rgba(212,168,67,0.3)",
  red: "#EF4444", green: "#10B981", blue: "#3B82F6", purple: "#8B5CF6",
  orange: "#F59E0B", cyan: "#06B6D4",
};

/* ─── 48 EMAAR PROJECTS (from Excel) ─── */
export const emaarProjects = [
  { id:1, name:"The Golf Residence", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Under Construction", handover:"Q2 2026", price:1750000, sizeFrom:750, sizeTo:2200, ppsf:2333, payment:"20/30/50", construction:80, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:2, name:"Hills Park", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Under Construction", handover:"Q2 2026", price:1210000, sizeFrom:650, sizeTo:1800, ppsf:1862, payment:"80/20", construction:75, branded:false, brand:"—", tier:"Mid-Market" },
  { id:3, name:"Golf Grand", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Under Construction", handover:"Q1 2027", price:1529388, sizeFrom:700, sizeTo:2100, ppsf:2185, payment:"10/80/10", construction:96, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:4, name:"Parkside Views", community:"Dubai Hills Estate", district:"DHE", type:"Apts & TH", beds:"1-3", status:"Under Construction", handover:"Q3 2027", price:2756888, sizeFrom:900, sizeTo:2800, ppsf:3063, payment:"10/80/10", construction:74, branded:false, brand:"—", tier:"Premium" },
  { id:5, name:"Greenside Residence", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Under Construction", handover:"Q3 2027", price:1540000, sizeFrom:700, sizeTo:2000, ppsf:2200, payment:"10/80/10", construction:61, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:6, name:"Club Drive", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Under Construction", handover:"Q1 2028", price:1626566, sizeFrom:726, sizeTo:2622, ppsf:2240, payment:"10/90", construction:55, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:7, name:"Golf Hillside", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Under Construction", handover:"Q4 2028", price:2816888, sizeFrom:741, sizeTo:2322, ppsf:3801, payment:"80/20", construction:37, branded:false, brand:"—", tier:"Premium" },
  { id:8, name:"Park Lane", community:"Dubai Hills Estate", district:"DHE", type:"Apts & TH", beds:"1-3", status:"Under Construction", handover:"Q4 2028", price:1480000, sizeFrom:700, sizeTo:2200, ppsf:2114, payment:"10/70/20", construction:33, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:9, name:"Palace Residences Hillside", community:"Dubai Hills Estate", district:"DHE", type:"Apts & TH", beds:"1-3", status:"Under Construction", handover:"Q2 2028", price:1760888, sizeFrom:750, sizeTo:2500, ppsf:2348, payment:"80/20", construction:17, branded:true, brand:"Palace", tier:"Luxury Branded" },
  { id:10, name:"Greencrest", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q2 2029", price:1743888, sizeFrom:774, sizeTo:1928, ppsf:2096, payment:"80/20", construction:10, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:11, name:"Vida Residences Hillside", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q2 2029", price:1800000, sizeFrom:700, sizeTo:2200, ppsf:2571, payment:"80/20", construction:8, branded:true, brand:"Vida", tier:"Luxury Branded" },
  { id:12, name:"Parkwood", community:"Dubai Hills Estate", district:"DHE", type:"Apts & TH", beds:"1-3", status:"Off-Plan", handover:"Q1 2029", price:1770000, sizeFrom:750, sizeTo:2400, ppsf:2360, payment:"80/20", construction:5, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:13, name:"Hillsedge", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q1 2029", price:1840000, sizeFrom:700, sizeTo:2000, ppsf:2629, payment:"80/20", construction:5, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:14, name:"Club Place", community:"Dubai Hills Estate", district:"DHE", type:"Apts & Duplex", beds:"1-3", status:"Off-Plan", handover:"Q4 2028", price:1450000, sizeFrom:700, sizeTo:2200, ppsf:2071, payment:"80/20", construction:10, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:15, name:"Rosehill", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q2 2029", price:1600888, sizeFrom:754, sizeTo:1848, ppsf:2123, payment:"80/20", construction:5, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:16, name:"Parkland", community:"Dubai Hills Estate", district:"DHE", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q4 2028", price:1500000, sizeFrom:700, sizeTo:2200, ppsf:2143, payment:"80/20", construction:8, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:17, name:"The Cove II", community:"Dubai Creek Harbour", district:"DCH", type:"Apts & TH", beds:"1-4", status:"Under Construction", handover:"Q4 2026", price:1669000, sizeFrom:650, sizeTo:2800, ppsf:2568, payment:"10/70/20", construction:87, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:18, name:"Creek Waters", community:"Dubai Creek Harbour", district:"DCH", type:"Apts & TH", beds:"1-4", status:"Under Construction", handover:"Q3 2027", price:1750000, sizeFrom:700, sizeTo:2600, ppsf:2500, payment:"10/80/10", construction:62, branded:false, brand:"—", tier:"Premium" },
  { id:19, name:"Creek Waters 2", community:"Dubai Creek Harbour", district:"DCH", type:"Apts & TH", beds:"1-4", status:"Under Construction", handover:"Q4 2027", price:1938110, sizeFrom:700, sizeTo:2800, ppsf:2769, payment:"10/80/10", construction:63, branded:false, brand:"—", tier:"Premium" },
  { id:20, name:"Oria", community:"Dubai Creek Harbour", district:"DCH", type:"Apartments", beds:"1-3", status:"Under Construction", handover:"Q3 2028", price:1814888, sizeFrom:700, sizeTo:2200, ppsf:2593, payment:"10/80/10", construction:49, branded:false, brand:"—", tier:"Premium" },
  { id:21, name:"Albero", community:"Dubai Creek Harbour", district:"DCH", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q4 2028", price:1810000, sizeFrom:700, sizeTo:2200, ppsf:2586, payment:"80/20", construction:10, branded:false, brand:"—", tier:"Premium" },
  { id:22, name:"Montiva by Vida", community:"Dubai Creek Harbour", district:"DCH", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q3 2029", price:1910000, sizeFrom:755, sizeTo:1911, ppsf:2530, payment:"80/20", construction:5, branded:true, brand:"Vida", tier:"Luxury Branded" },
  { id:23, name:"Silva", community:"Dubai Creek Harbour", district:"DCH", type:"Apts & TH", beds:"1-3", status:"Off-Plan", handover:"Q3 2029", price:1790888, sizeFrom:700, sizeTo:2200, ppsf:2558, payment:"80/20", construction:3, branded:false, brand:"—", tier:"Premium" },
  { id:24, name:"Creek Bay", community:"Dubai Creek Harbour", district:"DCH", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q2 2030", price:1800000, sizeFrom:735, sizeTo:1851, ppsf:2449, payment:"80/20", construction:0, branded:false, brand:"—", tier:"Premium" },
  { id:25, name:"Creek Haven", community:"Dubai Creek Harbour", district:"DCH", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q1 2030", price:1951888, sizeFrom:700, sizeTo:2200, ppsf:2788, payment:"80/20", construction:0, branded:false, brand:"—", tier:"Premium" },
  { id:26, name:"Lyvia by Palace", community:"Dubai Creek Harbour", district:"DCH", type:"Apts & TH", beds:"1-3", status:"Off-Plan", handover:"Q3 2029", price:1980000, sizeFrom:755, sizeTo:3245, ppsf:2622, payment:"80/20", construction:0, branded:true, brand:"Palace", tier:"Ultra-Lux Branded" },
  { id:27, name:"Altan", community:"Dubai Creek Harbour", district:"DCH", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q3 2029", price:1813888, sizeFrom:700, sizeTo:2200, ppsf:2591, payment:"80/20", construction:5, branded:false, brand:"—", tier:"Premium" },
  { id:28, name:"Address The Bay", community:"Emaar Beachfront", district:"EBF", type:"Apts & PH", beds:"1-4", status:"Under Construction", handover:"Q4 2026", price:3500000, sizeFrom:800, sizeTo:4500, ppsf:4375, payment:"80/20", construction:70, branded:true, brand:"Address", tier:"Ultra-Lux Branded" },
  { id:29, name:"Beachgate by Address", community:"Emaar Beachfront", district:"EBF", type:"Apts, TH, PH", beds:"1-4", status:"Under Construction", handover:"Q4 2026", price:3200000, sizeFrom:800, sizeTo:4000, ppsf:4000, payment:"80/20", construction:70, branded:true, brand:"Address", tier:"Ultra-Lux Branded" },
  { id:30, name:"Seapoint", community:"Emaar Beachfront", district:"EBF", type:"Apts & Villas", beds:"1-4", status:"Under Construction", handover:"Q2 2028", price:3000000, sizeFrom:750, sizeTo:3500, ppsf:4000, payment:"80/20", construction:45, branded:false, brand:"—", tier:"Luxury" },
  { id:31, name:"Bayview", community:"Emaar Beachfront", district:"EBF", type:"Apartments", beds:"1-4", status:"Under Construction", handover:"Q3 2028", price:3000000, sizeFrom:750, sizeTo:3500, ppsf:4000, payment:"80/20", construction:40, branded:true, brand:"Address", tier:"Ultra-Lux Branded" },
  { id:32, name:"Bristol Luxury Residences", community:"Emaar Beachfront", district:"EBF", type:"Branded Res.", beds:"1-4", status:"Off-Plan", handover:"Q3 2029", price:3500000, sizeFrom:800, sizeTo:4000, ppsf:4375, payment:"80/20", construction:15, branded:true, brand:"Bristol", tier:"Ultra-Lux Branded" },
  { id:33, name:"Golf Verge", community:"Emaar South", district:"ES", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q2 2029", price:1200000, sizeFrom:650, sizeTo:1800, ppsf:1846, payment:"10/70/20", construction:5, branded:false, brand:"—", tier:"Affordable" },
  { id:34, name:"Golf Meadow", community:"Emaar South", district:"ES", type:"Apts & TH", beds:"1-3", status:"Off-Plan", handover:"Q3 2029", price:3045888, sizeFrom:800, sizeTo:2500, ppsf:3807, payment:"10/70/20", construction:5, branded:false, brand:"—", tier:"Mid-Premium" },
  { id:35, name:"Terra Gardens", community:"Expo Living", district:"EL", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q4 2029", price:1550000, sizeFrom:742, sizeTo:1676, ppsf:2089, payment:"80/20", construction:0, branded:false, brand:"—", tier:"Affordable" },
  { id:36, name:"Farm Gardens", community:"The Valley", district:"TV", type:"Villas", beds:"4-5", status:"Under Construction", handover:"Q3 2026", price:7300000, sizeFrom:4950, sizeTo:10004, ppsf:1475, payment:"10/70/20", construction:76, branded:false, brand:"—", tier:"Ultra-Luxury" },
  { id:37, name:"Elora", community:"The Valley", district:"TV", type:"Townhouses", beds:"3-4", status:"Off-Plan", handover:"Q4 2026", price:1600000, sizeFrom:2111, sizeTo:2608, ppsf:758, payment:"80/20", construction:30, branded:false, brand:"—", tier:"Mid-Market" },
  { id:38, name:"Selvara", community:"Grand Polo Club", district:"GPC", type:"Villas", beds:"3-5", status:"Off-Plan", handover:"Q2 2029", price:5670000, sizeFrom:2948, sizeTo:5115, ppsf:1923, payment:"80/20", construction:10, branded:false, brand:"—", tier:"Ultra-Luxury" },
  { id:39, name:"Equestra", community:"Grand Polo Club", district:"GPC", type:"Townhouses", beds:"3-4", status:"Off-Plan", handover:"Q2 2029", price:3700000, sizeFrom:2176, sizeTo:2176, ppsf:1700, payment:"80/20", construction:5, branded:false, brand:"—", tier:"Luxury" },
  { id:40, name:"Equiterra", community:"Grand Polo Club", district:"GPC", type:"Townhouses", beds:"3-4", status:"Off-Plan", handover:"Q2 2029", price:3700000, sizeFrom:2176, sizeTo:2176, ppsf:1700, payment:"80/20", construction:5, branded:false, brand:"—", tier:"Luxury" },
  { id:41, name:"Chevalia Estate 2", community:"Grand Polo Club", district:"GPC", type:"Villas", beds:"4-5", status:"Off-Plan", handover:"Q2 2029", price:7880000, sizeFrom:4168, sizeTo:8635, ppsf:1890, payment:"80/20", construction:3, branded:false, brand:"—", tier:"Ultra-Luxury" },
  { id:42, name:"Selvara 3", community:"Grand Polo Club", district:"GPC", type:"Villas", beds:"4", status:"Off-Plan", handover:"Q2 2029", price:6490000, sizeFrom:3682, sizeTo:3851, ppsf:1706, payment:"80/20", construction:5, branded:false, brand:"—", tier:"Ultra-Luxury" },
  { id:43, name:"Selvara 4", community:"Grand Polo Club", district:"GPC", type:"Villas", beds:"4", status:"Off-Plan", handover:"Q2 2029", price:6200000, sizeFrom:3682, sizeTo:3851, ppsf:1631, payment:"80/20", construction:3, branded:false, brand:"—", tier:"Ultra-Luxury" },
  { id:44, name:"Aurea", community:"Rashid Yachts & Marina", district:"RYM", type:"Apartments", beds:"1-3", status:"Off-Plan", handover:"Q4 2029", price:2100000, sizeFrom:700, sizeTo:2500, ppsf:3000, payment:"10/70/20", construction:0, branded:false, brand:"—", tier:"Premium" },
  { id:45, name:"Baystar by Vida", community:"Rashid Yachts & Marina", district:"RYM", type:"Apartments", beds:"1-4", status:"Off-Plan", handover:"Q4 2029", price:2100000, sizeFrom:700, sizeTo:3000, ppsf:3000, payment:"80/20", construction:5, branded:true, brand:"Vida", tier:"Luxury Branded" },
  { id:46, name:"Marèva 2", community:"The Oasis", district:"TO", type:"Villas", beds:"4-6", status:"Off-Plan", handover:"Q4 2029", price:13830000, sizeFrom:7200, sizeTo:12700, ppsf:1921, payment:"80/20", construction:5, branded:false, brand:"—", tier:"Ultra-Luxury" },
  { id:47, name:"Avarra by Palace", community:"Business Bay", district:"BB", type:"Apts & PH", beds:"1-4", status:"Off-Plan", handover:"Q2 2031", price:2700000, sizeFrom:789, sizeTo:4226, ppsf:3422, payment:"90/10", construction:0, branded:true, brand:"Palace", tier:"Ultra-Lux Branded" },
  { id:48, name:"Greencrest Heights", community:"The Heights CW", district:"TH", type:"Townhouses", beds:"3-4", status:"Off-Plan", handover:"Q4 2029", price:2500000, sizeFrom:2200, sizeTo:3000, ppsf:1136, payment:"80/20", construction:3, branded:false, brand:"—", tier:"Mid-Premium" },
];

/* ─── ENHANCED FINANCIALS (from Excel PBI_Financials) ─── */
export const emaarFinancials = [
  { year:"2020", revenue:14.9, grossProfit:4.8, ebitda:6.2, netProfit:2.7, netProfitAttr:2.1, propertySales:14, backlog:28, recurringRev:5.3, intlSales:0.6, mallRev:3.2, hotelRev:2.1, mallOccupancy:93, dubaiMallFootfall:65, dividend:0.15, eps:0.24, unitsDelivered:59000, newLaunches:15, revenueUSD:4.1, netProfitUSD:0.6, gm:32.2, em:41.6, nm:14.1 },
  { year:"2021", revenue:27.9, grossProfit:11.6, ebitda:8.5, netProfit:6.6, netProfitAttr:5.3, propertySales:23.9, backlog:32, recurringRev:5.8, intlSales:0.8, mallRev:3.5, hotelRev:2.3, mallOccupancy:95, dubaiMallFootfall:80, dividend:0.25, eps:0.60, unitsDelivered:62000, newLaunches:20, revenueUSD:7.6, netProfitUSD:1.4, gm:41.6, em:30.5, nm:19.0 },
  { year:"2022", revenue:24.9, grossProfit:12.6, ebitda:9.8, netProfit:8.1, netProfitAttr:6.8, propertySales:30.7, backlog:41.5, recurringRev:7.5, intlSales:1.2, mallRev:4.2, hotelRev:3.3, mallOccupancy:96, dubaiMallFootfall:88, dividend:0.35, eps:0.77, unitsDelivered:65000, newLaunches:22, revenueUSD:6.8, netProfitUSD:1.9, gm:50.6, em:39.4, nm:27.3 },
  { year:"2023", revenue:26.7, grossProfit:16.9, ebitda:16.0, netProfit:15.1, netProfitAttr:11.6, propertySales:40.3, backlog:71.8, recurringRev:8.6, intlSales:2.9, mallRev:5.8, hotelRev:2.8, mallOccupancy:97, dubaiMallFootfall:105, dividend:0.50, eps:1.32, unitsDelivered:70000, newLaunches:27, revenueUSD:7.3, netProfitUSD:3.2, gm:63.3, em:59.9, nm:43.4 },
  { year:"2024", revenue:35.5, grossProfit:20.4, ebitda:19.3, netProfit:18.9, netProfitAttr:13.5, propertySales:69.5, backlog:111.5, recurringRev:9.3, intlSales:4.1, mallRev:5.6, hotelRev:3.7, mallOccupancy:98.5, dubaiMallFootfall:111, dividend:1.00, eps:1.53, unitsDelivered:75000, newLaunches:62, revenueUSD:9.7, netProfitUSD:3.7, gm:57.5, em:54.4, nm:38.0 },
  { year:"2025", revenue:49.6, grossProfit:28.5, ebitda:25.6, netProfit:25.7, netProfitAttr:17.6, propertySales:80.4, backlog:155, recurringRev:10.5, intlSales:9.3, mallRev:6.3, hotelRev:4.2, mallOccupancy:98, dubaiMallFootfall:118, dividend:1.00, eps:2.00, unitsDelivered:125600, newLaunches:48, revenueUSD:13.5, netProfitUSD:4.8, gm:57.5, em:51.6, nm:35.5, landBank:618 },
];

/* ─── COMMUNITIES (from Excel PBI_Communities) ─── */
export const emaarCommunities = [
  { district:"DHE", name:"Dubai Hills Estate", acres:2700, avgPpsf:2400, avgYield:5.0, projects:16, buyer:"Families, professionals", strengths:"Golf, schools, mall, parks" },
  { district:"DCH", name:"Dubai Creek Harbour", acres:2500, avgPpsf:2700, avgYield:4.8, projects:11, buyer:"Investors, expats", strengths:"Dubai Square; Creek Tower; waterfront" },
  { district:"EBF", name:"Emaar Beachfront", acres:250, avgPpsf:4150, avgYield:3.7, projects:5, buyer:"Luxury expats, UHNW", strengths:"Beach access; Address/Bristol brands" },
  { district:"ES", name:"Emaar South", acres:7000, avgPpsf:2800, avgYield:4.9, projects:2, buyer:"Value investors", strengths:"Expo legacy; golf; affordable entry" },
  { district:"EL", name:"Expo Living", acres:3000, avgPpsf:2170, avgYield:7.0, projects:1, buyer:"Value seekers", strengths:"Expo City legacy; metro-connected; affordable" },
  { district:"TV", name:"The Valley", acres:4000, avgPpsf:1100, avgYield:5.3, projects:2, buyer:"End-user families", strengths:"Townhouses & villas; community" },
  { district:"GPC", name:"Grand Polo Club", acres:3500, avgPpsf:1770, avgYield:5.5, projects:6, buyer:"UHNW, polo", strengths:"First polo community; equestrian; ultra-luxury" },
  { district:"RYM", name:"Rashid Yachts & Marina", acres:1000, avgPpsf:3000, avgYield:4.0, projects:2, buyer:"Maritime lifestyle", strengths:"Yacht marina; Vida" },
  { district:"TO", name:"The Oasis", acres:2300, avgPpsf:1921, avgYield:4.0, projects:1, buyer:"UHNW families", strengths:"100M sqft; 9,000 villas; lakes; AED 72B" },
  { district:"BB", name:"Business Bay", acres:600, avgPpsf:3422, avgYield:7.5, projects:1, buyer:"Executives", strengths:"CBD; Dubai Canal; Palace branded; Downtown" },
  { district:"TH", name:"The Heights CW", acres:800, avgPpsf:1136, avgYield:5.5, projects:1, buyer:"Wellness families", strengths:"Country club; near Oasis; wellness amenities" },
];

/* ─── ENHANCED YIELDS (from Excel PBI_RentalYields) ─── */
export const emaarYields = [
  { community:"Dubai Hills Estate", unit:"1BR Apt", rent:75000, price:1529388, gross:4.9, net:4.17, demand:"Very High", tenant:"Professionals, couples", visa:"Yes (≥2M)" },
  { community:"Dubai Hills Estate", unit:"2BR Apt", rent:110000, price:2200000, gross:5.0, net:4.25, demand:"Very High", tenant:"Families, professionals", visa:"Yes (≥2M)" },
  { community:"Dubai Hills Estate", unit:"3BR Apt", rent:160000, price:3500000, gross:4.57, net:3.89, demand:"High", tenant:"HNW families", visa:"Yes (≥2M)" },
  { community:"Dubai Creek Harbour", unit:"1BR Apt", rent:80000, price:1750000, gross:4.57, net:3.89, demand:"High", tenant:"Young professionals", visa:"Yes (≥2M)" },
  { community:"Dubai Creek Harbour", unit:"2BR Apt", rent:120000, price:2500000, gross:4.8, net:4.08, demand:"High", tenant:"Expat families", visa:"Yes (≥2M)" },
  { community:"Dubai Creek Harbour", unit:"3BR Apt", rent:170000, price:3500000, gross:4.86, net:4.13, demand:"Moderate-High", tenant:"HNW tenants", visa:"Yes (≥2M)" },
  { community:"Emaar Beachfront", unit:"1BR Apt", rent:120000, price:3200000, gross:3.75, net:3.19, demand:"Very High", tenant:"Luxury expats", visa:"Yes (≥2M)" },
  { community:"Emaar Beachfront", unit:"2BR Apt", rent:180000, price:5000000, gross:3.6, net:3.06, demand:"High", tenant:"UHNW tenants", visa:"Yes (≥2M)" },
  { community:"Emaar South", unit:"1BR Apt", rent:60000, price:1200000, gross:5.0, net:4.25, demand:"Growing", tenant:"Airport staff, young prof.", visa:"Yes (≥2M)" },
  { community:"Emaar South", unit:"2BR Apt", rent:85000, price:1800000, gross:4.72, net:4.01, demand:"Growing", tenant:"Families, value seekers", visa:"Yes (≥2M)" },
  { community:"The Valley", unit:"3BR TH", rent:95000, price:1600000, gross:5.94, net:5.05, demand:"High", tenant:"Family end-users", visa:"Yes (≥2M)" },
  { community:"The Valley", unit:"4BR Villa", rent:140000, price:3000000, gross:4.67, net:3.97, demand:"High", tenant:"Large families", visa:"Yes (≥2M)" },
  { community:"Rashid Marina", unit:"1BR Apt", rent:85000, price:2100000, gross:4.05, net:3.44, demand:"Moderate", tenant:"Maritime lifestyle", visa:"Yes (≥2M)" },
  { community:"Downtown Dubai", unit:"1BR Apt", rent:95000, price:2500000, gross:3.8, net:3.23, demand:"Very High", tenant:"Tourists, executives", visa:"Yes (≥2M)" },
  { community:"Downtown Dubai", unit:"2BR Apt", rent:145000, price:4000000, gross:3.62, net:3.08, demand:"Very High", tenant:"UHNW, corp. housing", visa:"Yes (≥2M)" },
];

/* ─── TOP 10 DEVELOPERS (from Excel PBI_Developers) ─── */
export const topDevelopers = [
  { rank:1, name:"Emaar Properties", sales:65.8, salesUSD:17.9, units:13149, delivered:7318, underConst:51032, segment:"Full Spectrum", confidence:"VERIFIED", share:9.64, color:T.gold },
  { rank:2, name:"DAMAC Properties", sales:35.9, salesUSD:9.8, units:15393, delivered:2113, underConst:46554, segment:"Mid-Premium → Ultra-Lux", confidence:"VERIFIED", share:5.26, color:T.teal },
  { rank:3, name:"Binghatti", sales:26.0, salesUSD:7.1, units:17061, delivered:4093, underConst:38000, segment:"Affordable → Mid-Premium", confidence:"VERIFIED", share:3.81, color:T.blue },
  { rank:4, name:"Nakheel", sales:24.6, salesUSD:6.7, units:4160, delivered:1522, underConst:15000, segment:"Waterfront", confidence:"VERIFIED", share:3.60, color:T.green },
  { rank:5, name:"Sobha Realty", sales:22.4, salesUSD:6.1, units:9698, delivered:2260, underConst:26933, segment:"Premium → Ultra-Lux", confidence:"VERIFIED", share:3.28, color:T.purple },
  { rank:6, name:"Meraas", sales:20.9, salesUSD:5.7, units:2385, delivered:1913, underConst:12000, segment:"Premium Lifestyle", confidence:"VERIFIED", share:3.06, color:T.orange },
  { rank:7, name:"Omniyat", sales:11.0, salesUSD:3.0, units:1656, delivered:800, underConst:4500, segment:"Ultra-Luxury", confidence:"VERIFIED", share:1.61, color:"#FF7043" },
  { rank:8, name:"Aldar", sales:9.9, salesUSD:2.7, units:1732, delivered:1200, underConst:18000, segment:"Abu Dhabi + Dubai", confidence:"VERIFIED", share:1.45, color:"#42A5F5" },
  { rank:9, name:"H&H Development", sales:8.1, salesUSD:2.2, units:1200, delivered:600, underConst:8000, segment:"Mid-Premium", confidence:"VERIFIED", share:1.19, color:"#AB47BC" },
  { rank:10, name:"Danube Properties", sales:7.0, salesUSD:1.9, units:4089, delivered:1757, underConst:22000, segment:"Affordable", confidence:"VERIFIED", share:1.03, color:T.textMuted },
];

/* ─── RISK MATRIX (from Excel PBI_Risks) ─── */
export const emaarRisks = [
  { factor:"Premium Pricing Risk", level:5, likelihood:5, impact:5, score:125, mitigation:"Off-plan payment plans (80/20); branded residences justify premium", assessment:"HIGH", color:T.red },
  { factor:"Market Cycle Correction", level:4, likelihood:5, impact:5, score:100, mitigation:"Diversified revenue; 35% recurring from malls/hotels", assessment:"ELEVATED", color:T.orange },
  { factor:"Supply Competition", level:4, likelihood:5, impact:3, score:60, mitigation:"Brand premium 20-40%; 79K track record; master communities", assessment:"ELEVATED", color:T.orange },
  { factor:"Geographic Concentration", level:3, likelihood:3, impact:5, score:45, mitigation:"Expanding to Saudi, Egypt, India; +124% intl sales YoY", assessment:"MODERATE", color:T.gold },
  { factor:"Interest Rate Sensitivity", level:2, likelihood:2, impact:2, score:8, mitigation:"87% cash buyers; no floating debt exposure", assessment:"LOW", color:T.teal },
  { factor:"Execution / Delivery", level:1, likelihood:1, impact:2, score:2, mitigation:"23-year record; 79,000+ units completed on schedule", assessment:"VERY LOW", color:T.green },
  { factor:"Regulatory Changes", level:1, likelihood:1, impact:2, score:2, mitigation:"DLD/RERA framework; transparent governance", assessment:"VERY LOW", color:T.green },
  { factor:"Currency (AED Peg)", level:1, likelihood:1, impact:2, score:2, mitigation:"USD peg since 1997; zero FX risk for USD investors", assessment:"VERY LOW", color:T.green },
  { factor:"Liquidity / Exit Risk", level:1, likelihood:1, impact:1, score:1, mitigation:"DFM-listed; AED 150B+ market cap; deep secondary market", assessment:"VERY LOW", color:T.green },
];

/* ─── DUBAI MARKET 2025 (from Excel PBI_DubaiMarket) ─── */
export const dubaiMarket = [
  { metric:"Total Sales Value", val2024:"AED 522.4B", val2025:"AED 682.5B", yoy:"+30.7%", category:"Sales" },
  { metric:"Sales Transactions", val2024:"180,860", val2025:"214,912", yoy:"+18.8%", category:"Volume" },
  { metric:"Total Txn Value", val2024:"AED 760.7B", val2025:"AED 919B", yoy:"+20.8%", category:"Sales" },
  { metric:"All Transactions", val2024:"226,117", val2025:"275,442", yoy:"+21.8%", category:"Volume" },
  { metric:"Q4 Sales", val2024:"AED 147.8B", val2025:"AED 187.5B", yoy:"+26.9%", category:"Sales" },
  { metric:"Avg Price/sqft", val2024:"AED 1,484", val2025:"AED 1,755", yoy:"+18.3%", category:"Pricing" },
  { metric:"Off-Plan Share", val2024:"55%", val2025:"62.6%", yoy:"Growing", category:"Structure" },
  { metric:"Cash Buyers", val2024:"85%", val2025:"87%", yoy:"Dominant", category:"Structure" },
  { metric:"New Investors H1", val2024:"48,600", val2025:"59,075", yoy:"+22%", category:"Demand" },
];

export const dubaiSalesHistory = [
  { year:"2020", sales:120 }, { year:"2021", sales:230 }, { year:"2022", sales:300 },
  { year:"2023", sales:410 }, { year:"2024", sales:522.4 }, { year:"2025", sales:682.5 },
];

/* ─── ROI PHASES (from Excel PBI_ROIPhases) ─── */
export const roiPhases = [
  { phase:"Pre-Launch", timeline:"At Booking", low:8, high:12, avg:10, risk:"Low" },
  { phase:"Construction", timeline:"2-3 Years", low:12, high:20, avg:16, risk:"Low-Medium" },
  { phase:"Handover", timeline:"Completion", low:15, high:25, avg:20, risk:"Medium" },
  { phase:"Rental Y1+", timeline:"Post-Handover", low:4.5, high:8, avg:6.3, risk:"Low" },
  { phase:"5-Year Hold", timeline:"2026-2031", low:30, high:50, avg:40, risk:"Medium" },
];

/* ─── SEGMENTS ─── */
export const emaarSegments = [
  { name:"UAE Property Dev", revenue:36.4, growth:"44%", color:T.gold },
  { name:"Malls & Retail", revenue:6.3, growth:"13%", color:T.teal },
  { name:"Hospitality", revenue:4.2, growth:"12%", color:T.cyan },
  { name:"International", revenue:2.6, growth:"124%", color:T.green },
];

/* ─── RADAR DATA ─── */
export const radarData = [
  { metric:"Revenue Growth", value:85 },
  { metric:"Profit Margin", value:72 },
  { metric:"Market Share", value:90 },
  { metric:"Brand Strength", value:95 },
  { metric:"Diversification", value:68 },
  { metric:"Delivery Record", value:92 },
];

/* ─── MEGA PROJECTS ─── */
export const megaProjects = [
  { name:"Dubai Square", community:"Dubai Creek Harbour", value:"AED 180B+", scale:"2.6M sqm retail/hospitality", type:"Retail + Mixed-Use", timeline:"Under construction - Opening ~2028", feature:"Future rival to Dubai Mall", status:"Under Construction", desc:"Launched Nov 2025. 2.6M sqm indoor city with AI-enabled navigation, EV facilities, and world-first drive-through retail. Construction underway, 3-year target.", developer:"Emaar Properties", announced:"Nov 2025" },
  { name:"Dubai Creek Tower", community:"Dubai Creek Harbour", value:"AED 3.67B+", scale:"Landmark observation tower with sky gardens", type:"Landmark Tower", timeline:"Tender Q1 2026", feature:"Redesigned iconic landmark for DCH", status:"Tender Phase", desc:"Originally planned as world's tallest. Paused during COVID. Redesigned - Alabbar confirmed Jan 2026 tender will be issued within 3 months. Emphasizes beauty over height. Minaret-inspired design with observation decks and sky gardens.", developer:"Emaar Properties", announced:"2016 / Revived Jan 2026" },
  { name:"Dubai Mall Expansion", community:"Downtown Dubai", value:"AED 1.5B", scale:"240 new luxury stores + F&B", type:"Retail Expansion", timeline:"2025-2027", feature:"World's most visited (111M visitors/yr)", status:"Under Construction", desc:"Major expansion of world's #1 retail destination. 240 luxury stores and F&B outlets being added. Currently 12.1M sqft at 99% occupancy. 111M annual visitors.", developer:"Emaar Malls", announced:"2024" },
  { name:"Emaar Hills", community:"Adjacent to Dubai Hills Estate", value:"AED 100B", scale:"40,000 ultra-luxury residences", type:"Master-Planned Community", timeline:"2025-2035 phased", feature:"Dubai's newest mega master community", status:"Launched Oct 2025", desc:"Walking distance from Dubai Hills Mall. AED 100B total value. First launch: Dubai Mansions (10,000-20,000 sqft each with private pools). Integrates nature, wellness, championship golf, and connectivity.", developer:"Emaar Properties", announced:"Oct 2025" },
  { name:"The Oasis", community:"Al Barari Area", value:"AED 72B", scale:"9,000 villas on 100M sqft", type:"Ultra-Luxury Villas", timeline:"2026-2032 phased", feature:"Largest villa project globally", status:"Under Development", desc:"100M sqft master community. 9,000 ultra-luxury villas with clubhouses, lakes, retail hubs. Multiple sub-communities including Mareva. Designed for UHNW buyers seeking privacy and resort-style living.", developer:"Emaar Properties", announced:"2023" },
  { name:"Grand Polo Club", community:"Dubai South", value:"AED 25B+", scale:"900+ units, polo grounds, equestrian", type:"Luxury Lifestyle", timeline:"2026-2030 phased", feature:"World's first polo-themed community", status:"Off-Plan Sales Active", desc:"World's first polo-themed residential community. World-class polo grounds, equestrian facilities, ultra-luxury villas and townhouses. Sub-communities: Selvara, Equestra, Equiterra, Chevalia Estate.", developer:"Emaar Properties", announced:"2024" },
  { name:"Dubai Creek Harbour District", community:"Dubai Creek Harbour", value:"AED 180B total", scale:"11M sqm - 3x size of Downtown Dubai", type:"Integrated Waterfront District", timeline:"Multi-phase through 2035+", feature:"New urban centre - 10,500+ units complete", status:"Partially Complete", desc:"11M sqm waterfront district. 10,582 completed units as of Sep 2025, 7,217 more by 2029. Features Creek Beach, marina, Vida/Address hotels, 30-hectare Central Park. Dubai Metro Blue Line connection coming (14 stations by 2029).", developer:"Emaar & Dubai Holding", announced:"2013" },
  { name:"Al Maktoum Intl Airport Expansion", community:"Dubai South", value:"AED 128B (USD 35B)", scale:"400+ gates, 5 runways, 260M passengers", type:"Airport Infrastructure", timeline:"Phase 1: 2032", feature:"World's largest airport - benefits Emaar South/GPC", status:"Under Construction", desc:"Will replace DXB as Dubai's primary airport. 5 parallel runways, 5 terminals, underground train. 260M annual passenger capacity. Directly benefits Emaar South, Grand Polo Club, and The Oasis with massive infrastructure investment and area appreciation.", developer:"Dubai Government", announced:"2019 / Expansion 2024" },
];

/* ─── COMMUNITY INTELLIGENCE (Location Profiles) ─── */
export const communityIntel = {
  "Dubai Hills Estate": {
    tagline: "Golf-Side Family Living in the Heart of New Dubai",
    famousFor: "18-hole championship golf course with Burj Khalifa views, Dubai Hills Mall (650+ outlets), 1.45M sqm of parks & open spaces, 54 km bicycle route",
    masterDev: "Emaar & Meraas joint venture — first phase of Mohammed Bin Rashid City (MBR City)",
    lifestyle: "Family-oriented, golf lifestyle, park-centric, gated communities with 24/7 security",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "GEMS Wellington Academy, King's School Al Barsha, Dubai Heights Academy, Blossom Nursery" },
      { icon: "🏥", label: "Healthcare", items: "King's College Hospital London (on-site), Mediclinic Parkview Hospital, Saudi German Hospital" },
      { icon: "🛍️", label: "Malls", items: "Dubai Hills Mall (on-site, 650+ stores), Mall of the Emirates (12 min)" },
      { icon: "⛳", label: "Leisure", items: "Dubai Hills Golf Club, Dubai Hills Park (splash park, skate park, ice rink), 54 km cycling tracks" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 13, min: 15 },
      { dest: "Business Bay / DIFC", km: 14, min: 16 },
      { dest: "Dubai Marina / JBR", km: 24, min: 25 },
      { dest: "Dubai Intl Airport (DXB)", km: 24, min: 25 },
      { dest: "Mall of the Emirates", km: 9, min: 12 },
      { dest: "Sheikh Zayed Road (E11)", km: 4, min: 5 },
      { dest: "Al Khail Road (E44)", km: 1, min: 2 },
      { dest: "Palm Jumeirah", km: 17, min: 21 },
    ],
    roads: "Al Khail Road (E44), Umm Suqeim Street, Sheikh Mohammed Bin Zayed Road (E311). Future metro connection planned.",
    goldenVisa: true,
    avgYield: "4.5–5.5%",
  },
  "Dubai Creek Harbour": {
    tagline: "Waterfront Living Between Historic Dubai & Modern Skyline",
    famousFor: "Creek Tower (future landmark), Ras Al Khor Wildlife Sanctuary views, waterfront promenade, yacht marina, Creek Beach, Vida & Address branded hotels",
    masterDev: "Emaar & Dubai Holding — 9 integrated districts along historic Dubai Creek",
    lifestyle: "Waterfront urban, young professionals & couples, design-led calm with skyline views",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "Deira International School (15 min), North London Collegiate (Sobha Hartland, 15 min), King's School Nad Al Sheba" },
      { icon: "🏥", label: "Healthcare", items: "Mediclinic Creek Harbour (on-site), Berlin Hospital Nadd Al Hamar, Rashid Hospital (15 min)" },
      { icon: "🛍️", label: "Malls", items: "Dubai Mall (15 min), Dubai Festival City Mall (11 min), upcoming 820,000 sqm retail within DCH" },
      { icon: "🌊", label: "Leisure", items: "Creek Beach, Marina Yacht Club, Ras Al Khor Wildlife Sanctuary, 30-hectare Central Park, waterfront promenade" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 10, min: 15 },
      { dest: "Business Bay / DIFC", km: 9, min: 15 },
      { dest: "Dubai Intl Airport (DXB)", km: 11, min: 12 },
      { dest: "Dubai Festival City", km: 9, min: 11 },
      { dest: "Dubai Marina / JBR", km: 30, min: 30 },
      { dest: "Sheikh Zayed Road (E11)", km: 8, min: 12 },
      { dest: "Ras Al Khor Road (E44)", km: 2, min: 3 },
      { dest: "Dubai Frame", km: 10, min: 14 },
    ],
    roads: "Ras Al Khor Road (E44), Nad Al Hamar Road (D62). Dubai Metro Green Line nearby (Dubai Healthcare City / Creek stations).",
    goldenVisa: true,
    avgYield: "5.0–6.0%",
  },
  "Emaar Beachfront": {
    tagline: "Private Island Living Between Dubai Marina & Palm Jumeirah",
    famousFor: "1.5 km private beach, island gated community within Dubai Harbour, 27 residential towers, Address & Bristol branded residences, 1,100+ yacht berth marina",
    masterDev: "Emaar Properties — 10 million sqft gated island community in Dubai Harbour",
    lifestyle: "Ultra-luxury beachfront, resort-style, yacht owners, high-net-worth individuals & couples",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "iCademy Middle East (10 min), Dubai British School (10 min), GEMS Wellington (12 min), nurseries in JBR/Marina" },
      { icon: "🏥", label: "Healthcare", items: "Emirates Hospital Clinic Marina (8 min), Mediclinic Meadows (17 min), Al Zahra Hospital (13 min)" },
      { icon: "🛍️", label: "Malls", items: "On-site 13,000 sqft retail mall, Dubai Marina Mall (5 min), Nakheel Mall Palm (12 min), The Walk JBR (10 min)" },
      { icon: "🏖️", label: "Leisure", items: "1.5 km private beach, yacht marina (1,100+ berths), beach clubs, Ain Dubai (15 min), Bluewaters Island" },
    ],
    distances: [
      { dest: "Dubai Marina / JBR", km: 3, min: 5 },
      { dest: "Palm Jumeirah", km: 5, min: 12 },
      { dest: "Downtown Dubai / Burj Khalifa", km: 22, min: 25 },
      { dest: "Business Bay / DIFC", km: 22, min: 25 },
      { dest: "Dubai Intl Airport (DXB)", km: 35, min: 28 },
      { dest: "Sheikh Zayed Road (E11)", km: 2, min: 5 },
      { dest: "Media City / Internet City", km: 5, min: 8 },
      { dest: "Mall of the Emirates", km: 8, min: 12 },
    ],
    roads: "Sheikh Zayed Road (E11), Al Sufouh Road. Sobha Realty Metro Station nearby.",
    goldenVisa: true,
    avgYield: "3.5–5.0%",
  },
  "Emaar South": {
    tagline: "Affordable Golf Living at Dubai's Future Aviation Hub",
    famousFor: "18-hole championship golf course, proximity to Al Maktoum International Airport (5 min) & Expo City Dubai, most affordable Emaar entry point, Dubai's southern growth corridor",
    masterDev: "Emaar Properties — within Dubai South district, 15,000+ homes planned",
    lifestyle: "Value-conscious families, young professionals, frequent travellers, golf lifestyle at entry-level pricing",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "GEMS International School (on-site), Greenfield Community School, Durham School Dubai (20 min), South View School" },
      { icon: "🏥", label: "Healthcare", items: "NMC Royal Hospital (20 min), Al Maktoum Airport Clinic (7 min), Mediclinic Meadows (nearby)" },
      { icon: "🛍️", label: "Malls", items: "Community retail centre (on-site), Ibn Battuta Mall (25 min), City Centre Me'aisem (nearby)" },
      { icon: "⛳", label: "Leisure", items: "18-hole golf course, community parks, swimming pools, Dubai Parks & Resorts (15 min), Expo City Dubai (10 min)" },
    ],
    distances: [
      { dest: "Al Maktoum Intl Airport (DWC)", km: 5, min: 7 },
      { dest: "Expo City Dubai", km: 8, min: 10 },
      { dest: "Downtown Dubai / Burj Khalifa", km: 40, min: 32 },
      { dest: "Dubai Marina / JBR", km: 30, min: 25 },
      { dest: "Dubai Hills Estate", km: 25, min: 20 },
      { dest: "Sheikh Zayed Road (E11)", km: 15, min: 18 },
      { dest: "E311 (MBZ Road)", km: 3, min: 5 },
      { dest: "Emirates Road (E611)", km: 2, min: 3 },
    ],
    roads: "Sheikh Mohammed Bin Zayed Road (E311), Emirates Road (E611). Expo 2020 Metro Station (20 min by bus).",
    goldenVisa: false,
    avgYield: "5.0–6.5%",
  },
  "Expo Living": {
    tagline: "Next-Gen Living at the Expo City District",
    famousFor: "Built on legacy of World Expo 2020, smart city infrastructure, sustainability-focused, adjacent to Expo City Dubai permanent district",
    masterDev: "Emaar Properties — within Expo City / Dubai South area",
    lifestyle: "Tech-savvy professionals, sustainability-minded, young families, future-forward community",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "GEMS International School (nearby), South View School, planned community school" },
      { icon: "🏥", label: "Healthcare", items: "NMC Royal Hospital (15 min), Al Maktoum Airport Clinic, planned community clinic" },
      { icon: "🛍️", label: "Malls", items: "Expo City retail district, Ibn Battuta Mall (20 min), City Centre Me'aisem" },
      { icon: "🌿", label: "Leisure", items: "Expo City pavilions & events, Terra sustainability pavilion, Al Wasl Plaza, community parks" },
    ],
    distances: [
      { dest: "Expo City Dubai", km: 2, min: 3 },
      { dest: "Al Maktoum Intl Airport (DWC)", km: 8, min: 10 },
      { dest: "Downtown Dubai / Burj Khalifa", km: 38, min: 30 },
      { dest: "Dubai Marina / JBR", km: 28, min: 25 },
      { dest: "Dubai Hills Estate", km: 22, min: 18 },
      { dest: "Sheikh Zayed Road (E11)", km: 12, min: 15 },
      { dest: "E311 (MBZ Road)", km: 3, min: 5 },
      { dest: "Emirates Road (E611)", km: 3, min: 4 },
    ],
    roads: "Sheikh Mohammed Bin Zayed Road (E311), Emirates Road (E611). Expo 2020 Metro Station (Red Line).",
    goldenVisa: false,
    avgYield: "5.0–6.0%",
  },
  "The Valley": {
    tagline: "Desert-Inspired Suburban Family Retreat on Dubai-Al Ain Road",
    famousFor: "Dubai's first desert-themed community, 47,000 sqm Sports Village, 30,000 sqm Golden Beach, 10,000 sqm Kids' Dale, Town Centre with farmers' market, family townhouses & villas",
    masterDev: "Emaar Properties — 200+ hectare master-planned community in Dubailand along Dubai-Al Ain Road",
    lifestyle: "Family-first suburban, nature-inspired, active outdoor lifestyle, village atmosphere with modern amenities",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "Maple Bear Nursery (on-site), GEMS FirstPoint School (12 km), The Aquila School, Repton School (25 min)" },
      { icon: "🏥", label: "Healthcare", items: "Dubai London Clinic (nearby), HealthHub Clinic, Aster Clinic Silicon Oasis, Emirates Hospital (24 min)" },
      { icon: "🛍️", label: "Malls", items: "The Pavilion Town Centre (on-site, 32,000 sqm), Dubai Outlet Mall (nearby), Dubai Hills Mall (20 min)" },
      { icon: "🏊", label: "Leisure", items: "Golden Beach (30,000 sqm), Sports Village, Kids' Dale, Wellness Center with spa & padel, cycling tracks, Zen Garden" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 28, min: 25 },
      { dest: "Dubai Intl Airport (DXB)", km: 22, min: 22 },
      { dest: "Dubai Marina / JBR", km: 35, min: 33 },
      { dest: "Dubai Hills Estate", km: 18, min: 20 },
      { dest: "IMG Worlds of Adventure", km: 10, min: 12 },
      { dest: "Dubai Silicon Oasis", km: 12, min: 14 },
      { dest: "Dubai-Al Ain Road (E66)", km: 1, min: 2 },
      { dest: "Academic City", km: 12, min: 17 },
    ],
    roads: "Dubai-Al Ain Road (E66), Jebel Ali-Lehbab Road (E77). Public transport still developing, private vehicle recommended.",
    goldenVisa: false,
    avgYield: "5.0–6.0%",
  },
  "Grand Polo Club": {
    tagline: "Equestrian Ultra-Luxury Estate — Dubai's Polo Lifestyle Destination",
    famousFor: "60 million sqft polo & equestrian estate, championship polo fields, world-class stables & riding school, AED 41B+ project value, gated resort-style living",
    masterDev: "Emaar Properties — adjacent to The Oasis in Dubai Investment Park 2 (DIP 2)",
    lifestyle: "Ultra-luxury, equestrian enthusiasts, high-net-worth families, resort-style gated community",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "Greenfield International School (10 min), Bright Riders School (10 min), The Arbor School, planned community school" },
      { icon: "🏥", label: "Healthcare", items: "NMC Royal Hospital DIP (15 min), Paradise Plus Poly Clinic, Mediclinic Parkview Hospital" },
      { icon: "🛍️", label: "Malls", items: "City Centre Me'aisem (10 min), Ibn Battuta Mall (20 min), Dubai Outlet Mall (15 min)" },
      { icon: "🐎", label: "Leisure", items: "Grand polo field, equestrian club & stables, riding school, mini golf, padel courts, football courts, forest walk, dog park" },
    ],
    distances: [
      { dest: "Al Maktoum Intl Airport (DWC)", km: 5, min: 5 },
      { dest: "Expo City Dubai", km: 8, min: 10 },
      { dest: "Downtown Dubai / Burj Khalifa", km: 42, min: 35 },
      { dest: "Dubai Marina / JBR", km: 30, min: 28 },
      { dest: "Dubai Hills Estate / Mall", km: 22, min: 20 },
      { dest: "Sheikh Zayed Road (E11)", km: 18, min: 20 },
      { dest: "Expo Road (E77)", km: 2, min: 3 },
      { dest: "Emirates Road (E611)", km: 2, min: 3 },
    ],
    roads: "Expo Road (E77), Emirates Road (E611), Sheikh Zayed Bin Hamdan Al Nahyan Street.",
    goldenVisa: true,
    avgYield: "5.0–7.0%",
  },
  "Rashid Yachts & Marina": {
    tagline: "Historic Port Reborn as Dubai's Premier Yacht & Waterfront Destination",
    famousFor: "430-berth marina for yachts up to 100m, QE2 floating hotel, Dubai's longest swimmable canal pool (500m), Venetian piazza, Dubai Mall by the Sea (upcoming), heritage meets modern luxury",
    masterDev: "Emaar Properties & P&O Marinas — 6.8 million sqft in historic Port Rashid, Bur Dubai",
    lifestyle: "Maritime luxury, yacht owners, urban waterfront, blend of old & new Dubai charm",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "New Academy School (2 km), GEMS Winchester School (2.5 km), Ambassador School, nurseries in Bur Dubai" },
      { icon: "🏥", label: "Healthcare", items: "Rashid Hospital (15 min), Aster Hospital, International Modern Hospital, Dubai Healthcare City Phase 2 (7 km)" },
      { icon: "🛍️", label: "Malls", items: "BurJuman (15 min), Dubai Mall (16 min), upcoming Dubai Mall by the Sea (on-site), Karama Centre" },
      { icon: "⛵", label: "Leisure", items: "430-yacht marina, QE2 Hotel, 500m canal pool, Venetian piazza, beach club, floating yacht club, waterfront promenade" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 12, min: 19 },
      { dest: "Business Bay / DIFC", km: 10, min: 18 },
      { dest: "Dubai Intl Airport (DXB)", km: 13, min: 17 },
      { dest: "Dubai Mall", km: 11, min: 16 },
      { dest: "La Mer Beach", km: 5, min: 10 },
      { dest: "Sheikh Zayed Road (E11)", km: 4, min: 15 },
      { dest: "Dubai Frame", km: 7, min: 12 },
      { dest: "Gold Souk / Deira", km: 8, min: 20 },
    ],
    roads: "Al Mina Road (D75), Sheikh Zayed Road (E11), Infinity Bridge to Deira. Water taxi available.",
    goldenVisa: true,
    avgYield: "5.5–7.0%",
  },
  "The Oasis": {
    tagline: "Dubai's Most Exclusive Ultra-Luxury Villa & Mansion Sanctuary",
    famousFor: "100 million sqft mega-development (AED 73B value), 7,000+ luxury villas & mansions, 25% dedicated to green spaces & water features, world-renowned architect designs, largest villa project globally",
    masterDev: "Emaar Properties & Dubai Holding — in Dubailand, between Emirates Road & Sheikh Zayed Bin Hamdan Street",
    lifestyle: "Ultra-high-net-worth, mansion living, lagoon & waterway views, absolute privacy with resort amenities",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "South View School (2.6 km), Jebel Ali School (3.8 km), Fairgreen International School (15 min), GEMS United School" },
      { icon: "🏥", label: "Healthcare", items: "Saudi German Clinics (on-site), Mediclinic Parkview Hospital (22 min), Aster Clinic Arabian Ranches (16 min)" },
      { icon: "🛍️", label: "Malls", items: "City Centre Me'aisem (10 min), Dubai Outlet Mall (15 min), planned on-site retail" },
      { icon: "🌴", label: "Leisure", items: "Private beaches & lagoons, 54 km cycling route, jogging tracks, sports courts, Trump Intl Golf Club (10 min), Dubai Autodrome (12 min)" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 40, min: 35 },
      { dest: "Dubai Hills Estate", km: 20, min: 20 },
      { dest: "Dubai Marina / JBR", km: 32, min: 28 },
      { dest: "Sheikh Zayed Road (E11)", km: 15, min: 16 },
      { dest: "Al Maktoum Intl Airport (DWC)", km: 10, min: 12 },
      { dest: "Expo City Dubai", km: 12, min: 14 },
      { dest: "Emirates Road (E611)", km: 2, min: 3 },
      { dest: "Dubai Intl Airport (DXB)", km: 38, min: 35 },
    ],
    roads: "Emirates Road (E611), Sheikh Zayed Bin Hamdan Road (D54), future Al Khail Road (E44) extension.",
    goldenVisa: true,
    avgYield: "4.0–5.5%",
  },
  "Business Bay": {
    tagline: "Dubai's Central Business & Luxury Living District",
    famousFor: "Adjacent to Downtown Dubai, Dubai Canal waterfront, 240+ commercial & residential towers, home to Address & Palace branded residences, Dubai's CBD with skyline views",
    masterDev: "Dubai Properties — with select Emaar branded residences (Palace, Address)",
    lifestyle: "Urban executives, business professionals, luxury city living, walkable to Downtown & DIFC",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "JSS International School (10 min), GEMS Wellington Primary (12 min), multiple nurseries within Business Bay" },
      { icon: "🏥", label: "Healthcare", items: "Mediclinic Parkview Hospital (10 min), American Hospital Dubai (15 min), multiple clinics in Business Bay" },
      { icon: "🛍️", label: "Malls", items: "Dubai Mall (10 min walk), Bay Avenue Mall (on-site), City Walk (10 min)" },
      { icon: "🏙️", label: "Leisure", items: "Dubai Canal boardwalk, Downtown Dubai promenade, Dubai Opera (10 min), Business Bay parks, waterfront dining" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 3, min: 5 },
      { dest: "DIFC", km: 4, min: 7 },
      { dest: "Dubai Mall", km: 3, min: 8 },
      { dest: "Dubai Intl Airport (DXB)", km: 15, min: 18 },
      { dest: "Dubai Marina / JBR", km: 22, min: 22 },
      { dest: "Sheikh Zayed Road (E11)", km: 1, min: 3 },
      { dest: "Al Khail Road (E44)", km: 1, min: 3 },
      { dest: "City Walk", km: 4, min: 8 },
    ],
    roads: "Sheikh Zayed Road (E11), Al Khail Road (E44), Business Bay Metro Station (Red Line).",
    goldenVisa: true,
    avgYield: "5.5–7.0%",
  },
  "The Heights CW": {
    tagline: "Country Club & Wellness Living Adjacent to The Oasis",
    famousFor: "Premium country club lifestyle, wellness-focused design, adjacent to The Oasis mega-development, green corridor living",
    masterDev: "Emaar Properties — within the greater Oasis / Dubai South corridor",
    lifestyle: "Wellness-focused families, country club living, suburban tranquility with modern amenities",
    keyAmenities: [
      { icon: "🏫", label: "Schools", items: "South View School (nearby), Jebel Ali School, Greenfield International School (10 min)" },
      { icon: "🏥", label: "Healthcare", items: "NMC Royal Hospital DIP (15 min), Mediclinic Parkview Hospital, community clinics planned" },
      { icon: "🛍️", label: "Malls", items: "City Centre Me'aisem (10 min), Ibn Battuta Mall (20 min)" },
      { icon: "🧘", label: "Leisure", items: "Country club & wellness centre, sports courts, cycling & jogging tracks, landscaped parks, nearby Oasis amenities" },
    ],
    distances: [
      { dest: "Downtown Dubai / Burj Khalifa", km: 40, min: 35 },
      { dest: "Dubai Hills Estate", km: 22, min: 20 },
      { dest: "Dubai Marina / JBR", km: 30, min: 28 },
      { dest: "Al Maktoum Intl Airport (DWC)", km: 8, min: 10 },
      { dest: "Expo City Dubai", km: 10, min: 12 },
      { dest: "Sheikh Zayed Road (E11)", km: 16, min: 18 },
      { dest: "Emirates Road (E611)", km: 2, min: 3 },
      { dest: "Dubai Intl Airport (DXB)", km: 38, min: 35 },
    ],
    roads: "Emirates Road (E611), Sheikh Zayed Bin Hamdan Road (D54), Expo Road (E77).",
    goldenVisa: true,
    avgYield: "5.0–6.0%",
  },
};
