/* ═══════════════════════════════════════════════════════════════
   DXB ANALYTICS — INTERNATIONALIZATION (i18n)
   20 languages · RTL support · localStorage persistence
   ═══════════════════════════════════════════════════════════════ */
import React, { createContext, useContext, useState } from "react";

export const LANGUAGES = [
  { code: "en", name: "English", flag: "🇬🇧", dir: "ltr" },
  { code: "ar", name: "العربية", flag: "🇦🇪", dir: "rtl" },
  { code: "ur", name: "اردو", flag: "🇵🇰", dir: "rtl" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳", dir: "ltr" },
  { code: "zh", name: "中文", flag: "🇨🇳", dir: "ltr" },
  { code: "ru", name: "Русский", flag: "🇷🇺", dir: "ltr" },
  { code: "fr", name: "Français", flag: "🇫🇷", dir: "ltr" },
  { code: "es", name: "Español", flag: "🇪🇸", dir: "ltr" },
  { code: "de", name: "Deutsch", flag: "🇩🇪", dir: "ltr" },
  { code: "pt", name: "Português", flag: "🇧🇷", dir: "ltr" },
  { code: "ja", name: "日本語", flag: "🇯🇵", dir: "ltr" },
  { code: "ko", name: "한국어", flag: "🇰🇷", dir: "ltr" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷", dir: "ltr" },
  { code: "it", name: "Italiano", flag: "🇮🇹", dir: "ltr" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱", dir: "ltr" },
  { code: "fa", name: "فارسی", flag: "🇮🇷", dir: "rtl" },
  { code: "th", name: "ไทย", flag: "🇹🇭", dir: "ltr" },
  { code: "tl", name: "Filipino", flag: "🇵🇭", dir: "ltr" },
  { code: "bn", name: "বাংলা", flag: "🇧🇩", dir: "ltr" },
  { code: "sw", name: "Kiswahili", flag: "🇰🇪", dir: "ltr" },
];

const T = {
  // ─── TABS ───
  tabs: {
    en: { Overview: "Overview", Financials: "Financials", Projects: "Projects", Map: "Map", Portfolio: "Portfolio", Competitors: "Competitors", Yields: "Yields", Risk: "Risk", Stocks: "Stocks", Market: "Market", Admin: "Admin" },
    ar: { Overview: "نظرة عامة", Financials: "البيانات المالية", Projects: "المشاريع", Map: "الخريطة", Portfolio: "المحفظة", Competitors: "المنافسون", Yields: "العوائد", Risk: "المخاطر", Stocks: "الأسهم", Market: "السوق", Admin: "الإدارة" },
    ur: { Overview: "جائزہ", Financials: "مالیات", Projects: "منصوبے", Map: "نقشہ", Portfolio: "پورٹ فولیو", Competitors: "حریف", Yields: "منافع", Risk: "خطرات", Stocks: "اسٹاکس", Market: "مارکیٹ", Admin: "ایڈمن" },
    hi: { Overview: "अवलोकन", Financials: "वित्तीय", Projects: "परियोजनाएँ", Map: "मानचित्र", Portfolio: "पोर्टफोलियो", Competitors: "प्रतिस्पर्धी", Yields: "उपज", Risk: "जोखिम", Stocks: "स्टॉक्स", Market: "बाज़ार", Admin: "एडमिन" },
    zh: { Overview: "概览", Financials: "财务数据", Projects: "项目", Map: "地图", Portfolio: "投资组合", Competitors: "竞争对手", Yields: "收益率", Risk: "风险", Stocks: "股票", Market: "市场", Admin: "管理" },
    ru: { Overview: "Обзор", Financials: "Финансы", Projects: "Проекты", Map: "Карта", Portfolio: "Портфель", Competitors: "Конкуренты", Yields: "Доходность", Risk: "Риски", Stocks: "Акции", Market: "Рынок", Admin: "Админ" },
    fr: { Overview: "Aperçu", Financials: "Finances", Projects: "Projets", Map: "Carte", Portfolio: "Portefeuille", Competitors: "Concurrents", Yields: "Rendements", Risk: "Risques", Stocks: "Actions", Market: "Marché", Admin: "Admin" },
    es: { Overview: "Resumen", Financials: "Finanzas", Projects: "Proyectos", Map: "Mapa", Portfolio: "Portafolio", Competitors: "Competidores", Yields: "Rendimientos", Risk: "Riesgo", Stocks: "Acciones", Market: "Mercado", Admin: "Admin" },
    de: { Overview: "Übersicht", Financials: "Finanzen", Projects: "Projekte", Map: "Karte", Portfolio: "Portfolio", Competitors: "Wettbewerber", Yields: "Renditen", Risk: "Risiko", Stocks: "Aktien", Market: "Markt", Admin: "Admin" },
    pt: { Overview: "Visão Geral", Financials: "Finanças", Projects: "Projetos", Map: "Mapa", Portfolio: "Portfólio", Competitors: "Concorrentes", Yields: "Rendimentos", Risk: "Risco", Stocks: "Ações", Market: "Mercado", Admin: "Admin" },
    ja: { Overview: "概要", Financials: "財務", Projects: "プロジェクト", Map: "地図", Portfolio: "ポートフォリオ", Competitors: "競合", Yields: "利回り", Risk: "リスク", Stocks: "株式", Market: "市場", Admin: "管理" },
    ko: { Overview: "개요", Financials: "재무", Projects: "프로젝트", Map: "지도", Portfolio: "포트폴리오", Competitors: "경쟁사", Yields: "수익률", Risk: "리스크", Stocks: "주식", Market: "시장", Admin: "관리자" },
    tr: { Overview: "Genel Bakış", Financials: "Finansal", Projects: "Projeler", Map: "Harita", Portfolio: "Portföy", Competitors: "Rakipler", Yields: "Getiriler", Risk: "Risk", Stocks: "Hisseler", Market: "Piyasa", Admin: "Yönetici" },
    it: { Overview: "Panoramica", Financials: "Finanza", Projects: "Progetti", Map: "Mappa", Portfolio: "Portafoglio", Competitors: "Concorrenti", Yields: "Rendimenti", Risk: "Rischio", Stocks: "Azioni", Market: "Mercato", Admin: "Admin" },
    nl: { Overview: "Overzicht", Financials: "Financiën", Projects: "Projecten", Map: "Kaart", Portfolio: "Portefeuille", Competitors: "Concurrenten", Yields: "Rendementen", Risk: "Risico", Stocks: "Aandelen", Market: "Markt", Admin: "Admin" },
    fa: { Overview: "نمای کلی", Financials: "مالی", Projects: "پروژه‌ها", Map: "نقشه", Portfolio: "سبد سرمایه", Competitors: "رقبا", Yields: "بازده", Risk: "ریسک", Stocks: "سهام", Market: "بازار", Admin: "مدیریت" },
    th: { Overview: "ภาพรวม", Financials: "การเงิน", Projects: "โครงการ", Map: "แผนที่", Portfolio: "พอร์ต", Competitors: "คู่แข่ง", Yields: "ผลตอบแทน", Risk: "ความเสี่ยง", Stocks: "หุ้น", Market: "ตลาด", Admin: "ผู้ดูแล" },
    tl: { Overview: "Pangkalahatang-tanaw", Financials: "Pananalapi", Projects: "Mga Proyekto", Map: "Mapa", Portfolio: "Portfolio", Competitors: "Mga Kakumpitensya", Yields: "Kita", Risk: "Panganib", Stocks: "Mga Stock", Market: "Pamilihan", Admin: "Admin" },
    bn: { Overview: "সারসংক্ষেপ", Financials: "আর্থিক", Projects: "প্রকল্প", Map: "মানচিত্র", Portfolio: "পোর্টফোলিও", Competitors: "প্রতিযোগী", Yields: "আয়", Risk: "ঝুঁকি", Stocks: "স্টক", Market: "বাজার", Admin: "অ্যাডমিন" },
    sw: { Overview: "Muhtasari", Financials: "Fedha", Projects: "Miradi", Map: "Ramani", Portfolio: "Kanda", Competitors: "Washindani", Yields: "Mapato", Risk: "Hatari", Stocks: "Hisa", Market: "Soko", Admin: "Msimamizi" },
  },

  // ─── SIDEBAR ───
  sidebar: {
    en: { platform: "Intelligence Platform", admin: "Admin", adminPortal: "Admin Portal", layoutSettings: "Layout Settings", adminConsole: "Admin Console", quickLinks: "Quick Links", dashboard: "Dashboard", landingPage: "Landing Page" },
    ar: { platform: "منصة الاستخبارات", admin: "الإدارة", adminPortal: "بوابة الإدارة", layoutSettings: "إعدادات التخطيط", adminConsole: "لوحة الإدارة", quickLinks: "روابط سريعة", dashboard: "لوحة القيادة", landingPage: "الصفحة الرئيسية" },
    ur: { platform: "انٹیلی جنس پلیٹ فارم", admin: "ایڈمن", adminPortal: "ایڈمن پورٹل", layoutSettings: "لے آؤٹ سیٹنگز", adminConsole: "ایڈمن کنسول", quickLinks: "فوری لنکس", dashboard: "ڈیش بورڈ", landingPage: "لینڈنگ پیج" },
    hi: { platform: "इंटेलिजेंस प्लेटफ़ॉर्म", admin: "एडमिन", adminPortal: "एडमिन पोर्टल", layoutSettings: "लेआउट सेटिंग्स", adminConsole: "एडमिन कंसोल", quickLinks: "त्वरित लिंक", dashboard: "डैशबोर्ड", landingPage: "लैंडिंग पेज" },
    zh: { platform: "情报平台", admin: "管理", adminPortal: "管理门户", layoutSettings: "布局设置", adminConsole: "管理控制台", quickLinks: "快捷链接", dashboard: "仪表盘", landingPage: "登陆页" },
    ru: { platform: "Аналитическая платформа", admin: "Администрирование", adminPortal: "Панель администратора", layoutSettings: "Настройки макета", adminConsole: "Консоль администратора", quickLinks: "Быстрые ссылки", dashboard: "Панель", landingPage: "Лендинг" },
    fr: { platform: "Plateforme d'Intelligence", admin: "Admin", adminPortal: "Portail Admin", layoutSettings: "Paramètres de mise en page", adminConsole: "Console Admin", quickLinks: "Liens rapides", dashboard: "Tableau de bord", landingPage: "Page d'accueil" },
    es: { platform: "Plataforma de Inteligencia", admin: "Admin", adminPortal: "Portal Admin", layoutSettings: "Configuración de diseño", adminConsole: "Consola Admin", quickLinks: "Enlaces rápidos", dashboard: "Panel", landingPage: "Página de inicio" },
    de: { platform: "Intelligence-Plattform", admin: "Admin", adminPortal: "Admin-Portal", layoutSettings: "Layout-Einstellungen", adminConsole: "Admin-Konsole", quickLinks: "Schnelllinks", dashboard: "Dashboard", landingPage: "Startseite" },
    pt: { platform: "Plataforma de Inteligência", admin: "Admin", adminPortal: "Portal Admin", layoutSettings: "Configurações de layout", adminConsole: "Console Admin", quickLinks: "Links rápidos", dashboard: "Painel", landingPage: "Página inicial" },
    ja: { platform: "インテリジェンスプラットフォーム", admin: "管理", adminPortal: "管理ポータル", layoutSettings: "レイアウト設定", adminConsole: "管理コンソール", quickLinks: "クイックリンク", dashboard: "ダッシュボード", landingPage: "ランディングページ" },
    ko: { platform: "인텔리전스 플랫폼", admin: "관리자", adminPortal: "관리자 포털", layoutSettings: "레이아웃 설정", adminConsole: "관리자 콘솔", quickLinks: "빠른 링크", dashboard: "대시보드", landingPage: "랜딩 페이지" },
    tr: { platform: "İstihbarat Platformu", admin: "Yönetici", adminPortal: "Yönetici Portalı", layoutSettings: "Düzen Ayarları", adminConsole: "Yönetici Konsolu", quickLinks: "Hızlı Bağlantılar", dashboard: "Pano", landingPage: "Ana Sayfa" },
    it: { platform: "Piattaforma Intelligence", admin: "Admin", adminPortal: "Portale Admin", layoutSettings: "Impostazioni layout", adminConsole: "Console Admin", quickLinks: "Link rapidi", dashboard: "Dashboard", landingPage: "Pagina iniziale" },
    nl: { platform: "Intelligence Platform", admin: "Admin", adminPortal: "Admin Portaal", layoutSettings: "Layout Instellingen", adminConsole: "Admin Console", quickLinks: "Snelle links", dashboard: "Dashboard", landingPage: "Landingspagina" },
    fa: { platform: "پلتفرم اطلاعات", admin: "مدیریت", adminPortal: "پورتال مدیریت", layoutSettings: "تنظیمات چیدمان", adminConsole: "کنسول مدیریت", quickLinks: "لینک‌های سریع", dashboard: "داشبورد", landingPage: "صفحه اصلی" },
    th: { platform: "แพลตฟอร์มข่าวกรอง", admin: "ผู้ดูแล", adminPortal: "พอร์ทัลผู้ดูแล", layoutSettings: "ตั้งค่าเลย์เอาต์", adminConsole: "คอนโซลผู้ดูแล", quickLinks: "ลิงก์ด่วน", dashboard: "แดชบอร์ด", landingPage: "หน้าแรก" },
    tl: { platform: "Intelligence Platform", admin: "Admin", adminPortal: "Portal ng Admin", layoutSettings: "Mga Setting ng Layout", adminConsole: "Admin Console", quickLinks: "Mabilisang Links", dashboard: "Dashboard", landingPage: "Landing Page" },
    bn: { platform: "ইন্টেলিজেন্স প্ল্যাটফর্ম", admin: "অ্যাডমিন", adminPortal: "অ্যাডমিন পোর্টাল", layoutSettings: "লেআউট সেটিংস", adminConsole: "অ্যাডমিন কনসোল", quickLinks: "দ্রুত লিংক", dashboard: "ড্যাশবোর্ড", landingPage: "ল্যান্ডিং পেজ" },
    sw: { platform: "Jukwaa la Ujasusi", admin: "Msimamizi", adminPortal: "Portal ya Msimamizi", layoutSettings: "Mipangilio ya Muundo", adminConsole: "Dashibodi ya Msimamizi", quickLinks: "Viungo vya Haraka", dashboard: "Dashibodi", landingPage: "Ukurasa wa Kuingia" },
  },

  // ─── ADMIN TABS ───
  adminTabs: {
    en: { overview: "Overview", users: "Users", revenue: "Revenue", data: "Data Manager", projects: "Project Manager", leads: "Leads", verification: "Verification", analytics: "Analytics" },
    ar: { overview: "نظرة عامة", users: "المستخدمون", revenue: "الإيرادات", data: "إدارة البيانات", projects: "إدارة المشاريع", leads: "العملاء المحتملون", verification: "التحقق", analytics: "التحليلات" },
    ur: { overview: "جائزہ", users: "صارفین", revenue: "آمدنی", data: "ڈیٹا مینیجر", projects: "پروجیکٹ مینیجر", leads: "لیڈز", verification: "تصدیق", analytics: "تجزیات" },
    hi: { overview: "अवलोकन", users: "उपयोगकर्ता", revenue: "राजस्व", data: "डेटा प्रबंधक", projects: "प्रोजेक्ट प्रबंधक", leads: "लीड्स", verification: "सत्यापन", analytics: "एनालिटिक्स" },
    zh: { overview: "概览", users: "用户", revenue: "收入", data: "数据管理", projects: "项目管理", leads: "潜在客户", verification: "身份验证", analytics: "分析" },
    ru: { overview: "Обзор", users: "Пользователи", revenue: "Доходы", data: "Данные", projects: "Проекты", leads: "Лиды", verification: "Верификация", analytics: "Аналитика" },
    fr: { overview: "Aperçu", users: "Utilisateurs", revenue: "Revenus", data: "Gestionnaire de données", projects: "Gestionnaire de projets", leads: "Prospects", verification: "Vérification", analytics: "Analytique" },
    es: { overview: "Resumen", users: "Usuarios", revenue: "Ingresos", data: "Gestor de datos", projects: "Gestor de proyectos", leads: "Prospectos", verification: "Verificación", analytics: "Analítica" },
    de: { overview: "Übersicht", users: "Benutzer", revenue: "Einnahmen", data: "Datenmanager", projects: "Projektmanager", leads: "Leads", verification: "Verifizierung", analytics: "Analytik" },
    pt: { overview: "Visão Geral", users: "Usuários", revenue: "Receita", data: "Gerenciador de dados", projects: "Gerenciador de projetos", leads: "Leads", verification: "Verificação", analytics: "Análise" },
    ja: { overview: "概要", users: "ユーザー", revenue: "収益", data: "データ管理", projects: "プロジェクト管理", leads: "リード", verification: "本人確認", analytics: "アナリティクス" },
    ko: { overview: "개요", users: "사용자", revenue: "수익", data: "데이터 관리", projects: "프로젝트 관리", leads: "리드", verification: "인증", analytics: "분석" },
    tr: { overview: "Genel Bakış", users: "Kullanıcılar", revenue: "Gelir", data: "Veri Yöneticisi", projects: "Proje Yöneticisi", leads: "Müşteri Adayları", verification: "Doğrulama", analytics: "Analitik" },
    it: { overview: "Panoramica", users: "Utenti", revenue: "Entrate", data: "Gestore dati", projects: "Gestore progetti", leads: "Lead", verification: "Verifica", analytics: "Analitica" },
    nl: { overview: "Overzicht", users: "Gebruikers", revenue: "Omzet", data: "Databeheer", projects: "Projectbeheer", leads: "Leads", verification: "Verificatie", analytics: "Analyse" },
    fa: { overview: "نمای کلی", users: "کاربران", revenue: "درآمد", data: "مدیریت داده", projects: "مدیریت پروژه", leads: "مشتریان بالقوه", verification: "احراز هویت", analytics: "تحلیل" },
    th: { overview: "ภาพรวม", users: "ผู้ใช้", revenue: "รายได้", data: "จัดการข้อมูล", projects: "จัดการโครงการ", leads: "ลูกค้าเป้าหมาย", verification: "ยืนยันตัวตน", analytics: "วิเคราะห์" },
    tl: { overview: "Pangkalahatang-tanaw", users: "Mga Gumagamit", revenue: "Kita", data: "Tagapamahala ng Data", projects: "Tagapamahala ng Proyekto", leads: "Mga Lead", verification: "Beripikasyon", analytics: "Analytics" },
    bn: { overview: "সারসংক্ষেপ", users: "ব্যবহারকারী", revenue: "রাজস্ব", data: "ডেটা ম্যানেজার", projects: "প্রকল্প ম্যানেজার", leads: "লিডস", verification: "যাচাই", analytics: "বিশ্লেষণ" },
    sw: { overview: "Muhtasari", users: "Watumiaji", revenue: "Mapato", data: "Meneja wa Data", projects: "Meneja wa Miradi", leads: "Wateja", verification: "Uthibitisho", analytics: "Uchambuzi" },
  },

  // ─── COMMON UI ───
  ui: {
    en: { search: "Search projects...", filter: "All", compare: "Compare", inquire: "Inquire", whatsapp: "WhatsApp", email: "Email", call: "Call", save: "Save", cancel: "Cancel", close: "Close", back: "Back", next: "Next", reset: "Reset to Default", done: "Done", remove: "Remove", add: "Add", loading: "Loading...", noResults: "No results found", upgrade: "Upgrade to Pro", freePlan: "FREE PLAN", proPlan: "Pro Plan", proTrial: "Pro Trial", enterprise: "Enterprise", signOut: "Sign Out", profile: "Profile", viewAll: "View All", download: "Download", export: "Export CSV" },
    ar: { search: "بحث عن المشاريع...", filter: "الكل", compare: "مقارنة", inquire: "استفسار", whatsapp: "واتساب", email: "البريد", call: "اتصال", save: "حفظ", cancel: "إلغاء", close: "إغلاق", back: "رجوع", next: "التالي", reset: "إعادة تعيين", done: "تم", remove: "إزالة", add: "إضافة", loading: "جاري التحميل...", noResults: "لا توجد نتائج", upgrade: "ترقية إلى برو", freePlan: "الخطة المجانية", proPlan: "خطة برو", proTrial: "تجربة برو", enterprise: "المؤسسات", signOut: "تسجيل الخروج", profile: "الملف الشخصي", viewAll: "عرض الكل", download: "تحميل", export: "تصدير CSV" },
    ur: { search: "منصوبے تلاش کریں...", filter: "سب", compare: "موازنہ", inquire: "استفسار", whatsapp: "واٹس ایپ", email: "ای میل", call: "کال", save: "محفوظ", cancel: "منسوخ", close: "بند", back: "واپس", next: "اگلا", reset: "ڈیفالٹ پر ری سیٹ", done: "مکمل", remove: "ہٹائیں", add: "شامل کریں", loading: "لوڈ ہو رہا ہے...", noResults: "کوئی نتائج نہیں", upgrade: "پرو میں اپ گریڈ", freePlan: "مفت پلان", proPlan: "پرو پلان", proTrial: "پرو ٹرائل", enterprise: "انٹرپرائز", signOut: "سائن آؤٹ", profile: "پروفائل", viewAll: "سب دیکھیں", download: "ڈاؤن لوڈ", export: "CSV ایکسپورٹ" },
    hi: { search: "प्रोजेक्ट खोजें...", filter: "सभी", compare: "तुलना", inquire: "पूछताछ", whatsapp: "व्हाट्सएप", email: "ईमेल", call: "कॉल", save: "सेव", cancel: "रद्द", close: "बंद", back: "वापस", next: "अगला", reset: "रीसेट", done: "पूर्ण", remove: "हटाएँ", add: "जोड़ें", loading: "लोड हो रहा...", noResults: "कोई परिणाम नहीं", upgrade: "प्रो में अपग्रेड", freePlan: "मुफ़्त प्लान", proPlan: "प्रो प्लान", proTrial: "प्रो ट्रायल", enterprise: "एंटरप्राइज़", signOut: "साइन आउट", profile: "प्रोफ़ाइल", viewAll: "सभी देखें", download: "डाउनलोड", export: "CSV एक्सपोर्ट" },
    zh: { search: "搜索项目...", filter: "全部", compare: "对比", inquire: "咨询", whatsapp: "WhatsApp", email: "邮件", call: "电话", save: "保存", cancel: "取消", close: "关闭", back: "返回", next: "下一步", reset: "恢复默认", done: "完成", remove: "移除", add: "添加", loading: "加载中...", noResults: "未找到结果", upgrade: "升级至专业版", freePlan: "免费版", proPlan: "专业版", proTrial: "专业试用", enterprise: "企业版", signOut: "退出", profile: "个人资料", viewAll: "查看全部", download: "下载", export: "导出CSV" },
    ru: { search: "Поиск проектов...", filter: "Все", compare: "Сравнить", inquire: "Запрос", whatsapp: "WhatsApp", email: "Email", call: "Звонок", save: "Сохранить", cancel: "Отмена", close: "Закрыть", back: "Назад", next: "Далее", reset: "По умолчанию", done: "Готово", remove: "Удалить", add: "Добавить", loading: "Загрузка...", noResults: "Ничего не найдено", upgrade: "Перейти на Pro", freePlan: "Бесплатный план", proPlan: "Pro план", proTrial: "Pro пробный", enterprise: "Корпоративный", signOut: "Выйти", profile: "Профиль", viewAll: "Показать все", download: "Скачать", export: "Экспорт CSV" },
    fr: { search: "Rechercher des projets...", filter: "Tout", compare: "Comparer", inquire: "Renseigner", whatsapp: "WhatsApp", email: "Email", call: "Appeler", save: "Enregistrer", cancel: "Annuler", close: "Fermer", back: "Retour", next: "Suivant", reset: "Réinitialiser", done: "Terminé", remove: "Supprimer", add: "Ajouter", loading: "Chargement...", noResults: "Aucun résultat", upgrade: "Passer à Pro", freePlan: "Plan gratuit", proPlan: "Plan Pro", proTrial: "Essai Pro", enterprise: "Entreprise", signOut: "Déconnexion", profile: "Profil", viewAll: "Voir tout", download: "Télécharger", export: "Exporter CSV" },
    es: { search: "Buscar proyectos...", filter: "Todo", compare: "Comparar", inquire: "Consultar", whatsapp: "WhatsApp", email: "Email", call: "Llamar", save: "Guardar", cancel: "Cancelar", close: "Cerrar", back: "Volver", next: "Siguiente", reset: "Restablecer", done: "Listo", remove: "Eliminar", add: "Agregar", loading: "Cargando...", noResults: "Sin resultados", upgrade: "Actualizar a Pro", freePlan: "Plan gratuito", proPlan: "Plan Pro", proTrial: "Prueba Pro", enterprise: "Empresa", signOut: "Cerrar sesión", profile: "Perfil", viewAll: "Ver todo", download: "Descargar", export: "Exportar CSV" },
    de: { search: "Projekte suchen...", filter: "Alle", compare: "Vergleichen", inquire: "Anfragen", whatsapp: "WhatsApp", email: "E-Mail", call: "Anrufen", save: "Speichern", cancel: "Abbrechen", close: "Schließen", back: "Zurück", next: "Weiter", reset: "Zurücksetzen", done: "Fertig", remove: "Entfernen", add: "Hinzufügen", loading: "Laden...", noResults: "Keine Ergebnisse", upgrade: "Auf Pro upgraden", freePlan: "Kostenlos", proPlan: "Pro Plan", proTrial: "Pro Testversion", enterprise: "Enterprise", signOut: "Abmelden", profile: "Profil", viewAll: "Alle anzeigen", download: "Herunterladen", export: "CSV exportieren" },
    pt: { search: "Buscar projetos...", filter: "Todos", compare: "Comparar", inquire: "Consultar", whatsapp: "WhatsApp", email: "Email", call: "Ligar", save: "Salvar", cancel: "Cancelar", close: "Fechar", back: "Voltar", next: "Próximo", reset: "Redefinir", done: "Pronto", remove: "Remover", add: "Adicionar", loading: "Carregando...", noResults: "Nenhum resultado", upgrade: "Atualizar para Pro", freePlan: "Plano gratuito", proPlan: "Plano Pro", proTrial: "Teste Pro", enterprise: "Empresarial", signOut: "Sair", profile: "Perfil", viewAll: "Ver tudo", download: "Baixar", export: "Exportar CSV" },
    ja: { search: "プロジェクトを検索...", filter: "すべて", compare: "比較", inquire: "お問い合わせ", whatsapp: "WhatsApp", email: "メール", call: "電話", save: "保存", cancel: "キャンセル", close: "閉じる", back: "戻る", next: "次へ", reset: "リセット", done: "完了", remove: "削除", add: "追加", loading: "読み込み中...", noResults: "結果なし", upgrade: "Proにアップグレード", freePlan: "無料プラン", proPlan: "Proプラン", proTrial: "Proトライアル", enterprise: "エンタープライズ", signOut: "ログアウト", profile: "プロフィール", viewAll: "すべて表示", download: "ダウンロード", export: "CSVエクスポート" },
    ko: { search: "프로젝트 검색...", filter: "전체", compare: "비교", inquire: "문의", whatsapp: "WhatsApp", email: "이메일", call: "전화", save: "저장", cancel: "취소", close: "닫기", back: "뒤로", next: "다음", reset: "초기화", done: "완료", remove: "삭제", add: "추가", loading: "로딩...", noResults: "결과 없음", upgrade: "Pro로 업그레이드", freePlan: "무료 플랜", proPlan: "Pro 플랜", proTrial: "Pro 체험", enterprise: "엔터프라이즈", signOut: "로그아웃", profile: "프로필", viewAll: "전체 보기", download: "다운로드", export: "CSV 내보내기" },
    tr: { search: "Proje ara...", filter: "Tümü", compare: "Karşılaştır", inquire: "Sorgula", whatsapp: "WhatsApp", email: "E-posta", call: "Ara", save: "Kaydet", cancel: "İptal", close: "Kapat", back: "Geri", next: "İleri", reset: "Sıfırla", done: "Tamam", remove: "Kaldır", add: "Ekle", loading: "Yükleniyor...", noResults: "Sonuç yok", upgrade: "Pro'ya yükselt", freePlan: "Ücretsiz Plan", proPlan: "Pro Plan", proTrial: "Pro Deneme", enterprise: "Kurumsal", signOut: "Çıkış", profile: "Profil", viewAll: "Tümünü gör", download: "İndir", export: "CSV dışa aktar" },
    it: { search: "Cerca progetti...", filter: "Tutti", compare: "Confronta", inquire: "Informazioni", whatsapp: "WhatsApp", email: "Email", call: "Chiama", save: "Salva", cancel: "Annulla", close: "Chiudi", back: "Indietro", next: "Avanti", reset: "Ripristina", done: "Fatto", remove: "Rimuovi", add: "Aggiungi", loading: "Caricamento...", noResults: "Nessun risultato", upgrade: "Passa a Pro", freePlan: "Piano gratuito", proPlan: "Piano Pro", proTrial: "Prova Pro", enterprise: "Enterprise", signOut: "Esci", profile: "Profilo", viewAll: "Vedi tutto", download: "Scarica", export: "Esporta CSV" },
    nl: { search: "Projecten zoeken...", filter: "Alles", compare: "Vergelijken", inquire: "Informeren", whatsapp: "WhatsApp", email: "E-mail", call: "Bellen", save: "Opslaan", cancel: "Annuleren", close: "Sluiten", back: "Terug", next: "Volgende", reset: "Herstellen", done: "Klaar", remove: "Verwijderen", add: "Toevoegen", loading: "Laden...", noResults: "Geen resultaten", upgrade: "Upgrade naar Pro", freePlan: "Gratis plan", proPlan: "Pro Plan", proTrial: "Pro proefversie", enterprise: "Enterprise", signOut: "Afmelden", profile: "Profiel", viewAll: "Alles bekijken", download: "Downloaden", export: "CSV exporteren" },
    fa: { search: "جستجوی پروژه...", filter: "همه", compare: "مقایسه", inquire: "استعلام", whatsapp: "واتساپ", email: "ایمیل", call: "تماس", save: "ذخیره", cancel: "لغو", close: "بستن", back: "بازگشت", next: "بعدی", reset: "بازنشانی", done: "انجام شد", remove: "حذف", add: "افزودن", loading: "بارگذاری...", noResults: "نتیجه‌ای یافت نشد", upgrade: "ارتقا به Pro", freePlan: "پلن رایگان", proPlan: "پلن Pro", proTrial: "آزمایشی Pro", enterprise: "سازمانی", signOut: "خروج", profile: "پروفایل", viewAll: "مشاهده همه", download: "دانلود", export: "خروجی CSV" },
    th: { search: "ค้นหาโครงการ...", filter: "ทั้งหมด", compare: "เปรียบเทียบ", inquire: "สอบถาม", whatsapp: "WhatsApp", email: "อีเมล", call: "โทร", save: "บันทึก", cancel: "ยกเลิก", close: "ปิด", back: "กลับ", next: "ถัดไป", reset: "รีเซ็ต", done: "เสร็จ", remove: "ลบ", add: "เพิ่ม", loading: "กำลังโหลด...", noResults: "ไม่พบผลลัพธ์", upgrade: "อัพเกรดเป็น Pro", freePlan: "แผนฟรี", proPlan: "แผน Pro", proTrial: "ทดลอง Pro", enterprise: "องค์กร", signOut: "ออกจากระบบ", profile: "โปรไฟล์", viewAll: "ดูทั้งหมด", download: "ดาวน์โหลด", export: "ส่งออก CSV" },
    tl: { search: "Maghanap ng proyekto...", filter: "Lahat", compare: "Ihambing", inquire: "Magtanong", whatsapp: "WhatsApp", email: "Email", call: "Tawagan", save: "I-save", cancel: "Kanselahin", close: "Isara", back: "Bumalik", next: "Susunod", reset: "I-reset", done: "Tapos", remove: "Alisin", add: "Idagdag", loading: "Naglo-load...", noResults: "Walang resulta", upgrade: "I-upgrade sa Pro", freePlan: "Libreng Plano", proPlan: "Pro Plano", proTrial: "Pro Trial", enterprise: "Enterprise", signOut: "Mag-sign Out", profile: "Profile", viewAll: "Tingnan lahat", download: "I-download", export: "I-export CSV" },
    bn: { search: "প্রকল্প খুঁজুন...", filter: "সব", compare: "তুলনা", inquire: "জিজ্ঞাসা", whatsapp: "হোয়াটসঅ্যাপ", email: "ইমেইল", call: "কল", save: "সংরক্ষণ", cancel: "বাতিল", close: "বন্ধ", back: "পিছনে", next: "পরবর্তী", reset: "রিসেট", done: "সম্পন্ন", remove: "সরান", add: "যোগ", loading: "লোড হচ্ছে...", noResults: "কোন ফলাফল নেই", upgrade: "Pro তে আপগ্রেড", freePlan: "ফ্রি প্ল্যান", proPlan: "Pro প্ল্যান", proTrial: "Pro ট্রায়াল", enterprise: "এন্টারপ্রাইজ", signOut: "সাইন আউট", profile: "প্রোফাইল", viewAll: "সব দেখুন", download: "ডাউনলোড", export: "CSV এক্সপোর্ট" },
    sw: { search: "Tafuta miradi...", filter: "Zote", compare: "Linganisha", inquire: "Uliza", whatsapp: "WhatsApp", email: "Barua pepe", call: "Piga simu", save: "Hifadhi", cancel: "Ghairi", close: "Funga", back: "Rudi", next: "Endelea", reset: "Weka upya", done: "Tayari", remove: "Ondoa", add: "Ongeza", loading: "Inapakia...", noResults: "Hakuna matokeo", upgrade: "Panda hadi Pro", freePlan: "Mpango wa bure", proPlan: "Mpango wa Pro", proTrial: "Jaribio la Pro", enterprise: "Biashara", signOut: "Ondoka", profile: "Wasifu", viewAll: "Angalia yote", download: "Pakua", export: "Hamisha CSV" },
  },

  // ─── SECTIONS & LABELS ───
  sections: {
    en: { emaarProperties: "Emaar Properties", companyOverview: "Company Overview", revenueBreakdown: "Revenue Breakdown", projectCatalog: "Project Catalog", allProjects: "All Emaar Projects", interactiveMap: "Interactive Map", myPortfolio: "My Portfolio", startTracking: "Track Your Property Investments", competitorAnalysis: "Competitor Analysis", rentalYields: "Rental Yields & ROI", riskAssessment: "Risk Assessment", stockTracker: "Stock Tracker", marketInsights: "Market Insights", daysRemaining: "days remaining", sources: "Sources", notFinancialAdvice: "Not financial advice", language: "Language" },
    ar: { emaarProperties: "إعمار العقارية", companyOverview: "نظرة عامة على الشركة", revenueBreakdown: "تفصيل الإيرادات", projectCatalog: "كتالوج المشاريع", allProjects: "جميع مشاريع إعمار", interactiveMap: "خريطة تفاعلية", myPortfolio: "محفظتي", startTracking: "تتبع استثماراتك العقارية", competitorAnalysis: "تحليل المنافسين", rentalYields: "عوائد الإيجار والعائد على الاستثمار", riskAssessment: "تقييم المخاطر", stockTracker: "متتبع الأسهم", marketInsights: "رؤى السوق", daysRemaining: "أيام متبقية", sources: "المصادر", notFinancialAdvice: "ليست نصيحة مالية", language: "اللغة" },
    ur: { emaarProperties: "اعمار پراپرٹیز", companyOverview: "کمپنی کا جائزہ", revenueBreakdown: "ریونیو کی تفصیل", projectCatalog: "پروجیکٹ کیٹلاگ", allProjects: "تمام اعمار پروجیکٹس", interactiveMap: "انٹرایکٹو نقشہ", myPortfolio: "میرا پورٹ فولیو", startTracking: "اپنی سرمایہ کاری ٹریک کریں", competitorAnalysis: "حریفوں کا تجزیہ", rentalYields: "کرایہ کی آمدنی اور ROI", riskAssessment: "خطرات کا جائزہ", stockTracker: "اسٹاک ٹریکر", marketInsights: "مارکیٹ کی بصیرت", daysRemaining: "دن باقی", sources: "ذرائع", notFinancialAdvice: "مالی مشورہ نہیں", language: "زبان" },
    hi: { emaarProperties: "इमार प्रॉपर्टीज", companyOverview: "कंपनी अवलोकन", revenueBreakdown: "राजस्व विवरण", projectCatalog: "प्रोजेक्ट कैटलॉग", allProjects: "सभी इमार प्रोजेक्ट", interactiveMap: "इंटरैक्टिव मानचित्र", myPortfolio: "मेरा पोर्टफोलियो", startTracking: "अपने निवेश ट्रैक करें", competitorAnalysis: "प्रतिस्पर्धी विश्लेषण", rentalYields: "किराया आय और ROI", riskAssessment: "जोखिम मूल्यांकन", stockTracker: "स्टॉक ट्रैकर", marketInsights: "बाज़ार अंतर्दृष्टि", daysRemaining: "दिन शेष", sources: "स्रोत", notFinancialAdvice: "वित्तीय सलाह नहीं", language: "भाषा" },
    zh: { emaarProperties: "伊玛尔地产", companyOverview: "公司概览", revenueBreakdown: "收入分析", projectCatalog: "项目目录", allProjects: "所有伊玛尔项目", interactiveMap: "互动地图", myPortfolio: "我的投资组合", startTracking: "追踪您的房产投资", competitorAnalysis: "竞争对手分析", rentalYields: "租金收益率与投资回报", riskAssessment: "风险评估", stockTracker: "股票追踪", marketInsights: "市场洞察", daysRemaining: "天剩余", sources: "数据来源", notFinancialAdvice: "非投资建议", language: "语言" },
    ru: { emaarProperties: "Emaar Properties", companyOverview: "Обзор компании", revenueBreakdown: "Распределение дохода", projectCatalog: "Каталог проектов", allProjects: "Все проекты Emaar", interactiveMap: "Интерактивная карта", myPortfolio: "Мой портфель", startTracking: "Отслеживайте свои инвестиции", competitorAnalysis: "Анализ конкурентов", rentalYields: "Доходность аренды и ROI", riskAssessment: "Оценка рисков", stockTracker: "Отслеживание акций", marketInsights: "Аналитика рынка", daysRemaining: "дней осталось", sources: "Источники", notFinancialAdvice: "Не является финансовой рекомендацией", language: "Язык" },
    fr: { emaarProperties: "Emaar Properties", companyOverview: "Aperçu de l'entreprise", revenueBreakdown: "Répartition des revenus", projectCatalog: "Catalogue des projets", allProjects: "Tous les projets Emaar", interactiveMap: "Carte interactive", myPortfolio: "Mon portefeuille", startTracking: "Suivez vos investissements", competitorAnalysis: "Analyse concurrentielle", rentalYields: "Rendements locatifs & ROI", riskAssessment: "Évaluation des risques", stockTracker: "Suivi des actions", marketInsights: "Perspectives du marché", daysRemaining: "jours restants", sources: "Sources", notFinancialAdvice: "Pas un conseil financier", language: "Langue" },
    es: { emaarProperties: "Emaar Properties", companyOverview: "Resumen de la empresa", revenueBreakdown: "Desglose de ingresos", projectCatalog: "Catálogo de proyectos", allProjects: "Todos los proyectos Emaar", interactiveMap: "Mapa interactivo", myPortfolio: "Mi portafolio", startTracking: "Rastrea tus inversiones", competitorAnalysis: "Análisis de competidores", rentalYields: "Rendimientos de alquiler y ROI", riskAssessment: "Evaluación de riesgos", stockTracker: "Seguimiento de acciones", marketInsights: "Perspectivas del mercado", daysRemaining: "días restantes", sources: "Fuentes", notFinancialAdvice: "No es asesoramiento financiero", language: "Idioma" },
    de: { emaarProperties: "Emaar Properties", companyOverview: "Unternehmensübersicht", revenueBreakdown: "Umsatzaufschlüsselung", projectCatalog: "Projektkatalog", allProjects: "Alle Emaar Projekte", interactiveMap: "Interaktive Karte", myPortfolio: "Mein Portfolio", startTracking: "Verfolgen Sie Ihre Investitionen", competitorAnalysis: "Wettbewerbsanalyse", rentalYields: "Mietrenditen & ROI", riskAssessment: "Risikobewertung", stockTracker: "Aktienverfolgung", marketInsights: "Marktanalyse", daysRemaining: "Tage übrig", sources: "Quellen", notFinancialAdvice: "Keine Finanzberatung", language: "Sprache" },
    pt: { emaarProperties: "Emaar Properties", companyOverview: "Visão geral da empresa", revenueBreakdown: "Detalhamento de receita", projectCatalog: "Catálogo de projetos", allProjects: "Todos os projetos Emaar", interactiveMap: "Mapa interativo", myPortfolio: "Meu portfólio", startTracking: "Acompanhe seus investimentos", competitorAnalysis: "Análise de concorrentes", rentalYields: "Rendimentos de aluguel e ROI", riskAssessment: "Avaliação de risco", stockTracker: "Rastreador de ações", marketInsights: "Insights de mercado", daysRemaining: "dias restantes", sources: "Fontes", notFinancialAdvice: "Não é aconselhamento financeiro", language: "Idioma" },
    ja: { emaarProperties: "エマール・プロパティーズ", companyOverview: "企業概要", revenueBreakdown: "収益内訳", projectCatalog: "プロジェクトカタログ", allProjects: "全エマールプロジェクト", interactiveMap: "インタラクティブマップ", myPortfolio: "マイポートフォリオ", startTracking: "投資を追跡", competitorAnalysis: "競合分析", rentalYields: "賃貸利回りとROI", riskAssessment: "リスク評価", stockTracker: "株式トラッカー", marketInsights: "市場分析", daysRemaining: "日残り", sources: "情報源", notFinancialAdvice: "投資助言ではありません", language: "言語" },
    ko: { emaarProperties: "에마르 프로퍼티즈", companyOverview: "회사 개요", revenueBreakdown: "수익 분석", projectCatalog: "프로젝트 카탈로그", allProjects: "모든 에마르 프로젝트", interactiveMap: "인터랙티브 지도", myPortfolio: "내 포트폴리오", startTracking: "투자 추적하기", competitorAnalysis: "경쟁사 분석", rentalYields: "임대 수익률 & ROI", riskAssessment: "리스크 평가", stockTracker: "주식 트래커", marketInsights: "시장 인사이트", daysRemaining: "일 남음", sources: "출처", notFinancialAdvice: "투자 조언이 아닙니다", language: "언어" },
    tr: { emaarProperties: "Emaar Properties", companyOverview: "Şirket Genel Bakışı", revenueBreakdown: "Gelir Dağılımı", projectCatalog: "Proje Kataloğu", allProjects: "Tüm Emaar Projeleri", interactiveMap: "İnteraktif Harita", myPortfolio: "Portföyüm", startTracking: "Yatırımlarınızı takip edin", competitorAnalysis: "Rakip Analizi", rentalYields: "Kira Getirileri & ROI", riskAssessment: "Risk Değerlendirmesi", stockTracker: "Hisse Takibi", marketInsights: "Piyasa Görüşleri", daysRemaining: "gün kaldı", sources: "Kaynaklar", notFinancialAdvice: "Finansal tavsiye değildir", language: "Dil" },
    it: { emaarProperties: "Emaar Properties", companyOverview: "Panoramica aziendale", revenueBreakdown: "Ripartizione ricavi", projectCatalog: "Catalogo progetti", allProjects: "Tutti i progetti Emaar", interactiveMap: "Mappa interattiva", myPortfolio: "Il mio portafoglio", startTracking: "Monitora i tuoi investimenti", competitorAnalysis: "Analisi concorrenza", rentalYields: "Rendimenti affitto & ROI", riskAssessment: "Valutazione rischi", stockTracker: "Tracker azioni", marketInsights: "Analisi di mercato", daysRemaining: "giorni rimasti", sources: "Fonti", notFinancialAdvice: "Non è consulenza finanziaria", language: "Lingua" },
    nl: { emaarProperties: "Emaar Properties", companyOverview: "Bedrijfsoverzicht", revenueBreakdown: "Omzetverdeling", projectCatalog: "Projectcatalogus", allProjects: "Alle Emaar Projecten", interactiveMap: "Interactieve kaart", myPortfolio: "Mijn Portefeuille", startTracking: "Volg uw investeringen", competitorAnalysis: "Concurrentieanalyse", rentalYields: "Huurrendementen & ROI", riskAssessment: "Risicobeoordeling", stockTracker: "Aandelentracker", marketInsights: "Marktinzichten", daysRemaining: "dagen resterend", sources: "Bronnen", notFinancialAdvice: "Geen financieel advies", language: "Taal" },
    fa: { emaarProperties: "اعمار", companyOverview: "نمای کلی شرکت", revenueBreakdown: "تفکیک درآمد", projectCatalog: "کاتالوگ پروژه", allProjects: "همه پروژه‌های اعمار", interactiveMap: "نقشه تعاملی", myPortfolio: "سبد من", startTracking: "سرمایه‌گذاری خود را دنبال کنید", competitorAnalysis: "تحلیل رقبا", rentalYields: "بازده اجاره و ROI", riskAssessment: "ارزیابی ریسک", stockTracker: "پیگیری سهام", marketInsights: "تحلیل بازار", daysRemaining: "روز باقیمانده", sources: "منابع", notFinancialAdvice: "مشاوره مالی نیست", language: "زبان" },
    th: { emaarProperties: "Emaar Properties", companyOverview: "ภาพรวมบริษัท", revenueBreakdown: "รายละเอียดรายได้", projectCatalog: "แคตตาล็อกโครงการ", allProjects: "โครงการ Emaar ทั้งหมด", interactiveMap: "แผนที่โต้ตอบ", myPortfolio: "พอร์ตของฉัน", startTracking: "ติดตามการลงทุนของคุณ", competitorAnalysis: "วิเคราะห์คู่แข่ง", rentalYields: "ผลตอบแทนเช่า & ROI", riskAssessment: "ประเมินความเสี่ยง", stockTracker: "ติดตามหุ้น", marketInsights: "วิเคราะห์ตลาด", daysRemaining: "วันที่เหลือ", sources: "แหล่งข้อมูล", notFinancialAdvice: "ไม่ใช่คำแนะนำทางการเงิน", language: "ภาษา" },
    tl: { emaarProperties: "Emaar Properties", companyOverview: "Pangkalahatang-tanaw ng Kumpanya", revenueBreakdown: "Detalye ng Kita", projectCatalog: "Katalogo ng Proyekto", allProjects: "Lahat ng Proyekto ng Emaar", interactiveMap: "Interactive na Mapa", myPortfolio: "Aking Portfolio", startTracking: "I-track ang iyong investments", competitorAnalysis: "Pagsusuri ng Kakumpitensya", rentalYields: "Kita sa Renta & ROI", riskAssessment: "Pagsusuri ng Panganib", stockTracker: "Stock Tracker", marketInsights: "Kaalaman sa Pamilihan", daysRemaining: "araw na natitira", sources: "Mga Pinagmulan", notFinancialAdvice: "Hindi payo sa pananalapi", language: "Wika" },
    bn: { emaarProperties: "ইমার প্রপার্টিজ", companyOverview: "কোম্পানি সারসংক্ষেপ", revenueBreakdown: "আয়ের বিশ্লেষণ", projectCatalog: "প্রকল্প ক্যাটালগ", allProjects: "সব ইমার প্রকল্প", interactiveMap: "ইন্টারেক্টিভ মানচিত্র", myPortfolio: "আমার পোর্টফোলিও", startTracking: "আপনার বিনিয়োগ ট্র্যাক করুন", competitorAnalysis: "প্রতিযোগী বিশ্লেষণ", rentalYields: "ভাড়া আয় ও ROI", riskAssessment: "ঝুঁকি মূল্যায়ন", stockTracker: "স্টক ট্র্যাকার", marketInsights: "বাজার বিশ্লেষণ", daysRemaining: "দিন বাকি", sources: "সূত্র", notFinancialAdvice: "আর্থিক পরামর্শ নয়", language: "ভাষা" },
    sw: { emaarProperties: "Emaar Properties", companyOverview: "Muhtasari wa Kampuni", revenueBreakdown: "Mgawanyo wa Mapato", projectCatalog: "Katalogi ya Miradi", allProjects: "Miradi Yote ya Emaar", interactiveMap: "Ramani ya Mwingiliano", myPortfolio: "Kanda Yangu", startTracking: "Fuatilia uwekezaji wako", competitorAnalysis: "Uchambuzi wa Washindani", rentalYields: "Mapato ya Kodi & ROI", riskAssessment: "Tathmini ya Hatari", stockTracker: "Kifuatilia Hisa", marketInsights: "Maarifa ya Soko", daysRemaining: "siku zilizobaki", sources: "Vyanzo", notFinancialAdvice: "Si ushauri wa kifedha", language: "Lugha" },
  },
};

// ─── CONTEXT ───
const I18nContext = createContext();

export function I18nProvider({ children }) {
  const [lang, setLangRaw] = useState(() => {
    try { return localStorage.getItem("dxb_lang") || "en"; } catch { return "en"; }
  });
  const setLang = (code) => { setLangRaw(code); try { localStorage.setItem("dxb_lang", code); } catch {} };
  const langInfo = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];
  const t = (section, key) => T[section]?.[lang]?.[key] || T[section]?.en?.[key] || key;
  const dir = langInfo.dir;

  return (
    <I18nContext.Provider value={{ lang, setLang, t, dir, langInfo, LANGUAGES }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() { return useContext(I18nContext); }
export default T;
